### ISSUE TITLE
Feature request: elastic gridpanel layout

### ISSUE THREAD

**Issue by erwin-mouthaan** [DelphiWorlds/Kastri#1]
Normally when TCellItem.SizeStyle is set to TSizeStyle.Auto the row or column is sized automatically, but not Height of gridpanel itself unfortunately. Elastic feature matters if cell contains top aligned label with AutoSize and WordWrap set to True. 
 
Dave may actually have code for that already.. he just need to find it!
https://delphiworlds.slack.com/archives/C014PCSF3TK/p1592298113013900

**Comment by DelphiWorlds** [comment]
I might need some help with the requirements of this one. If all the row heights are auto, they're a percentage of the size of the gridpanel - I can understand if the rows are a fixed size.

Can you clarify this a bit more?

**Comment by erwin-mouthaan** [comment]
If all the row heights are auto, then all row heights are sized automatically. What do you mean with "they're a percentage of the size of the gridpanel"?

http://docwiki.embarcadero.com/Libraries/Sydney/en/FMX.Layouts.TGridPanelLayout.TCellItem.SizeStyle

When for label both AutoSize and WordWrap are set to True, the label's width does not change, and the height increases to show the full Text. If height of top aligned label increases automatically, it would be nice if height of gridpanellayout would be elastic.

http://docwiki.embarcadero.com/Libraries/Sydney/en/FMX.StdCtrls.TLabel.AutoSize

Or do we have to put elasticlayout in cell item of gridpanel component first? And elasticlayout is parent of label? A DW.ElasticLayout.TGridPanelLayout component would be great.

**Comment by DelphiWorlds** [comment]
Sorry it has taken so long.. I've now updated the `DW.ElasticLayout` unit
