### ISSUE TITLE
DW.Android.Helpers

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/Kastri#100]
Hello
i download last kastri and use Playground and Kastrifree
when i run my app show this error in file DW.Android.Helpers (lines 626 & 628): 
[DCC Error] DW.Android.Helpers.pas(626): E2003 Undeclared identifier: 'cDWBroadcastReceiverExtraServiceClassName'
[DCC Error] DW.Android.Helpers.pas(628): E2003 Undeclared identifier: 'cDWBroadcastReceiverExtraJobId'

**Comment by DelphiWorlds** [comment]
When using Kastri, use the latest file for DW.Consts.Android:
https://github.com/DelphiWorlds/Kastri/blob/master/Core/DW.Consts.Android.pas
Playground is a separate repo

**Comment by kabiri** [comment]
the file DW.Consts.Android.pas in Kastri/Core is difrent with DW.Consts.Android.pas in Playground/Core
When I use both Kastri and Playground, then I add the path of both files to Delphi. But Delphi does not know which version is the last.

**Comment by DelphiWorlds** [comment]
I've now updated both so they are aligned
