### ISSUE TITLE
JLocalTime not available in Tokyo version

### ISSUE THREAD

**Issue by tazj** [DelphiWorlds/Kastri#101]
Hello,

DW.Androidapi.JNI.App references JLocalTime under JUiModeManager

    function getCustomNightModeEnd: JLocalTime; cdecl;
    function getCustomNightModeStart: JLocalTime; cdecl;
    procedure setCustomNightModeEnd(time: JLocalTime); cdecl;
    procedure setCustomNightModeStart(time: JLocalTime); cdecl;

I have Tokyo, Rio, Sydney and Alexandria versions.  The last three have JLocalTime.  Tokyo gives these messages.

[DCC Error] DW.Androidapi.JNI.App.pas(226): E2003 Undeclared identifier: 'JLocalTime'
[DCC Error] DW.Androidapi.JNI.App.pas(227): E2005 'JLocalTime' is not a type identifier
[DCC Error] DW.Androidapi.JNI.App.pas(231): E2005 'JLocalTime' is not a type identifier
[DCC Error] DW.Androidapi.JNI.App.pas(232): E2005 'JLocalTime' is not a type identifier
[DCC Fatal Error] DW.Android.Helpers.pas(62): F2063 Could not compile used unit 'DW.Androidapi.JNI.App.pas'

I am using TAndroidHelperEx.QuitApplication in a Sydney application and it works great.  Trying to use it in the same application under Tokyo (older Android OS - v4.4).

Is there a workaround?

Thanks.

Tony Jackson

**Comment by DelphiWorlds** [comment]
You could solve it by copying the imports for the missing classes into `DW.Androidapi.JNI.App.pas`, but if you have the later versions, why are you concerned with compiling in Tokyo? It would be made worse if you were attempting to compile an app for Play Store.

**Comment by tazj** [comment]
I thought about that but I was willing to let the author(s) make the possible change(s).  If not, I will "attempt" my own change(s).

The apps do not hit the Play Store.  We build, install and update the apps for our customers.  Not for consumer use.

Thanks.

**Comment by DelphiWorlds** [comment]
I've added a placeholder import for JLocalTime so that it should compile with Delphi 10.2.x

**Comment by tazj** [comment]
I will check it out very soon.

Thanks.

**Comment by tazj** [comment]
To not my surprise, this did not work for Android OS under v5 (the one I am supporting is v4.4 - KitKat).  Apparently the capability to remove the task does not exist (at least trying this way), but it does work for those v5 and over.

Thanks. 

class procedure TAndroidHelperEx.QuitApplication;
begin
  if TOSVersion.Check(5) then
    TAndroidHelper.Activity.finishAndRemoveTask
  else
    TAndroidHelper.Activity.finish;
  TJSystem.JavaClass.exit(2);
end;

**Comment by DelphiWorlds** [comment]
OK.. closing this issue as it now compiles in 10.2
