### ISSUE TITLE
[VKVertScrollBox] Scroll position is off when using Android 12

### ISSUE THREAD

**Issue by DelphiWorlds** [DelphiWorlds/Kastri#103]
As per title. The controls are slightly below where they should be, at least for me

**Comment by rhazell-numze** [comment]
Any update on this issue, please?

I've also encountered this on a Samsung Galaxy Z Fold3 5G running Android 12.

However, weirdly enough... positioning is correct on the large screen (i.e. when the device is open) but not correct when using the smaller front screen.

Let me know if you'd like to see some screen shots.

Thanks in advance.

**Comment by DelphiWorlds** [comment]
Thanks for the reminder - I may get to this in the next couple of days

**Comment by rhazell-numze** [comment]
That would be much appreciated.

**Comment by DelphiWorlds** [comment]
An update: I started looking at this a day or so ago - it seems on later versions of Android the reported size of the virtual keyboard is not accurate, or some other factor is causing the problem. Still looking into it..

**Comment by DelphiWorlds** [comment]
Please see: https://github.com/DelphiWorlds/Playground/tree/main/Demos/VKObserver
