### ISSUE TITLE
[Scheduled Services] App closed!

### ISSUE THREAD

**Issue by barnisoft** [DelphiWorlds/Kastri#104]
Hi there! I want to use the scheduled services, and i did try the demo example in delphi 10.4 and delphi 11 and when i open the app, first i get a notification then after 60 second the app closed! Whta the problem? Tested on android 10! Thank you so much your help!

**Comment by DelphiWorlds** [comment]
Which demo are you using?

**Comment by barnisoft** [comment]
Scheduled Services Demo

**Comment by barnisoft** [comment]
If i skip this line, then the app not closed, but then not work the alarm! I think here is the some problem, but I don't know what! :( Help me please! I use the android 64bit!

if FInterval > 0 then
  begin
    // Allow for alarms while in "doze" mode
    if TOSVersion.Check(6) then
      TAndroidHelper.AlarmManager.setExactAndAllowWhileIdle(TJAlarmManager.JavaClass.RTC_WAKEUP, GetTimeFromNowInMillis(AInterval), FAlarmIntent)
    else
      TAndroidHelper.AlarmManager.setRepeating(TJAlarmManager.JavaClass.RTC_WAKEUP, AStartAt, AInterval, FAlarmIntent);
  end
  else
    TAndroidHelper.AlarmManager.&set(TJAlarmManager.JavaClass.RTC_WAKEUP, AStartAt, FAlarmIntent);
end;

**Comment by DelphiWorlds** [comment]
There is no Scheduled Services Demo in Kastri. There is one in KastriFree, however that repo is now deprecated.

**Comment by barnisoft** [comment]
Thank you so much! Then i will try something and i will looking what's wrong! :)
