### ISSUE TITLE
[EMBTFCM Demo] iOS Delphi 11.1: App crashes when starting

### ISSUE THREAD

**Issue by viniziowow** [DelphiWorlds/Kastri#105]
I did all the steps indicated on the Embarcadero website and in the example of Kastri:
  - Create the APN key on the developer.apple site...;
- Import the key in Firebase console;
- GoogleService-Info.plist in the "Resources" folder;
- Reference Firebase directories in "Framework search patch";
- Edit the iOSapi.FirebaseMessaging.pas unit;
- Change the property "CFBundleIdentifier" and others;
- etc...
I tried using the Firebase version recommended by Embarcadero 6.18, 6.28, 7.7 and the latest release. In all versions of Firebase the example when starting closes without being able to catch the error.
Can anyone tell me if I'm skipping something?

**Comment by DelphiWorlds** [comment]
Something that is missing from the documentation is the requirement to use a value of `-ObjC` for `Options passed to the LD linker` in the Linking section (Building > Delphi Compiler Linking) of the Project Options, as per the demo. Please ensure you have that configured.

**Comment by viniziowow** [comment]
Yes, I did that too. Even so the problem persists.

**Comment by DelphiWorlds** [comment]
What do you have as the Remote Path for the GoogleService-Info.plist file?

**Comment by DelphiWorlds** [comment]
Also, are you actually using the demo, or is this your own project? If it's your own, can you try with the demo first?

**Comment by DelphiWorlds** [comment]
If the app is crashing, it won't have anything to do with the APNs key - most likely some other issue. Can you zip the project without the GoogleService-info.plist and attach it here? (Do a clean first to remove generated binaries)

**Comment by viniziowow** [comment]
[EMBTFCM.zip](https://github.com/DelphiWorlds/Kastri/files/9065788/EMBTFCM.zip)

**Comment by DelphiWorlds** [comment]
I've now pushed a fix to this unit:
https://github.com/DelphiWorlds/Kastri/blob/master/Features/Notifications/DW.PushNotification.pas
Which should solve the crash

**Comment by viniziowow** [comment]
In the example it worked perfectly. But in my application it still keeps closing when starting. It's all exactly the same. Very strange...

**Comment by viniziowow** [comment]
Following the steps of RSP-18329 the problem was solved. It really is an incompatibility between FireDAC with SQLite and the Firebase SDKs.
