### ISSUE TITLE
Syntax error in DW.Location.Android line 97

### ISSUE THREAD

**Issue by MHumm** [DelphiWorlds/Kastri#106]
At least my D11.1 says there's a syntax error in line 97 of SW.Location.Android. In fact there are two and this is the contents as it should be:

  {$IF CompilerVersion < 35} DW.Androidapi.JNI.SupportV4, {$ELSE} DW.Androidapi.JNI.AndroidX.LocalBroadcastManager, {$ENDIF}

The errors are: ; at the end after } but the uses clause has at least one further unit and missing , after the units in the ifdefs

**Comment by DelphiWorlds** [comment]
Fixed
