### ISSUE TITLE
KastriFMX.dproj does not compile

### ISSUE THREAD

**Issue by MHumm** [DelphiWorlds/Kastri#108]
Trying to compile KastriFMX, as this seems to be the project to isntall the native controls, does result in the error that OnLongPress; in DW.NativeButton.pas is not present in the base class.

Commenting this out makes the project compile. But there's still a warning 
[dcc32 Warnung] KastriFMX.dpk(44): W1033 The Unit 'DW.NativeControlModel' has been implicietely imported in package 'KastriFMX'

**Comment by DelphiWorlds** [comment]
Fixed
