### ISSUE TITLE
Dw.webchromeclient

### ISSUE THREAD

**Issue by alissonrodrigo** [DelphiWorlds/Kastri#114]
With DW.WebChromeClient can I capture the click on html elements?  I can't in fmx yet

**Comment by DelphiWorlds** [comment]
Please refer to: https://github.com/DelphiWorlds/Kastri/issues/115

**Comment by alissonrodrigo** [comment]
Thanks, this was exactly what I was looking for. There is no reference to this in the sources. Do you have a usage example?

**Comment by DelphiWorlds** [comment]
I'm still working on it. I'll have something by the middle of the week

**Comment by DelphiWorlds** [comment]
I'll revisit this soon

**Comment by DelphiWorlds** [comment]
I'm closing this issue in preference to: https://github.com/DelphiWorlds/Kastri/issues/115
