### ISSUE TITLE
[WebBrowserExt] Enhance TWebBrowser

### ISSUE THREAD

**Issue by DelphiWorlds** [DelphiWorlds/Kastri#115]
TWebBrowserExt is in development. The initial features are:

* Execute JavaScript and be able to handle results
* Print web pages or plain text (initially Android only)
* Handle elements events such as onclick 
* Set UserAgent property (maybe not all platforms)

...and possibly others.

**Comment by alissonrodrigo** [comment]
News???

**Comment by DelphiWorlds** [comment]
Still working on it. I thought I had something that would work on all platforms, however WebView on Android appears to have problems with iframe elements that use unsupported protocols (Windows has no such problem)

**Comment by DelphiWorlds** [comment]
Just bumping this issue. Hopefully something soon, but again the onclick thing is problematic

**Comment by DelphiWorlds** [comment]
I've managed to implement handling clicking of elements. I'll be releasing something soon

**Comment by alissonrodrigo** [comment]
Thanks for the effort and for sharing. When you have news post

**Comment by DelphiWorlds** [comment]
I have now pushed the work in progress, for which the demo is [here](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/WebBrowserExt). Please read the readme :-)

**Comment by alissonrodrigo** [comment]
Very good, I took a look at the documentation and the demo code, the kastri codes I haven't had the chance to see yet... but thanks a lot for the job! Gratitude

**Comment by DelphiWorlds** [comment]
Please let me know if it's able to do everything you need.

**Comment by DelphiWorlds** [comment]
Closing due to no response
