### ISSUE TITLE
I add setlanguage function to TTS but Speak play default language

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/Kastri#117]
i add procedure
`
procedure TPlatformTextToSpeech.setLanguage(language: string);
begin
 FTextToSpeech.setLanguage(TJLocale.JavaClass.init(StringToJString(language)));
end;
`

and

`
procedure TTextToSpeech.setLanguage(language: string);
begin
  FPlatformTextToSpeech.setLanguage(language);
end;
`

but Speak function play default language

**Comment by DelphiWorlds** [comment]
You have not shown what value you are passing for `language`. Also, what are you expecting to happen? Remember that it is not a translation service - TextToSpeech will simply speak in an accent that is compatible with the selected value.

**Comment by DelphiWorlds** [comment]
I've now added support for selecting the language voice via the Language property. Note that it needs to be in BCP 47 format as per this table: https://www.techonthenet.com/js/language_tags.php

Note that **not all languages are supported on each platform**. The languages used in the demo are supported (at least) on Android, iOS and macOS. Windows support is yet to be added

**Comment by kabiri** [comment]
> You have not shown what value you are passing for `language`. Also, what are you expecting to happen? Remember that it is not a translation service - TextToSpeech will simply speak in an accent that is compatible with the selected value.
I use  BCP 47 format :
  FSpeaker.Setlanguage('tr_TR');
  FSpeaker.Speak(lblText.Text);
but device speek English

**Comment by DelphiWorlds** [comment]
> but device speek English

If you have English text, that is what it will read - it does not translate to Turkish for you.

**Comment by kabiri** [comment]
> > but device speek English
> 
> If you have English text, that is what it will read - it does not translate to Turkish for you.

Thanks
I download new version and it work fine.

**Comment by kabiri** [comment]
i found problem
i use 
`FSpeaker.Setlanguage('tr_TR');`
but true is tr-TR

**Comment by DelphiWorlds** [comment]
The code does not have a `SetLanguage` method, it has a `Language` property, and yes.. you should use `tr-TR`, which conforms to the BCP 47 specification.

**Comment by kabiri** [comment]
I talked about the code I had written.
Later I got your code and used the language property.
In any case, thank you for your work and answer.
