### ISSUE TITLE
Admob InterstitialAd and banner not show on adnroid 12

### ISSUE THREAD

**Issue by barnisoft** [DelphiWorlds/Kastri#120]
Hi there, i did try use the admob adds banner and interstitialad! If i use only banner, then work is good, but if i use both two the banner and interstitial, then not show the banner and not work interstitial on andorid 12! On andorid 10 and 11 good work! What be the problem?  I work with delphi 11.2! Thank you so mutch your help and your time!

**Comment by DelphiWorlds** [comment]
Is this from the demo, or in your own app?

**Comment by barnisoft** [comment]
Is this from my app! The demo i can't didn't try, because I want to compiller i get an error! When i try my app on android 10-11, then everything good work, just only on andoird 12 not work nothing, banner and interstitial! If i use only banner, then good work on andorid 12 too.

**Comment by barnisoft** [comment]
![Screenshot_20221021-110300](https://user-images.githubusercontent.com/76049976/197158336-904abb09-01b3-4bbc-9e15-d6c47c4cf854.jpg)
![Screenshot_20221021-110311](https://user-images.githubusercontent.com/76049976/197158341-335b5c98-9f97-4963-a1fa-2ff263c0bd59.jpg)

**Comment by barnisoft** [comment]
![IMG-20221021-WA0015](https://user-images.githubusercontent.com/76049976/197158417-773f7472-e9e9-4d53-8359-690af0ec5391.jpg)

**Comment by DelphiWorlds** [comment]
I can only help if I know if you have your app configured correctly. Adding screenshots will not help

**Comment by barnisoft** [comment]
The first two image about andorid 10, the other image about android 12!

**Comment by DelphiWorlds** [comment]
Screenshots will not help - you need to show that you have configured your application correctly. Check the demo readme, and the demo project configuration

**Comment by barnisoft** [comment]
Yes, I'm so sorry! So, I added to my project, the "Api, Controls, Core, Futures/AdMob, Futures/SpeechRecognition, Include" dirs and i added in the project libraries the "dw-admob.jar, and i added in the manifest.xml the meta data, my admob Application ID.

<%application-meta-data%>
  <meta-data
android:name="[com.google.android.gms.ads](http://com.google.android.gms.ads/).APPLICATION_ID"
android:value="ca-app-pub-xxxxxxxxxxxxxxxxxxxxxxxxx"/>
<%uses-libraries%>



constructor TForm1.Create(AOwner: TComponent);
begin
  inherited;
  FIntAd := TInterstitialAd.Create;
  FIntAd.TestMode := False;
  FIntAd.AdUnitId:='ca-app-pub-xxxxxxxxxxx'; //this ID at interstitial.
  FIntAd.OnAdDismissedFullScreenContent := AdDismissedFullScreenContentHandler;
  FIntAd.OnAdFailedToShowFullScreenContent := AdFailedToShowFullScreenContentHandler;
  FIntAd.OnAdWillPresentFullScreenContent := AdWillPresentFullScreenContentHandler;
  FIntAd.OnAdLoaded := AdLoadedHander;
  FIntAd.OnAdFailedToLoad := AdFailedToLoadHandler;

  FRewAd := TRewardedAd.Create;
  FRewAd.TestMode := True;
  FRewAd.OnAdDismissedFullScreenContent := AdDismissedFullScreenContentHandler;
  FRewAd.OnAdFailedToShowFullScreenContent := AdFailedToShowFullScreenContentHandler;
  FRewAd.OnAdWillPresentFullScreenContent := AdWillPresentFullScreenContentHandler;
  // RewardAds only
  FRewAd.OnUserEarnedReward := UserEarnedRewardHandler;

//  FOpenAd := TAppOpenAd.Create;
//  FOpenAd.TestMode := True;
//  FOpenAd.OnAdDismissedFullScreenContent := AdDismissedFullScreenContentHandler;
//  FOpenAd.OnAdFailedToShowFullScreenContent := AdFailedToShowFullScreenContentHandler;
//  FOpenAd.OnAdWillPresentFullScreenContent := AdWillPresentFullScreenContentHandler;
//  FOpenAd.Load;

FSpeech := TSpeechRecognition.Create;
  FSpeech.StopInterval := 1500;
  FSpeech.OnAuthorizationStatus := SpeechAuthorizationHandler;
  FSpeech.OnRecording := SpeechRecordingHandler;
  FSpeech.OnStopped := SpeechStoppedHandler;
  FSpeech.OnText := SpeechTextHandler;
  // FSpeech.Language := 'es-MX'; // For example, if you are expecting Spanish (Mexican)
  DoStopped;
end;


procedure TForm1.OnShow(Sender: TObject);
begin
  AdMobBannerAd1.UnitId:= 'ca-app-pub-xxxxxxxxxxx';  // this other ID at banner
//  AdMobBannerAd1.AdSize := TAdMobBannerAdSize.Adaptive;
  AdMobBannerAd1.LoadAd;
end;

**Comment by barnisoft** [comment]
could be the problem that, I right now change the delphi 11.1 about delphi 11.2, but i did only uninstall the delphi 11.1,  and install delphi 11.2 and maybe stayed some file from delphi 11.1? Because, if i use the FMX.PhoneDialer too then my app not running on the android 12 i get only black screen!?

**Comment by DelphiWorlds** [comment]
Your problem is with PhoneDialer, not AdMob - please see this bug report: https://quality.embarcadero.com/browse/RSP-39445

**Comment by barnisoft** [comment]
No, I have problem with AdMob, and I now test and have a problem API 32! The interstitial ads not work with API 32!

**Comment by DelphiWorlds** [comment]
"not work" is too vague - please be more specific, e.g. does the application start, or is it stuck on the splash screen again? If the app starts, does the Banner ad work, but not the Interstitial? Does the Reward ad work? Are you launching via the IDE, and if so, does it raise any errors? Give exact details

It may help to use a logcat viewer such as [Device Lens](https://github.com/DelphiWorlds/DeviceLens) to check messages for any clues as to what is going wrong.

**Comment by barnisoft** [comment]
Alright, I will try tomorrow with Device Lens, and after i will write!
Thank you so much!

**Comment by barnisoft** [comment]
Hi, I did now check it with Device Lens, and i did take pictures! Not runing banner and interstitial too android 12! I use Delphi 11.2! 
![20221026_224354](https://user-images.githubusercontent.com/76049976/198135873-427ef98a-fb6b-4744-a02e-ea76afa34789.jpg)
![20221026_224338](https://user-images.githubusercontent.com/76049976/198135896-426f2bd3-793e-442b-aa58-c6f968433f63.jpg)
![20221026_224557](https://user-images.githubusercontent.com/76049976/198135902-f2a3547f-9a52-4b23-8fec-07843d11cfb1.jpg)

**Comment by DelphiWorlds** [comment]
See this link regarding AdMob error code 3:
https://support.google.com/admob/thread/134289592/error-code-3-no-ad-config-on-android?hl=en

**Comment by DelphiWorlds** [comment]
Incidentally, when this error occurs, the Kastri Admob code will call the `OnAdFailedToShowFullScreenContent` event (for full screen ads, like Interstitial), which you can use to determine what the error is.

**Comment by barnisoft** [comment]
Thank you your help! I will see this 😊

**Comment by barnisoft** [comment]
I did have was the problem, until i not upload the new version on google play! Aftert I uploaded on google play, and everything good work! I want to other ask! How to check it when someone closed the interstitial ad or reward ad? Because I want to do something when someone closed the interstitial or rewards ad! Can you help me please? Thank you so much!

**Comment by DelphiWorlds** [comment]
> How to check it when someone closed the interstitial ad or reward ad?

Both of these have an event: `OnAdDismissedFullScreenContent`, which happens when the user closes the ad. See [here](https://github.com/DelphiWorlds/Kastri/blob/8a6e771df796d460bb2f600afb218b214ebe7347/Demos/AdMob/Unit1.pas#L65), and [here](https://github.com/DelphiWorlds/Kastri/blob/8a6e771df796d460bb2f600afb218b214ebe7347/Demos/AdMob/Unit1.pas#L105) in the demo. Also, `TRewardedAd` has an event: `OnUserEarnedReward` which provides Amount and RewardType information.

**Comment by barnisoft** [comment]
thank you so much your time and help! thank you so much everithing!😊😇
