### ISSUE TITLE
[Biometric] Hiding biometric prompt - delphi 11

### ISSUE THREAD

**Issue by tommyhustava** [DelphiWorlds/Kastri#123]
Delphi 11, using biometric prompt. After success verify the prompt goes to hide. After unsuccess (denied) verify prompt is not hided and after repeatly used biometry the events from this prompt is dead - not detected in my application. I need hide the biometric prompt after unsuccess (denied) verify.

**Comment by DelphiWorlds** [comment]
Can you specify what make/model device you have, and what version of Android?

**Comment by DelphiWorlds** [comment]
Thanks for the report! I suspect there's an option to dismiss on the first denial, or just prevent the event being fired if the denial leaves the dialog showing. I'll be looking at that soon...

**Comment by tommyhustava** [comment]
Samsung Note 10+ 12Gb/256GB, android 12

Dňa ut 25. 10. 2022, 20:55 DelphiWorlds ***@***.***>
napísal(a):

**Comment by DelphiWorlds** [comment]
I've just pushed an update which should fix the issue. Note that there is now an `AllowedAttempts` property (which defaults to 0, which means unlimited attempts). If you set this to a value of `1`, it will allow only one attempt before closing the auth dialog

**Comment by tommyhustava** [comment]
Thank you, but i have problem with compilation:

1. line 142 in dw.biometric.android.pas
procedure TPlatformBiometric.Cancel;
begin
  TJDWBiometricFragmentActivity.JavaClass.stop;
end;

delphi 11 says: "[DCC Error] DW.Biometric.Android.pas(142): E2003
Undeclared identifier: 'stop'"


2.

line 292 in dw.biometric.android.pas
    if LAuthRes =
TJDWBiometricFragmentActivity.JavaClass.AUTHENTICATION_RESULT_SUCCESS then

line 300 i n dw.biometric.android.pas
    else if LAuthRes =
TJDWBiometricFragmentActivity.JavaClass.AUTHENTICATION_RESULT_ERROR then

line 320 i n dw.biometric.android.pas
    else if LAuthRes =
TJDWBiometricFragmentActivity.JavaClass.AUTHENTICATION_RESULT_FAILED then

delphi 11 says: "[DCC Error] DW.Biometric.Android.pas(292): E2008
Incompatible types"

3. line 324 i n dw.biometric.android.pas
        TJDWBiometricFragmentActivity.JavaClass.cancel;

delphi 11 says: "[DCC Error] DW.Biometric.Android.pas(324): E2003
Undeclared identifier: 'cancel'"

I have only simply replaced content in files dw.biometric.pas and
dw.biometric.android.pas.

st 26. 10. 2022 o 22:28 DelphiWorlds ***@***.***> napísal(a):

**Comment by tommyhustava** [comment]
Sorry for my "brainfog" :-)
I have reinstalled complete package of kastri and everything worked fine.

št 27. 10. 2022 o 10:49 Tomáš Húšťava ***@***.***> napísal(a):

**Comment by DelphiWorlds** [comment]
Yes, when pushing an update, it can include other files in Kastri. You should use a git client to manage your local copy because changes are made on a regular basis.
