### ISSUE TITLE
[Kastri-free Notifications demo]

### ISSUE THREAD

**Issue by tommyhustava** [DelphiWorlds/Kastri#124]
I want use your replacement of notifications in my app with Delphi 11.0. App targetting is set to API level 33. Error message are displayed od Android 12 device.
![Screenshot_20221028_230201](https://user-images.githubusercontent.com/116656429/198733028-a7081d8f-d748-4c21-803b-4e32d9d957b2.jpg)

**Comment by DelphiWorlds** [comment]
You should be able to just replace the units from the Features\Notifications folder in Kastri

**Comment by tommyhustava** [comment]
I have copied folder Features from Kastri to Kastri-free and app freezes on splash screen. On google i have found "_Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles._". How to modify this flag?

**Comment by DelphiWorlds** [comment]
You will also need to add the `dw-kastri-base-2.0.0.jar` library (located in [Kastri\Lib](https://github.com/DelphiWorlds/Kastri/tree/master/Lib)) to your project. In Project Manager, under the Android 32-bit platform, there is a Libraries node. Right-click it and click Add, select the `dw-kastri-base-2.0.0.jar` file and click OK

**Comment by DelphiWorlds** [comment]
> On google i have found "Strongly consider using FLAG_IMMUTABLE..

> How to modify this flag?

The flag is already being [set in the Notifications code](https://github.com/DelphiWorlds/Kastri/blob/8a6e771df796d460bb2f600afb218b214ebe7347/Features/Notifications/DW.Notifications.Android.pas#L437)

**Comment by tommyhustava** [comment]
I have copied folder Features from Kastri to Kastri-free and app freezes on splash screen. On google i have found "_Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles._". How to modify this flag?

**Comment by tommyhustava** [comment]
Thank you. I have add "**dw-kastri-base-2.0.0.jar**" to library node. Now ican't compile project notification demo with compiler error "_[PAClient Error] Error: E7688 Unable to execute '"C:\Program Files\Java\jdk-19\bin\java.exe" -jar "c:\program files (x86)\embarcadero\studio\22.0\bin\Android\embt-d8-2.2.64.jar" --release --min-api 23 --output "D:\SourceProg\Android\KastriFree-master\Demos\Notifications\Android\Release\NotificationsDemo.classes" --input-list "D:\SourceProg\Android\KastriFree-master\Demos\Notifications\Android\Release\input-list.txt"' (Error 1)_". Please help me.

**Comment by Morrismx** [comment]
Hi, why are you using KastriFree? You should use Kastri.

 

Regards,

MH

 

De: tommyhustava ***@***.***>
Responder a: DelphiWorlds/Kastri ***@***.***>
Fecha: domingo, 30 de octubre de 2022, 9:46
Para: DelphiWorlds/Kastri ***@***.***>
CC: Subscribed ***@***.***>
Asunto: Re: [DelphiWorlds/Kastri] [Kastri-free Notifications demo] (Issue #124)

 

Thank you. I have add "dw-kastri-base-2.0.0.jar" to library node. Now ican't compile project notification demo with compiler error "[PAClient Error] Error: E7688 Unable to execute '"C:\Program Files\Java\jdk-19\bin\java.exe" -jar "c:\program files (x86)\embarcadero\studio\22.0\bin\Android\embt-d8-2.2.64.jar" --release --min-api 23 --output "D:\SourceProg\Android\KastriFree-master\Demos\Notifications\Android\Release\NotificationsDemo.classes" --input-list "D:\SourceProg\Android\KastriFree-master\Demos\Notifications\Android\Release\input-list.txt"' (Error 1)". Please help me.

**Comment by tommyhustava** [comment]
Hi,
i have only tested the Notification demo project, because i need working
wrapper for TNotification in Delphi 11.0. I have targetted application to
API level 33 and on Android 12 i have received error message with
*FLAG_IMMUTABLE
/FLAG_MUTABLE*.

**Comment by DelphiWorlds** [comment]
> why are you using KastriFree?

There's no Notifications demo in Kastri. I'll rectify that, later.

> Unable to execute '"C:\Program Files\Java\jdk-19\bin\java.exe"

Not sure if this is the actual problem, but you should not be using the old JDK with Delphi 11. See [here](https://blogs.embarcadero.com/adopting-the-openjdk-for-delphi-android-development)

**Comment by DelphiWorlds** [comment]
Looking at the code in `Features\Notifications`, I've realised it needs some rework. In the meantime, you could explain why you're not using the built-in support for notifications in Delphi - as far as I know there's no major issues with it now.

**Comment by tommyhustava** [comment]
Hi, i use JDK 19 with Delphi 11

ne 30. 10. 2022 o 20:49 DelphiWorlds ***@***.***> napísal(a):

**Comment by tommyhustava** [comment]
I am the author of the application "TipLab - lucky lottery numbers"
for Slovak / Czech republic. For some time now I have been looking for
a solution replacement for the built-in system in Delphi 11 -
TNotificationCenter / TNotification notifications, because after
targeting the API level of my application to the value 33 I have a
problem and when creating a Pusp Up notification the application
crashes, or freezes, in the best case it throws an error message like
is in the picture, related to the "FLAGMUTTABLE / FLAG_IMMUTABLE"
flag. If the target API level of my app is <= 30, then it works. I
can't change the mentioned flag anywhere in the built-in system in
Delphi 11. I will be very happy if you find time to review the code
sometime in the near future.

ne 30. 10. 2022 o 21:36 DelphiWorlds ***@***.***> napísal(a):

**Comment by DelphiWorlds** [comment]
OK.. I'll look into what might be causing the problem with the built-in support

**Comment by DelphiWorlds** [comment]
This one slipped past me - I plan to take a look soon

**Comment by DelphiWorlds** [comment]
Closing, as the built-in support appears to work, this report was against a deprecated library, and doesn't even apply to Kastri, either. If you continue to have issues with Delphi's built-in support, please report it [here](https://quality.embarcadero.com/)
