### ISSUE TITLE
[Speech] StopInterval on android - if nothing said the OnStopped event does not fire

### ISSUE THREAD

**Issue by kmarbach** [DelphiWorlds/Kastri#126]
While waiting for user to speak I show a spinning wheel (TAniIndicator). In the OnStopped event I kill the ani, which works great when user says something.

If user starts the speech recognition and then says nothing, the OnStopped event does not fire, so the ani spins endlessly.

Is there a way to trap this case, like an "OnCancel" event?

**Comment by DelphiWorlds** [comment]
You could use the OnRecording event and check for `IsRecording = False`

**Comment by kmarbach** [comment]
That doesn't work for me. I hit the speedbutton that launches this code:

    DMCommon.FSpeechText := '';
    DMCommon.FSpeech.StartRecording;

and then I don't say anything. The OnRecording event never fires.

**Comment by kmarbach** [comment]
Discovered something...  I had this:
        DMCommon.FSpeech.Language := '';

I changed to this:
        DMCommon.FSpeech.Language := 'es-EN';

and now things seem to work properly with onRecording event firing as you suggested.

Where can I get a list of the possible language options? I just assumed leaving blank would use the default language for the device.

**Comment by DelphiWorlds** [comment]
> and then I don't say anything. The OnRecording event never fires.

Perhaps it does not record if it does not hear anything? I expect you should not count on the event being called in that scenario

> and now things seem to work properly with onRecording event firing as you suggested.

I didn't suggest anything about OnRecording.

> Where can I get a list of the possible language options?

I've added an [enhancement request](https://github.com/DelphiWorlds/Kastri/issues/131) for this.

**Comment by kmarbach** [comment]
I spoke too soon... setting FSpeech.Language := 'es-EN' does seem to fix the problem with onRecording firing with no user feedback, but es-EN doesn't seem to be the proper language... Now it does not understand me as well, and I am doing numbers, like 1304... the 1 does not capture. If I set Language := '', the recognition part works great. Can you tell me the language options for Mexican Spanish, American English and British English?

**Comment by kmarbach** [comment]
In this page: https://developer.android.com/guide/topics/resources/app-languages

near the end there is a section named Sample locale_config.xml file. I'm assuming those are the language codes I'm looking for, so I'm using en-US for American english and es-US for TexMex / spanish. Things seem to be working well with those values.
