### ISSUE TITLE
Media manager

### ISSUE THREAD

**Issue by kmarbach** [DelphiWorlds/Kastri#130]
My app allows user to take a photo or pull photo from image library/gallery. Photo is saved in a database and later transferred to a datasnap server. What would be great is a way to allow user to select multiple (up to a limit I would set at run-time) photos at once from the image library.

I limit # photos to 10, so if there are already 3 photos in a submission, I would call the proposed media manager with a value of 7, meaning allow user to select 0-7 photos and bring them back to the app as images.

**Comment by DelphiWorlds** [comment]
Please submit issues to the correct repo. In this case, [here](https://github.com/DelphiWorlds/Playground/issues).
