### ISSUE TITLE
Question on how the generation of the iOS-WrapperClasses work

### ISSUE THREAD

**Issue by procedurebeginend** [DelphiWorlds/Kastri#132]
Do you generate the iOS-Warpperclasses in (Kastri\API) with some kind of program or are you manually writing them based on the SDK-Page of Apple?

**Comment by DelphiWorlds** [comment]
I generate them using a tool - unfortunately it cannot be made public yet. One day..
If there's a particular framework (or frameworks) you need imported, let me know

**Comment by procedurebeginend** [comment]
I was just curious. There was a tool included with Delphi. But i think somewhere around Delphi 10.2 or so it stopped working. Right now i don´t need an additional Framework but i´ll surely come back to the offer :) 

Do you have plans on releasing the tool at some point?

**Comment by DelphiWorlds** [comment]
Yes, there are plans to release it. I'll be messaging the concerned parties :-)
