### ISSUE TITLE
When I add Kastri units, Delphi (for IOS) gives a linker error.

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/Kastri#133]
Hi
When I add Kastri units (DW.AdMob, DW.AdMobBannerAd, DW.AdMobAds), Delphi (for IOS) gives a linker error.

```
[DCC Error] E2597 ld: warning: directory not found for option '-Lexternal'
  ld: warning: directory not found for option '-LComponent'
  ld: file not found: UserMessagingPlatform

[DCC Fatal Error] F2588 Linker error code: 1 ($00000001)
```
Do these not work on IOS?

**Comment by DelphiWorlds** [comment]
The Admob support is dependent on the Firebase iOS SDK, as described in the [readme for the demo](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/AdMob#readme). Please refer to the iOS section in the readme

**Comment by kabiri** [comment]
Thans
My mistake was that I had not added the routes to the project in the frame section.
Thanks for your tips

$(Firebase)\FirebaseAnalytics\GoogleAppMeasurement.xcframework\ios-arm64_armv7;$(Firebase)\FirebaseAnalytics\GoogleAppMeasurementIdentitySupport.xcframework\ios-arm64_armv7;$(Firebase)\FirebaseAnalytics\GoogleUtilities.xcframework\ios-arm64_armv7;$(Firebase)\FirebaseAnalytics\nanopb.xcframework\ios-arm64_armv7;$(Firebase)\FirebaseAnalytics\PromisesObjC.xcframework\ios-arm64_armv7;$(Firebase)\Google-Mobile-Ads-SDK\GoogleMobileAds.xcframework\ios-arm64_armv7;$(Firebase)\Google-Mobile-Ads-SDK\UserMessagingPlatform.xcframework\ios-arm64_armv7

**Comment by kabiri** [comment]
But it still doesn't work
After the splash screen is displayed, the program closes.
I think I forgot a step but I don't know what it is?

`  <key>GADApplicationIdentifier</key>
  <string>ca-app-pub-{ --MY ID-- }</string>
  <key>SKAdNetworkItems</key>
  <array>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>cstr6suwn9.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>4fzdc2evr5.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>2fnua5tdw4.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>ydx93a7ass.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>5a6flpkh64.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>p78axxw29g.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>v72qych5uu.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>c6k4g5qg8m.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>s39g8k73mm.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>3qy4746246.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>3sh42y64q3.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>f38h382jlk.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>hs6bdukanm.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>prcb7njmu6.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>v4nxqhlyqp.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>wzmmz9fp6w.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>yclnxrl5pm.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>t38b2kh725.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>7ug5zh24hu.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>9rd848q2bz.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>n6fk4nfna4.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>kbd757ywx3.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>9t245vhmpl.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>4468km3ulz.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>2u9pt9hc89.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>8s468mfl3y.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>av6w8kgt66.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>klf5c3l5u5.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>ppxm28t8ap.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>424m5254lk.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>uw77j35x4d.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>578prtvx9j.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>4dzt52r2t5.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>e5fvkxwrpn.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>8c4e2ghe7u.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>zq492l623r.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>3qcr597p9d.skadnetwork</string>
    </dict>
  </array>`

**Comment by DelphiWorlds** [comment]
Can you use the demo to see if that works? It may be something in your project code

**Comment by kabiri** [comment]
> Can you use the demo to see if that works? It may be something in your project code

Yes
Your demo work fine.
I followed your instructions, but when I add admob, the app doesn't work.

**Comment by kabiri** [comment]
Yes your demo work
I followed your instructions, but when I add admob, the app doesn't work.

**Comment by DelphiWorlds** [comment]
Then, yes.. you've missed something in the configuration of your project, or in your code.

**Comment by kabiri** [comment]
I know, but I did all the steps. I don't know which part I didn't do right.
The configuration is correct because your program is running.
I set the framework path in my app.
I put the admob component on the form and set the value of ID.
I changed the file you said and put my ID.
Is there a step forgotten?

**Comment by DelphiWorlds** [comment]
Did you do the step as described in the readme that starts with:

For iOS: modify info.plist.TemplateiOS.xml..

**Comment by kabiri** [comment]
> Did you do the step as described in the readme that starts with:
> 
> For iOS: modify info.plist.TemplateiOS.xml..

Yes : [https://github.com/DelphiWorlds/Kastri/issues/133#issuecomment-1353121379](url)

**Comment by DelphiWorlds** [comment]
This could be it: I missed a step in the readme. Please make sure you have a value of: `-ObjC` for `Options passed to the LD linker` in Project Options

![image](https://user-images.githubusercontent.com/22670829/208263872-3223f9ca-4f40-42b0-8a0c-ccf077b2fb25.png)

**Comment by kabiri** [comment]
Thanks
Now the program runs without problems.
This was my missing step.
Although it still doesn't show ads, it might be because there are no ads in my area. I will check this tomorrow.

**Comment by DelphiWorlds** [comment]
You could use the demo as a "test harness", as it handles a number of events and shows the result, including when an ad cannot be displayed

**Comment by kabiri** [comment]
I ran the Android version and got this error.
I also changed the name of the package to something else.
In the 64-bit version, I added the dw-admob.jar library, but I got the same error again.
I created an empty application and placed the AdMobBannerAd component on the form, the application was executed in Android, but it did not display an ad, and the error routine did not give an error.
```
procedure TForm1.AdMobBannerAd1AdFailedToLoad(Sender: TObject;
   const Error: TAdError);
begin
   ShowMessage(Error.Message)
end;
```
Delphi 11.2 patch1
Android 12

![err](https://user-images.githubusercontent.com/8082245/208310432-1e895af8-e32b-4dcd-ad2e-649b5c6ffe4e.png)

**Comment by DelphiWorlds** [comment]
> I can add the dw-admob.jar file from the Playground\Lib path to Android 64!

You do not need to add libraries to Android 64-bit. Adding it to Android 32-bit will mean that will be used in both.

As for the error message you have, it seems you somehow have an older `AndroidManifest.template.xml` file. Can you try:

1. Deleting the one you have
2.Rebuild the app to allow the IDE to recreate it? 

If that does not work, check the date/time in the file `AndroidManifest.xml` (i.e. not `AndroidManifest.template.xml`) in the folder: `C:\Users\(username)\AppData\Roaming\Embarcadero\BDS\22.0` it should be dated April 28th, 2022. If not, please delete it and restart Delphi, and repeat the steps above

**Comment by kabiri** [comment]
In the case of IOS, it is enough to add these two lines or add all the lines.

<key>GADApplicationIdentifier</key>
<string>{ca-app-pub- MY APP ID }</string>

**Comment by DelphiWorlds** [comment]
Did you resolve your issue on Android?

**Comment by kabiri** [comment]
When I didn't add the file to platform 64, the ad didn't show.
I will test carefully again today.
The AndroidManifest.xml file was old and I did your work, but I myself had added the android:exported="true" option to the AndroidManifest.template.xml file.

**Comment by kabiri** [comment]
On Android, everything is fine.
It's just like the banner ad is not displayed in the right size.
The Delphi component had the same problem
https://quality.embarcadero.com/browse/RSP-37310?filter=-2

I get an ad not found error on IOS.
I don't know if it is normal or not.

Currently, I think the only problem is the incorrect display of the banner ad size.

**Comment by DelphiWorlds** [comment]
> I myself had added the android:exported="true" option to the AndroidManifest.template.xml file.

Which version of Delphi are you using? For Delphi 11.2, you should not need to manually add that attribute

**Comment by kabiri** [comment]
@DelphiWorlds 
Delphi 11.2
After deleting androidManifest.xml it was fixed.

**Comment by kabiri** [comment]
For IOS need add this line to info.plist.TemplateiOS.xml

  <key>SKAdNetworkItems</key>
  <array>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>cstr6suwn9.skadnetwork</string>
    </dict>
  </array>

**Comment by DelphiWorlds** [comment]
Sorry, the readme was not explicit enough - it was meant to indicate that you should use the ` info.plist.TemplateiOS.xml` **from the demo itself,** and modify it as necessary

**Comment by kabiri** [comment]
@DelphiWorlds 
Happy New Year
I am really grateful to you.
You are always quick to review and fix issues and add new features.
I said this just to make your tool usage guide more complete.
Anyway, you are my teacher and I have learned a lot from you.

**Comment by DelphiWorlds** [comment]
Thanks very much.. Happy New Year to you, too!
