### ISSUE TITLE
Barcode Reader IOS usage

### ISSUE THREAD

**Issue by vedat42** [DelphiWorlds/Kastri#134]
Hi, in the Barcode Reader's read me file it says to use the demo app in ios platform **MLKitBarcodeScanning.framework.zip** must be unzipped in place. I did it. But when I try to build the demo it gives an error like  : 
[DCC Error] E2597 ld: file not found: /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/vImage for architecture arm64

I also added the path into framework. But no result. I think I did something wrong. Can you explain what to do step by step please ?
Btw in android platform it works well.

**Comment by DelphiWorlds** [comment]
> I also added the path into framework.

You should not need to add the path to this framework. It would appear that your SDK did not import correctly. Please look in the folder: 
`C:\Users\(username)\Documents\Embarcadero\Studio\SDKs\iPhoneOSXX.X.sdk\System\Library\Frameworks\Accelerate.framework\Frameworks`

Where username is your logged in name on the PC, and XX.X is the iOS SDK version and check that the subfolders exist with the binaries inside them

**Comment by vedat42** [comment]
Thanks for answer. In the path that you indicate there is a directory called **vImage.framework**. Inside that directory the hierarchy is like that : 
--Headers
----Alpha.h
----BasicImageTypes.h
----Conversion.h
----Convolution.h
----Geometry.h
----Histogram.h
----Morphology.h
----Transform.h
----vImage.h
----vImage_CVUtilities.h
----vImage_Types.h
----vImage_Utilities.h

These are all it has. If there is a missing file, can you help to reinstall it properly.

**Comment by vedat42** [comment]
[DCC Error] E2597 problem was solved by reinstalling sdk for ios. There were some missing files as you mentioned about **incorrect sdk import**. Thanks for help

**Comment by DelphiWorlds** [comment]
I was going to suggest that.. thanks for the reply!
