### ISSUE TITLE
[Barcode] Reader demo won't compile in 64-bit android

### ISSUE THREAD

**Issue by kmarbach** [DelphiWorlds/Kastri#136]
Delphi 11.1, Android 64-bit
32-bit compiles and runs but 64-bit generates the following delphi errors:

[PAClient Error] Error: E7432 Unable to execute '"C:\Program Files\Java\jdk1.8.0_60\bin\java.exe" -cp "c:\program files (x86)\embarcadero\studio\22.0\bin\Android\r8-3.0.73.jar" com.android.tools.r8.D8 --intermediate --release --min-api 23 --lib "C:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository\AndroidSDK-2525-22.0.44500.8973\platforms\android-30\android.jar" @"C:\Programming\JCM\Kastri-master\Demos\BarcodeReader\Android64\Debug\classpath_list.txt" --output "C:\Programming\JCM\Kastri-master\Demos\BarcodeReader\Android64\Debug\play-services-vision-17.0.2-dexed.jar" "C:\Programming\JCM\Kastri-master\ThirdParty\Android\play-services-vision-17.0.2.jar"' (Error 1)
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\android-support-v4.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\android-support-v4.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-ads-base.17.2.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-ads-base.17.2.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-ads-identifier.16.0.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-ads-identifier.16.0.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-ads-lite.17.2.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-ads-lite.17.2.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-ads.17.2.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-ads.17.2.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-analytics-impl.16.0.8.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-analytics-impl.16.0.8.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-analytics.16.0.8.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-analytics.16.0.8.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-base.16.0.1.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-base.16.0.1.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-basement.16.2.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-basement.16.2.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-gass.17.2.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-gass.17.2.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-identity.16.0.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-identity.16.0.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-maps.16.1.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-maps.16.1.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-measurement-base.16.4.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-measurement-base.16.4.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-measurement-sdk-api.16.4.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-measurement-sdk-api.16.4.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-stats.16.0.1.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-stats.16.0.1.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-tagmanager-v4-impl.16.0.8.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-tagmanager-v4-impl.16.0.8.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-tasks.16.0.1.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-tasks.16.0.1.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-wallet.16.0.1.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-android-gms.play-services-wallet.16.0.1.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-analytics.16.4.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-analytics.16.4.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-common.16.1.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-common.16.1.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-iid-interop.16.0.1.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-iid-interop.16.0.1.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-iid.17.1.1.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-iid.17.1.1.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-measurement-connector.17.0.1.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-measurement-connector.17.0.1.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-messaging.17.5.0.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\com-google-firebase.firebase-messaging.17.5.0.jar
[PAClient Error] Error: E7432 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\google-play-billing.jar:
[PAClient Error] Error: E7432 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\google-play-billing.jar
[PAClient Error] Error: E7432 Compilation failed with an internal error.
[PAClient Error] Error: E7432 Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\google-play-billing.jar
[PAClient Error] Error: E7432 	at com.android.tools.r8.utils.w.a(SourceFile:92)
[PAClient Error] Error: E7432 	at com.android.tools.r8.D8.main(D8.java:4)
[PAClient Error] Error: E7432 Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\google-play-billing.jar
[PAClient Error] Error: E7432 	at Version.fakeStackEntry(Version_3.0.73.java:0)
[PAClient Error] Error: E7432 	at com.android.tools.r8.utils.w.a(SourceFile:68)
[PAClient Error] Error: E7432 	at com.android.tools.r8.utils.w.a(SourceFile:28)
[PAClient Error] Error: E7432 	at com.android.tools.r8.utils.w.a(SourceFile:27)
[PAClient Error] Error: E7432 	at com.android.tools.r8.BaseCommand$Builder.build(BaseCommand.java:2)
[PAClient Error] Error: E7432 	at com.android.tools.r8.D8.a(D8.java:4)
[PAClient Error] Error: E7432 	at com.android.tools.r8.utils.w.a(SourceFile:84)
[PAClient Error] Error: E7432 	... 1 more
[PAClient Error] Error: E7432 Caused by: java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\google-play-billing.jar
[PAClient Error] Error: E7432 	at com.android.tools.r8.b.a(SourceFile:75)
[PAClient Error] Error: E7432 	at com.android.tools.r8.b.a(SourceFile:1)
[PAClient Error] Error: E7432 	at com.android.tools.r8.D8Command.parse(D8Command.java:1)
[PAClient Error] Error: E7432 	... 3 more
[PAClient Error] Error: E7432 	Suppressed: java.lang.RuntimeException: com.android.tools.r8.internal.b: java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\google-play-billing.jar
[PAClient Error] Error: E7432 		at com.android.tools.r8.internal.UA.a(SourceFile:25)
[PAClient Error] Error: E7432 		at com.android.tools.r8.BaseCommand$Builder.a(BaseCommand.java:3)
[PAClient Error] Error: E7432 		at com.android.tools.r8.utils.w.a(SourceFile:24)
[PAClient Error] Error: E7432 		at com.android.tools.r8.BaseCommand$Builder.build(BaseCommand.java:2)
[PAClient Error] Error: E7432 		... 3 more
[PAClient Error] Error: E7432 	Caused by: com.android.tools.r8.internal.b: java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\google-play-billing.jar
[PAClient Error] Error: E7432 		at com.android.tools.r8.internal.UA.a(SourceFile:14)
[PAClient Error] Error: E7432 		at com.android.tools.r8.internal.UA.error(SourceFile:1)
[PAClient Error] Error: E7432 		at com.android.tools.r8.BaseCommand$Builder.error(BaseCommand.java:1)
[PAClient Error] Error: E7432 		at com.android.tools.r8.b.a(SourceFile:87)
[PAClient Error] Error: E7432 		at com.android.tools.r8.b.a(SourceFile:1)
[PAClient Error] Error: E7432 		at com.android.tools.r8.D8Command.parse(D8Command.java:1)
[PAClient Error] Error: E7432 		... 3 more
[PAClient Error] Error: E7432 	[CIRCULAR REFERENCE:java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\google-play-billing.jar]

**Comment by DelphiWorlds** [comment]
I've pushed an update to the .dproj
