### ISSUE TITLE
[Barcode] reader - my code failing

### ISSUE THREAD

**Issue by kmarbach** [DelphiWorlds/Kastri#137]
I copied your demo for the barcode reader almost exactly, to get scan capability added to my app. I have a TabControl for app navigation, so I added another TTabItem and placed the scanning capability on it.

When I run the app, this procedure TfrmMain.CameraSampleBufferReady final line:

    FReader.Scan(FSectionBitmap);

causes this error.

    Project JCMMaterial.apk raised exception class EJNI with message 'Java type JBarcodeDetector_Builder could not be found'.

I don't get that error with your demo so I wonder what I'm missing? Maybe something in project settings?

Thanks, and thanks for the quick response on the 64-bit demo question :)

**Comment by DelphiWorlds** [comment]
Did you follow the configuration steps [in the readme](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/BarcodeReader)? Specifically, the part that says you need to add:

* play-services-vision-17.0.2.jar
* play-services-vision-common-17.0.2.jar

Note: These only need to be added to Android 32-bit - the IDE knows to include them for 64-bit

> Thanks, and thanks for the quick response on the 64-bit demo question :)

Well, I'm awake, and at my computer, so.. :-)

**Comment by kmarbach** [comment]
I did not see the readme... next time I know to look for that. I'm only trying to get 64-bit version working right now, so maybe this will not help, but i will follow the readme and see if I can get 32 or 64 bit working. Thank you!

**Comment by kmarbach** [comment]
Ok... follow the instructions and it works (64-bit, have not tried 32-bit yet). Thank you! Happy Holidays!
