### ISSUE TITLE
[DCC Error] E2597 duplicate symbol in Protobuf

### ISSUE THREAD

**Issue by vedat42** [DelphiWorlds/Kastri#138]
Hello. I'm using FCM push notification in my app. So it uses some SDKs for firebase integration on iOS platform. When I try to use Barcode Reader for iOS it gives an error during compiling. The Protobuf framework that I used for FCM Push notification conflicts with the ThirdParty\iOS\libProtobuf.a file. It says it is duplicate. I tried to research about it but couldn't find a solution. Can you help me please 
 ?
**Note** : Barcode Reader demo works fine on iOS. I can create a new project and use it without problem. But when it comes to use the barcode reader feature in a project which also uses FCM Push notification it gives duplicate error.

**Comment by DelphiWorlds** [comment]
In the Building > Delphi Compiler section of the Project Options, add a Conditional Define of: `FIREBASE`:

![image](https://user-images.githubusercontent.com/22670829/209206217-f925d342-54bb-49f0-9398-6e531750e574.png)

and rebuild

**Comment by vedat42** [comment]
It worked ! thank you
