### ISSUE TITLE
TBackgroundMonitor question

### ISSUE THREAD

**Issue by alpires** [DelphiWorlds/Kastri#14]
Hi Guys. I created a new local service and configured a TBackgroundMonitor, but when the alarm is triggered I get an intent = nil in OnStartCommand.

```
LAlarm := (intent <> nil) and JStringToString(intent.getAction)
    .Equals(cDWBroadcastReceiverActionServiceAlarm);
  if LAlarm and FBackgroundMonitor.IsDozed then
  begin
    // Starts the next alarm
    FBackgroundMonitor.StartDozeAlarm;
  end;
```

So the FBackgroundMonitor.StartDozeAlarm is not executed.
In demo CrossPlatformLocation works well, but not in my new project.
Where am I going wrong?

**Comment by DelphiWorlds** [comment]
Can you show how you have configured the `TBackgroundMonitor`? Also, please use [Device Lens](https://github.com/DelphiWorlds/DeviceLens) or other logcat viewer to show the messages being sent from [DWMultiBroadcastReceiver](https://github.com/DelphiWorlds/Kastri/blob/master/Java/Base/DWMultiBroadcastReceiver.java) when the alarm triggers. There should be one that says: `Attempting to restart service or start service from alarm`

**Comment by alpires** [comment]
I used the same code from CrossPlatformLocation demo:
```
procedure Tforgram_s_datamodule.CreateObjects;
begin
  if FLocalReceiver = nil then
    FLocalReceiver := TLocalReceiver.Create(Self);
  if FBackgroundMonitor = nil then
  begin
    FBackgroundMonitor := TBackgroundMonitor.Create;
    FBackgroundMonitor.ServiceName := cServiceNameFull;
    FBackgroundMonitor.OnDozeChange := BackgroundMonitorDozeChange;
    FBackgroundMonitor.OnScreenLockChange := BackgroundMonitorScreenLockChange;
    FBackgroundMonitor.DozeAlarmInterval := cMinimumDozeAlarmIntervalSecs;
  end;
end;
```

In OnCommandStart I put this code to debug: 

```
  if intent <> nil then
    send_log('Intent: ' + JStringToString(intent.getAction))
  else
    send_log('Intent is nil');

  LAlarm := (intent <> nil) and JStringToString(intent.getAction)
    .Equals(cDWBroadcastReceiverActionServiceAlarm);
  if LAlarm and FBackgroundMonitor.IsDozed then
  begin
    // Starts the next alarm
    FBackgroundMonitor.StartDozeAlarm;
  end;
```
In my log I always get "Intent is nil", but in CrossPlatformLocation demo works well, only in my new project not.
The strange is that the BackgroundMonitorDozeChange and BackgroundMonitorScreenLockChange procedures are working.

**Comment by DelphiWorlds** [comment]
I suspect you have not added `dw-kastri-base.jar` (from [here](https://github.com/DelphiWorlds/Kastri/blob/master/Lib/dw-kastri-base.jar)) to the Libraries node of the Android platform in Project Manager, e.g: 

![image](https://user-images.githubusercontent.com/22670829/97311662-82a58e80-18b4-11eb-8f22-cfda1d5df7c2.png)

**Comment by alpires** [comment]
How, that's it, thanks, i will test now

**Comment by alpires** [comment]
Now works, thansk :-)

**Comment by DelphiWorlds** [comment]
Excellent!
