### ISSUE TITLE
Error with BiometricDemoD11

### ISSUE THREAD

**Issue by JtheK1984** [DelphiWorlds/Kastri#140]
At Compile i became an Error  on Delphi 11.2

[MSBuild Fehler] Unerwarteter Fehler bei der CreateAndroidManifestFile-Aufgabe.
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "E:\Komponenten\Kastri-master11\Demos\Biometric\Lib\BiometricDemoD11.R.jar" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path)
   bei Borland.Build.Tasks.Shared.CreateAndroidManifestFile.GetAndroidService(String JarFile)
   bei Borland.Build.Tasks.Shared.CreateAndroidManifestFile.WriteServicesStr()
   bei Borland.Build.Tasks.Shared.CreateAndroidManifestFile.genManifestFile()
   bei Borland.Build.Tasks.Shared.CreateAndroidManifestFile.Execute()
   bei Microsoft.Build.BuildEngine.TaskEngine.ExecuteInstantiatedTask(EngineProxy engineProxy, ItemBucket bucket, TaskExecutionMode howToExecuteTask, ITask task, Boolean& taskResult)

**Comment by DelphiWorlds** [comment]
I suggest using [this demo](https://github.com/DelphiWorlds/Playground/tree/main/Demos/Biometric) instead, for now

**Comment by JtheK1984** [comment]
Now I became this errror with the new project 
[Exec Fehler] Der Befehl "\Tools\manifestmerge AndroidManifest.merge.xml Android\Debug\AndroidManifest.xml" wurde mit dem Code 3 beendet.

**Comment by rj1102** [comment]
You need to update the jar libs:
activity-1.1.0.jar => remove, and add androidx-activity-1.3.1.jar
appcompat-1.2.0.jar => remove, and add androidx-appcompat-1.0.2.jar
appcompat-resources-1.2.0.jar => remove (no alternative found)
biometric-1.1.0.jar => remove, and add androidx-biometric-1.1.0.jar
BiometricDemoD11R.jar => remove (no alternative found)
fragment-1.2.5.jar => remove, and add fragment-1.3.6.jar
lifecycle-common-2.2.0.jar => remove, and add lifecycle-common-2.3.1.jar
lifecycle-livedata-core-2.2.0.jar => remove, and add lifecycle-livedata-core-2.3.1.jar
lifecycle-runtime-2.2.0.jar => remove, and add lifecycle-runtime-2.3.1.jar
lifecycle-viewmodel-savedstate-2.2.0.jar => remove, and add lifecycle-viewmodel-savedstate-2.3.1.jar
savedstate-1.0.0.jar => remove, and add androidx-savedstate-1.1.0.jar
vectordrawable-1.1.0.jar => remove (no alternative found)

**Comment by DelphiWorlds** [comment]
> [Exec Fehler] Der Befehl "\Tools\manifestmerge AndroidManifest.merge.xml Android\Debug\AndroidManifest.xml" wurde mit dem Code 3 beendet.

As per [the main readme](https://github.com/DelphiWorlds/Playground), you need to have a User Override variable of Kastri, that points to where you have the Kastri library.

**Comment by rj1102** [comment]
> > [Exec Fehler] Der Befehl "\Tools\manifestmerge AndroidManifest.merge.xml Android\Debug\AndroidManifest.xml" wurde mit dem Code 3 beendet.
> 
> As per [the main readme](https://github.com/DelphiWorlds/Playground), you need to have a User Override variable of Kastri, that points to where you have the Kastri library.

And also make sure manifestmerge.exe is not blocked by your anti-virus software.
