### ISSUE TITLE
FileSelector .cer files (Android)

### ISSUE THREAD

**Issue by jtrejodarkness** [DelphiWorlds/Kastri#141]
How can I use FileSelector to select *.cer, *.key files  on Android?

I use:

  FSelector.FileKinds := [{$IFDEF IOS}TFileKind.Item{$ENDIF IOS}{$IFDEF ANDROID}TFileKind.Content{$ENDIF ANDROID}];
  FSelector.Select(TSelectionMode.Content);

On IOS works ok, but on Android the files doesn't show, only shows images, videos, Text and PDF.

**Comment by DelphiWorlds** [comment]
What format are the .key files? I could add the relevant mime types to the code

**Comment by jtrejodarkness** [comment]
I really don't know, but are the keys to sign files with the certificate (.cer)

**Comment by DelphiWorlds** [comment]
I've pushed changes to the `DW.FilesSelector` units that may help. Sorry - you'll have to test it for me :-)

**Comment by DelphiWorlds** [comment]
Excellent, thanks!
