### ISSUE TITLE
Create Stream from file on Android

### ISSUE THREAD

**Issue by jtrejodarkness** [DelphiWorlds/Kastri#142]
A Little help please, how can I create an Stream from a file using the DW.Android.Helpers unit? 
I tried ...

                  var jis : JInputStream;
                  var uri: Jnet_Uri;

                  Result:= TMemoryStream.Create;
                  var Data: Jnet_Uri;
                  var lFile: JFile;
                  lFile := TJFile.JavaClass.init(StringToJString(SourcePath));
                  var AFile:= TAndroidFileStream.Create(TAndroidHelper.JFileToJURI(lFile));
                  Result.CopyFrom(AFile,AFile.Size);

                  ASize:= Result.Size;
                  Result.Position:= 0;

where source path is "/data/user/0/com.xpsistemas.HVPPortalMovil/files/CER_TEGJ780722QQ8.cer"

**Comment by DelphiWorlds** [comment]
You should be able to do just this:

```
  var AFile := TAndroidFileStream.Create(SourcePath);
```

..and treat `AFile` like any other `TStream` descendant. There should be no need to copy it to another stream, or use any other Android Java classes. You should also be able to do this:

```
  AFile.SaveToFile(SomeFileName);
```

Where SomeFileName is a filename in a folder that your app can write to

**Comment by jtrejodarkness** [comment]
It's correct... thank you very much!
