### ISSUE TITLE
AdMob Load and Show

### ISSUE THREAD

**Issue by Orifsoft** [DelphiWorlds/Kastri#143]
I just tested Admob demos and it's very pleasant me.
when i press  Interstitial or  Reward button after some times an Ad loads automatically. 
Is it possible  at first an Ad to be  load and after pressing show button the Ad to be shown ?
Thank very much and execuse me for my english..

**Comment by DelphiWorlds** [comment]
I am not sure I understand what you mean - is it that there is a delay between clicking the button and the ad showing? If so, this is something totally out of my control, that is: the delay is in the ad service - there is no way to load an ad first, then show it later.

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
