### ISSUE TITLE
TTS does not work on IOS 14.7.1, IPad Air 2

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/Kastri#145]
I ran your demo on IOS. But no sound is played.
I display Started, Finshed events

IOS ver 14.7.1
IPad Air 2

**Comment by DelphiWorlds** [comment]
Works here; not sure why it would not be working on yours. Make sure it is not muted, and the volume is sufficient to hear it

**Comment by kabiri** [comment]
I had checked all this and it was correct.
In TTS settings, it played the downloaded sound well.
I will check with another phone today.

**Comment by DelphiWorlds** [comment]
So it does not work on IOS ver 14.7.1, IPad Air 2?

**Comment by kabiri** [comment]
> So it does not work on IOS ver 14.7.1, IPad Air 2?

Yes, it does not work on IOS version 14.7.1, IPad Air 2

**Comment by DelphiWorlds** [comment]
Closing as I'm unable to fix Apple's OS for them
