### ISSUE TITLE
[Save Photo] Error in MediaManager Demo

### ISSUE THREAD

**Issue by FMXExpress** [DelphiWorlds/Kastri#146]
**Description**
Press Save Photo after Take Photo. Error popup message appears.

**Error messages**
Saving photo failed: The operation couldn't be completed. (PHPhotosErrorDomain error 3300.)

**Please indicate**
Delphi Version:
Delphi 11 on iOS (iPadOS?)
It's an older iPad.

**Steps To Reproduce**
Press Save Photo after Take Photo. Error popup message appears. This happened when I had "Recents" selected as the Collection. Once I made my own collection it let me Save Photo without an error.

**Comment by DelphiWorlds** [comment]
Thanks for your report - as per the readme, issues for this should be submitted to the Playground repo where this demo is located, but this time I'll manage it from here.

**Comment by DelphiWorlds** [comment]
Can you indicate the model of iPad, and the version of iOS on it?

**Comment by DelphiWorlds** [comment]
Does not fail on my iPad Pro 12.9 (iOS 16.6.1). Not sure whether I can fix this for older iPads, so closing
