### ISSUE TITLE
FCM Compile Error Delphi 11 - Firebase IOS SDK 8.7

### ISSUE THREAD

**Issue by jtrejodarkness** [DelphiWorlds/Kastri#147]
I try to use push notifications but I got the next error :

[DCC Error] E2597 duplicate symbol '_OBJC_CLASS_$_PodsDummy_nanopb' in:
      F:\Concentrado de Info\Proyectos\HoVir\Fuentes\Alexandria\HVPPortalMovil\ThirdParty\Firebase 8.7.0\FirebaseAnalytics\nanopb.xcframework\ios-arm64_armv7/nanoPB.framework/nanoPB(nanopb-dummy.o)
        F:\Concentrado de Info\Proyectos\HoVir\Fuentes\Alexandria\HVPPortalMovil\ThirdParty\Firebase 8.7.0\FirebaseAnalytics\nanopb.xcframework\ios-arm64_armv7/nanopb.framework/nanopb(nanopb-dummy.o)
  duplicate symbol '_OBJC_METACLASS_$_PodsDummy_nanopb' in:
      F:\Concentrado de Info\Proyectos\HoVir\Fuentes\Alexandria\HVPPortalMovil\ThirdParty\Firebase 8.7.0\FirebaseAnalytics\nanopb.xcframework\ios-arm64_armv7/nanoPB.framework/nanoPB(nanopb-dummy.o)
        F:\Concentrado de Info\Proyectos\HoVir\Fuentes\Alexandria\HVPPortalMovil\ThirdParty\Firebase 8.7.0\FirebaseAnalytics\nanopb.xcframework\ios-arm64_armv7/nanopb.framework/nanopb(nanopb-dummy.o)
  ld: 2 duplicate symbols for architecture arm64
[DCC Fatal Error] F2588 Linker error code: 1 ($00000001)

Can u help me?

**Comment by DelphiWorlds** [comment]
Are you including Barcode reading as well? If so, did you include a conditional define `FIREBASE`, as per the readme?:

https://github.com/DelphiWorlds/Kastri/tree/master/Demos/BarcodeReader

**Comment by jtrejodarkness** [comment]
![Captura de pantalla 2023-01-26 131021](https://user-images.githubusercontent.com/45110494/214927610-401deec9-9c1e-4e4d-9567-83dc46f80128.jpg)

I included the conditional, but I still having the error :(

**Comment by DelphiWorlds** [comment]
Try doing a Clean, then Build

**Comment by jtrejodarkness** [comment]
I tried but same result, I'm not using Barcode from Kastri I'm using ZXing dont know if its the problem.

**Comment by DelphiWorlds** [comment]
There appears to be some other library you are using that is causing the conflict. I doubt that it is ZXing since it uses all Delphi code

**Comment by jtrejodarkness** [comment]
No idea, I'll keep trying... thanks

**Comment by jtrejodarkness** [comment]
I found the Library on conflict. 

Thank u very much!
