### ISSUE TITLE
[Question] Don't receive Push Notification on IOS 

### ISSUE THREAD

**Issue by jtrejodarkness** [DelphiWorlds/Kastri#148]
I'm using Firebase library, on Android Debug compilation receiving works ok, but IOS dont receive nothing.  I 'm getting the token without problem.

Do I need to do something special with apple certificates to work on Debug compilation?

**Comment by DelphiWorlds** [comment]
On iOS if you receive the token, but not messages, usually it's a provisioning profile issue. Did you create one as per the info [in the readme](https://github.com/DelphiWorlds/Kastri/blob/master/Demos/FirebaseCloudMessaging/Readme.md)?

**Comment by jtrejodarkness** [comment]
I do all the process again, create new certificates and provisioning file, but I got the same result, Token receive but not notification. 

![image](https://user-images.githubusercontent.com/45110494/215575628-38ad1084-b8ed-4a92-9aaf-6fd6ed08207b.png)

**Comment by DelphiWorlds** [comment]
When the app is deployed, a file with the extension `.entitlements` is created in the project output folder. Please check that it contains either:

```
  <key>aps-environment</key>
  <string>development</string>
```

when deploying in development mode, or:

```
  <key>com.apple.developer.aps-environment</key>
  <string>production</string>
```

when deploying for App Store. If the `.entitlements` file does not contain this, it means you have not selected Push Notifications for the App ID on the Apple developer site, and/or have not recreated the provisioning profile after making the change

**Comment by jtrejodarkness** [comment]
Its seems to be ok

![image](https://user-images.githubusercontent.com/45110494/215608016-c4033afc-b494-4b8a-974c-a2f7c2ac2d8b.png)

**Comment by DelphiWorlds** [comment]
Next thing to check is whether you have an APNs Key on Firebase Console, e.g:
![image](https://user-images.githubusercontent.com/22670829/215608845-ad2afb9a-141d-4adc-a885-dd6226fd97b3.png)
If not, refer to [the readme](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FirebaseCloudMessaging)

**Comment by jtrejodarkness** [comment]
:`(  Already configurated...  

![image](https://user-images.githubusercontent.com/45110494/215609479-331163e8-6051-4534-98d1-8eac5c6b60a1.png)

Question: If doesn't work on development (sandbox) neither will works when upload to Apple store?

**Comment by DelphiWorlds** [comment]
> Question: If doesn't work on development (sandbox) neither will works when upload to Apple store?

Likely not. I'm not sure what the issue is here. Are you receiving Push Notifications on Android? How are you sending them?

**Comment by jtrejodarkness** [comment]
Yes, I receive push notification on Android and I'm using PushIt App. 

Isn't the APNs certificates necessary to test? Is possible to works if delete them?

**Comment by DelphiWorlds** [comment]
> Isn't the APNs certificates necessary to test?

They are not necessary if you have an APNs key assigned

**Comment by jtrejodarkness** [comment]
Delete the certificates but, sadly didn't work... the message appears to send correctly:

{"multicast_id":941618140076972962,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1675120404778643%b9f228a1b9f228a1"}]}

but the device doesn't receive anything.

Tomorrow, I'm gonna try with another IOS device.

**Comment by DelphiWorlds** [comment]
Yes, it can say `"success": 1`, but fail at the point where it reaches the APNs service. You could test your APNs key using something like this: https://pushever.app/

**Comment by jtrejodarkness** [comment]
Sorry the late... finally I could resolved, have to create new certificates.

Now, I have a question, How can I obtain the notification information when I click over the push received??

I mean, when the user clic on the notification my app opens and show some information about the notification received.

**Comment by DelphiWorlds** [comment]
> I mean, when the user clic on the notification my app opens and show some information about the notification received

When the user taps a notification and the app starts, the `OnMessageReceived` event should be called, so you can show the information when that happens

**Comment by jtrejodarkness** [comment]
How can I obtain the push notification info, like Body, Tittle and Detail? 

this is the result that obtain when user taps on notification

{"google.delivered_priority":"normal","google.sent_time":"1678983613330","google.ttl":"2419200","google.original_priority":"normal","from":"54325846069","google.message_id":"0:1678983613402389%b9f228a1b9f228a1","gcm.n.analytics_data":"Bundle[mParcelledData.dataSize=96]","collapse_key":"com.xpsistemas.HVPPortalMovil"}

**Comment by DelphiWorlds** [comment]
How are the messages being sent?

**Comment by jtrejodarkness** [comment]
Firstable, I register a group of keys to send the push notif, then send the message to this group with the code:

var
  IdHTTP : TIdHTTP;
  IdIOHandler : TIdSSLIOHandlerSocketOpenSSL;
  jsonString,response : String;
  JsonToSend : TStringStream;
  // ++ JSon
  JSonValue: TJSonValue;
  JsonArray: TJSONArray;
  ArrayElement, FoundValue: TJSonValue;
begin
  Result:= 0;

  IdHTTP := TIdHTTP.Create(nil);
  Try
    IdIOHandler := TIdSSLIOHandlerSocketOpenSSL.Create(IdHTTP);
    IdIOHandler.SSLOptions.Method := sslvSSLv23;
    IdHTTP.IOHandler := IdIOHandler;

    with IdHTTP.Request do
      begin
        ContentType := 'application/json';
        Charset := 'UTF-8';
        CustomHeaders.Values['Authorization'] := 'key='+LlaveApp;
      end;

    jsonString := Format('{"to" : "%s",' +
                         '"data" : {' +
                         '"gcm.notification.title" : "%s",' +
                         '"gcm.notification.body" : "%s",' +
                         '"gcm.notification.detalle" : "%s",' +
                         '"gcm.notification.IdNotificacion" : "%d",' +
                         '"gcm.notification.IdTipo" : "%d"' +
                         '},}',[NotificationKey,Titulo,Cuerpo,Detalle,IdNotificacion,IdTipo]);

    JsonToSend := TStringStream.Create(jsonString, TEncoding.UTF8);
    var i : Integer;
    var Enviado : Boolean:= False;

    for i := 1 to 10 do
      Try
        Sleep(500);  // ++ Esperar medio segundo a que se registre el grupo con los tokens
        hLog('Intento de Envío: '+i.ToString);
        response := IdHTTP.Post('https://fcm.googleapis.com/fcm/send', JsonToSend);
  //      hLog(response);
        dm_database.RegistrarLogPush(5,IdNotificacion,1,jsonString,response);
        if response.Contains('"success"') then
          begin
            // ++ analizar respuestas
            var TokenErrores : String;
            JSonValue:= TJSonObject.ParseJSONValue(response);
            if JSonValue is TJSonObject then
              begin
                if JSonValue.FindValue('success') <> nil then
                  TotalOk:=  JSonValue.GetValue<integer>('success');
                if JSonValue.FindValue('failure') <> nil then
                  TotalError:=  JSonValue.GetValue<integer>('failure');
                if JSonValue.FindValue('failed_registration_ids') <> nil then
                  TokenErrores:=  JSonValue.GetValue<string>('failed_registration_ids');
              end;
            Result:= TotalOk;
            if TokenErrores <> '' then hLog(Format('Tokens con Errores: %s',[TokenErrores]));
            if Result > 0 then Break;
          end;
      Except
        On E: EIdHTTPProtocolException do
          begin
            hLog(Format('Error al enviar el mensaje al grupo con llave [%s] (%s)',[NotificationKey,E.Message]));
            dm_database.RegistrarLogPush(5,IdNotificacion,1,jsonString,Format('Error al enviar el mensaje al grupo con llave [%s] (%s)',[NotificationKey,E.Message]));
          end;
      End;
  Finally
    IdHTTP.Free;
  End;

**Comment by DelphiWorlds** [comment]
The payload for the message being sent is wrong. Please refer to: https://firebase.google.com/docs/cloud-messaging/concept-options
