### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by alpires** [DelphiWorlds/Kastri#15]
Hi, there is a demo that uses DW.Notifications.pas?
How send a notification with Kastri?

**Comment by DelphiWorlds** [comment]
There is a demo in the old Kastri Free repo, here: https://github.com/DelphiWorlds/KastriFree/tree/master/Demos/Notifications. This is related to local notifications, and was used as a workaround for issues in older versions of Delphi. If you want an implementation for push notifications, please go to: https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FirebaseCloudMessaging

**Comment by DelphiWorlds** [comment]
Closed due to inactivity

**Comment by alpires** [comment]
Hi, but if I use DW.Notifications of kastri, i get the error in: 

```
function TPlatformNotificationChannel.GetSound: string;
begin
  Result := JURIToStr(FChannel.getSound);
end;
```
[DCC Error] DW.Notifications.Android.pas(186): E2003 Undeclared identifier: 'getSound'
