### ISSUE TITLE
[Biometric] [Playground] Biometric demo in playground will not deploy

### ISSUE THREAD

**Issue by rj1102** [DelphiWorlds/Kastri#151]
**Description**
Deploying Biometric demo in playground fails
I have followed all steps in ReadMe.md

**Error messages**
Both before and after executing BuildRJar.bat I will get this two errors while deploying (build is succesful):

[PAClient Error] Error: E2312 Unable to execute '"C:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository\AndroidSDK-2525-22.0.46141.0937\build-tools\32.0.0\Aapt.exe" package -f -M "C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Android\Release\BiometricDemoD11\AndroidManifest.xml" -F "C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Android\Release\BiometricDemoD11\bin\BiometricDemoD11-unaligned.apk" -I "C:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository\AndroidSDK-2525-22.0.46141.0937\platforms\android-32\android.jar" -S "C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Android\Release\BiometricDemoD11\res" -A "C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Android\Release\BiometricDemoD11\assets" "C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Android\Release\BiometricDemoD11\library" "C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Android\Release\BiometricDemoD11\classes"' (Error 1)

[PAClient Error] Error: E2312 C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Android\Release\BiometricDemoD11\AndroidManifest.xml:21: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.AppCompat').

**Please indicate**
Delphi 11.2 (Professional with Mobile) on Windows 11
Android SDK 25.2.5 - NDK r21
Testing on OPPO mobile with Android 12

**Steps To Reproduce**
Follow the steps in ReadMe.md. Errors occur while executing step 4 (but it expected to give errors however ReadMe.md does not mention which errrors), and while executing step 6 (still same two errors while it is expected to succeed).

**Extra** 
Below is the content of my BuildRJarSetVars.bat after step 1 in ReadMe.md. There were many paths to chose on my PC but I tried to find the most recent one.

@echo off

:: ****** Modify this file to suit your project and environment
set KastriPath=C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master
set PlatformConfig=Android
set BuildConfig=Release
::: if %IsRelease% == 1 ( set BuildConfig=Debug ) else ( set BuildConfig=Release)

:: Project related paths
:: SPN = SanitizedProjectName
set SPN=BiometricDemoD11
set ProjectPath=%~dp0..
set ProjectBinPath=%ProjectPath%\%PlatformConfig%\%BuildConfig%\%SPN%
set MergedResPath=%ProjectPath%\Resources\Merged\res
set BuildPath=%ProjectPath%\Build

set ResMergeExe=%KastriPath%\Tools\resmerge.exe
set TrimRJavaExe=%KastriPath%\Tools\trimrjava.exe
:: Root path to target package and its dependencies
set PackagePath=%~dp0..\..\..\ThirdParty\Android\androidx-biometric-1.1.0

:: Tools/library paths
set PlatformPath=C:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository\AndroidSDK-2525-22.0.46141.0937\platforms\android-32
set JDKPath=C:\Program Files\Java\jdk1.8.0_191\bin
set AAPT2Exe=C:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository\AndroidSDK-2525-22.0.46141.0937\build-tools\32.0.0\aapt2.exe
set AAPTExe=C:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository\AndroidSDK-2525-22.0.46141.0937\build-tools\32.0.0\aapt.exe

**Comment by DelphiWorlds** [comment]
Please show all messages and errors (if any) emitted when you run `BuildRJar.bat` because it appears part of it is failing

**Comment by rj1102** [comment]
Sorry for that.
You were right there was a typo in the JDKPath. The command line window was closing too fast to notice.
I have corrected it in: set JDKPath=C:\Program Files\Java\jdk1.8.0_60\bin
I have made a fresh copy of the playground  and tried again
But Is still get the same errors after executing BuildRJar.bat.
The output of the command line window of BuildRJar.bat:

C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Scripts>BuildRJar.bat
Copying resource files...
Merging resource files...
Generating R.java file for appcompat-1.2.0
Compacting R.java file for appcompat-1.2.0
Generating R.java file for appcompat-resources-1.2.0
Compacting R.java file for appcompat-resources-1.2.0
Generating R.java file for biometric-1.1.0
Compacting R.java file for biometric-1.1.0
Generating R.java file for core-1.5.0-rc02
Compacting R.java file for core-1.5.0-rc02
Compiling classes from R.java files..
Compiling C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Scripts\..\Lib\BiometricDemoD11.R.jar..

C:\Users\Robbert-Jan\Data\Projecten\DelphiLibsAlexandria\Kastri-master\Playground-main\Demos\Biometric\Scripts>

**Comment by DelphiWorlds** [comment]
Can you check the files being deployed in Deployment Manager, that the files in the folder: Resources\Merged\res are all being deployed? There's quite a number of them, e.g:

![image](https://user-images.githubusercontent.com/22670829/215588462-3f6efa39-3e39-494c-82f4-65fad7765a89.png)

**Comment by rj1102** [comment]
I'm sure what you mean. 
My deployment list (Rroject -> Deployment) looks like below.
I don't see any folder Resources\Merged\res. How do I get there?

![Schermafbeelding 2023-01-31 173319](https://user-images.githubusercontent.com/8749590/215822943-abb6182e-2f55-460f-9f24-9201c0c6ced9.png)

**Comment by rj1102** [comment]
I have some progress. I've tried **debug** mode and that succeeded! And the success and fail handlers are called only once!
But how do I get it deployable using a **release** build configuration? In BuildRJarSetVars I have "set BuildConfig=Release" from the beginning, but I don't get any Resources\Merged\res files.

**Comment by DelphiWorlds** [comment]
> how do I get it deployable using a release build configuration?

Oops! I missed adding the deployment files for Android 32-bit for Release. I've now pushed that change

Incidentally, the whole batch file and deployment thing is planned to be automated in [Codex](https://github.com/DelphiWorlds/Codex), v1.6

**Comment by rj1102** [comment]
Thanks. I was now able to deploy it in Release build configuration.
