### ISSUE TITLE
Estou com problemas ao abrir a camera  do Barcode reader no IOS. Erro: 'ObjectiveC class MLKvisionImage could not be found'

### ISSUE THREAD

**Issue by alisson07** [DelphiWorlds/Kastri#152]
Estou com problemas ao abrir a camera  do [Barcode] reader no IOS. Erro: 'ObjectiveC class MLKvisionImage could not be found'

**Description**
Estou tentando utilizar o Barcode Reader no IOS 16.2 mas estou tendo problemas.

**Error messages**
objective c with message 'objective c class mlkvisionimage could not be found'

Delphi Version:11.2
Platform(s) that the issue occurs on (i.e. iOS, Android etc): IOS
If mobile, device model and OS version (e.g. Pixel 3a, Android 11): IOS 16.2

**Steps To Reproduce**
Concise steps to reproduce the behaviour:

**Comment by DelphiWorlds** [comment]
Does this error occur when using the demo or your own project? I've updated [the readme](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/BarcodeReader#readme) about including information about using the `-ObjC` option in Project Options.

In future, please use English when filing an issue. You can use [Google Translate](https://translate.google.com) to translate your question.

No futuro, use o inglês ao registrar um problema. Você pode usar o [Google Translate](https://translate.google.com) para traduzir sua pergunta.

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
