### ISSUE TITLE
Can't to play audio stream on Android

### ISSUE THREAD

**Issue by wesov** [DelphiWorlds/Kastri#153]
Hi, I try the audioplayer demo, but it can't to play audio stream on Android.

**Comment by DelphiWorlds** [comment]
What do you mean by "can't to play"? Is there an error? Does the caption for the "Play" button switch to "Pause"

What model device do you have, and what version of Android is on it?

**Comment by DelphiWorlds** [comment]
If you're playing from a URL, please provide a URL that does not work, that I can test from

**Comment by DelphiWorlds** [comment]
You should use the SaveToFile method of the TMemoryStream and load it from the file

**Comment by wesov** [comment]
Thanks a lot. 
I want to play mp3's MemoryStream directly, and add a LoadFromStream methon. 
    procedure setDataSource(dataSource: JMediaDataSource); cdecl; overload;
    procedure setDataSource(context: JContext; uri: Jnet_Uri; headers: JMap); cdecl; overload;
    procedure setDataSource(path: JString; headers: JMap); cdecl; overload;
    procedure setDataSource(path: JString); cdecl; overload;
    procedure setDataSource(afd: JAssetFileDescriptor); cdecl; overload;
    procedure setDataSource(fd: JFileDescriptor); cdecl; overload;
    procedure setDataSource(fd: JFileDescriptor; offset: Int64; length: Int64); cdecl; overload;
Which procedure is more appropriate, and how to convert TMemoryStream to Android's JFileDescriptor, it can't work with TBytes.

**Comment by DelphiWorlds** [comment]
I looked into adding LoadFromStream, and had the same problem as you, i.e. how to use `TMemoryStream` and `FileDescriptor` together, and I am yet to find a solution. There is an alternative: to create a descendant of [`MediaDataSource`](https://developer.android.com/reference/android/media/MediaDataSource), however it requires Java code to implement it. I'll keep looking for a way to produce a `FileDescriptor`

**Comment by DelphiWorlds** [comment]
ChatGPT to the rescue! This is the equivalent Java code:

```
import android.os.ParcelFileDescriptor;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;

public class ByteArrayToFileDescriptor {
  public static ParcelFileDescriptor getFileDescriptorFromByteArray(byte[] byteArray) {
    ParcelFileDescriptor pfd = null;
    PipedOutputStream pos = null;
    PipedInputStream pis = null;
    try {
      pos = new PipedOutputStream();
      pis = new PipedInputStream(pos);
      pos.write(byteArray);
      pfd = ParcelFileDescriptor.fromData(pis.read(), 0, byteArray.length);
    } catch (FileNotFoundException e) {
      e.printStackTrace();
    } catch (IOException e) {
      e.printStackTrace();
    } finally {
      try {
        if (pos != null) {
          pos.close();
        }
        if (pis != null) {
          pis.close();
        }
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
    return pfd;
  }
}
```

I'll work on doing a Delphi equivalent

**Comment by DelphiWorlds** [comment]
OK.. I tried the FileDescriptor method, but that was a failure. In contrast, creating a descendant of `MediaDataSource` was rather trivial, but as I mentioned earlier, it required Java code. 

I am attaching changes to this comment that adds a `LoadFromStream` method to `TAudioPlayer`, and implements it for Android only, so you can test it. You will also need to add the updated `dw-kastri-base-2.0.0.jar` (also attached) to the Android libraries (just 32-bit) in Project Manager.
[AudioPlayerChanges.zip](https://github.com/DelphiWorlds/Kastri/files/10637189/AudioPlayerChanges.zip)

**Comment by wesov** [comment]
Thank you very much for your warm help. @DelphiWorlds
