### ISSUE TITLE
Firebase notification on iOS

### ISSUE THREAD

**Issue by crishead** [DelphiWorlds/Kastri#155]
Hello,

I tried the Firebase Notification on iOS. I followed the demo app readme instructions, and the demo app works perfectly, I got the token, and I got the messages. 
But when I created a new project with same code and options, I never got the token.

Its my mistake, but I didn't found the missing step(s). My process the following:
I create a new app (in this case I create the same app with the demo, just token memo and message memo, and copy the code.
In IDE options, I set the Delphi Compiler->Framework search path to (copied from demo, and $(`Firebase_8_7`) is valid): 
$`(Firebase_8_7`)\FirebaseAnalytics;$(Firebase_8_7)\FirebaseAnalytics\FirebaseAnalytics.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseAnalytics\FirebaseCore.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseAnalytics\FirebaseCoreDiagnostics.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseAnalytics\FirebaseInstallations.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseAnalytics\GoogleAppMeasurement.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseAnalytics\GoogleDataTransport.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseAnalytics\GoogleUtilities.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseAnalytics\nanopb.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseAnalytics\PromisesObjC.xcframework\ios-arm64_armv7;
$(`Firebase_8_7`)\FirebaseMessaging\FirebaseMessaging.xcframework\ios-arm64_armv7

I set the Search path to Api, Core, Include, Features\Firebase, Features\Notifications
In Version Info, I set the BundleIdentifier to used and working identifier (same the demo), and the UIBackgrundModes to fetch, remote-notifications

For the provisoring profile, I used the same profile.

I added the GoogleService-info.plist to Deployment, in to root folder.

The app was successfully built and running, but the token did not load ... 

Have you any idea, whitch steps missing?

**Comment by DelphiWorlds** [comment]
There is something else to check, however missing this step would normally cause the app to crash: Ensure that the `Options passed to the LD linker` option is set to: `-ObjC`
![image](https://user-images.githubusercontent.com/22670829/219150485-79ed5f14-3c50-46df-a72e-6b56159fc7c4.png)

**Comment by DelphiWorlds** [comment]
If everything compiles and runs, not receiving a token is usually related to a mismatch between the CFBundleIdentifier value and what is configured for your project in Firebase Console.

**Comment by crishead** [comment]
Thank you!
The problem was the missing -ObjC. 
Now it's work.
