### ISSUE TITLE
(Camera) get Bitmap

### ISSUE THREAD

**Issue by p3rf1** [DelphiWorlds/Kastri#157]
In the camera demo D11 how can i get the bitmap in Timage?
Apparently it should be in the procedure CameraFrameAvailableHandler?

Please tell me how to call this procedure and what should be registered in it? Thank you

**Comment by DelphiWorlds** [comment]
The demo code actually tells you what you need to do:

https://github.com/DelphiWorlds/Kastri/blob/a390d1ff19cf6255e759c179630094a797043f21/Demos/Camera/Views/CD.View.Camera.pas#L142

i.e. the project needs a conditional define of `USEGL`. In Project Options, select Building > Delphi Compiler and put `USEGL` in the Conditional Defines property

**Comment by p3rf1** [comment]
Thank you very much for the quick response. Did as you said.
Then I wrote in the procedure:

```
Form3.Image1.bitmap.Assign(AFrame);
Form3.show;
```
but TImage is empty. What am I doing wrong? How to call this procedure?

I'm sorry, I'm just a newbie and I really need to do this. Thank you very much for your help

**Comment by p3rf1** [comment]
I add in this procedure:
`Showmessage('');`
But it didn't work

**Comment by DelphiWorlds** [comment]
If that code is not being called, it is most likely you have not included the conditional define correctly. Please see my other comment: https://github.com/DelphiWorlds/Kastri/issues/157#issuecomment-1448760511

**Comment by p3rf1** [comment]
Can you see screenshot https://prnt.sc/fbtoTf-DWJ78 ?

**Comment by p3rf1** [comment]
I managed! After compiling and Build project/
Thank you so much!
