### ISSUE TITLE
The latest update to manifestmerge.exe seems to get caught in a loop

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#158]
Since updating to your latest sources, when the manifest merge.exe runs in my project PostBuildEvent, it seems to get stuck in a loop and never ends when building my app.

My path is: manifestmerge.exe AndroidManifest.merge.xml .\$(Platform)\$(Config)\AndroidManifest.xml

The AndroidManifest.merge.xml is as follows:
<manifest>
    <application>
        <service merge:update="android:name=&quot;com.google.firebase.components.ComponentDiscoveryService&quot;">
            <meta-data android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>
    </application>
</manifest>

If you'd like a copy of my AndroidManifest.xml to test this, please message me and I'll be happy to send it over.

Thanks

**Comment by DelphiWorlds** [comment]
Please update the merge.xml file so that the manifest tag has namespacing, thus:

```
<manifest xmlns:merge="http://www.delphiworlds.com/xmlns/merge" xmlns:android="http://schemas.android.com/apk/res/android">
```

**Comment by Gebhard-AddIn** [comment]
I found the same issue. 
You can test it with the FirebaseCloudMessaging - Demo.
I am using now the older version of manifestmerge.exe. now it works for me.
