### ISSUE TITLE
CrossPlatformLocation Android 12

### ISSUE THREAD

**Issue by alissonrodrigo** [DelphiWorlds/Kastri#159]
The Cross Platform Location demo service does not work when the app is closed, it only works with it open or in the background

**Comment by alissonrodrigo** [comment]
actually the service does not start after killing the application in android 10 . with xiaomi phones

**Comment by DelphiWorlds** [comment]
Just on Xaiomi phones?

**Comment by alissonrodrigo** [comment]
> Just on Xaiomi phones?

Yes

**Comment by alissonrodrigo** [comment]
> Just on Xaiomi phones?

also on Samsung on7.  and of course on xiaomi

**Comment by alissonrodrigo** [comment]
In this last commit did you find the error? If yes, how to fix it here in the project? Grateful

**Comment by DelphiWorlds** [comment]
It works OK on my Android 13 phone - I don't know why it would not work on Android 10. I think I have one that has Android 10, that I can test on later...

**Comment by alissonrodrigo** [comment]
Did you add android:exported="True" in the manifest? in the android documentation it asks to add for the new android (>12). I added from your demo both in app and service

**Comment by alissonrodrigo** [comment]
Is this code actually yours? I'm using your example. I remove the project and it runs without problems, when I add the service to the project I get this error. But the project is yours. without adding anything. Changing only the package name

**Comment by DelphiWorlds** [comment]
> Is this code actually yours?

Yes, this code is mine.

> I'm using your example. I remove the project and it runs without problems, when I add the service to the project I get this error

What do you mean by "add the service"? The service is already added to the project. For Android, please load the CPLAndroidGroupD11.groupproj group project. You should not be loading the CrossPlatformLocation.dproj project by itself.

**Comment by alissonrodrigo** [comment]
Yes, you got me wrong. I say that for the error not to rise I have to remove the service from the project. Adding the service again the error appears.

**Comment by alissonrodrigo** [comment]
> Can you try this? 
> 
> 
> 
> 1. Uninstall the app from your device
> 
> 2. Rebuild the app
> 
> 3. Deploy the app to your device
> 
> 4. Run the app - when it prompts for permission, then shows the message about "location updates in the background", ensure that you select "Always" before tapping the back arrow
> 
> 
> 
> Let me know whether it still has the same problem
> 
> 

Yes, I already did those steps, but it didn't solve the problem.

**Comment by DelphiWorlds** [comment]
Can you attach your `.apk` file to this report, please?

**Comment by alissonrodrigo** [comment]
> Can you attach your `.apk` file to this report, please?

Yes! I will send the access data too! username and password

**Comment by alissonrodrigo** [comment]
send email to davidn@radsoft.com.au.

**Comment by DelphiWorlds** [comment]
I thought you meant the demo does not work for you. The .apk you sent is of your app, which has code in it that is very likely causing the issue, not the demo. I'm unable to resolve the issue unless I see all your code, but that is beyond the scope of support in Kastri. If you need help with finding the issue, please email me and I may be able to work out a quote

**Comment by alissonrodrigo** [comment]
I'm studying delphi and compiling only the demo gives me the same error (when closing the application)
I noticed some curiosities. in D11 and package dw-fusedlocation-jar instead of dw-fusedlocation-2.0.0-jar as stated in the documentation for the D11 jar.
in the Lib folder there is no dw-fusedlocation-2.0.0-jar. Could this be causing the problem?

**Comment by DelphiWorlds** [comment]
> I noticed some curiosities. in D11 and package dw-fusedlocation-jar instead of dw-fusedlocation-2.0.0-jar as stated in the documentation for the D11 jar.

The [documentation](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/CrossPlatformLocation#fused-location-api) mentions no such thing. It specifically states: `dw-fusedlocation-jar`. This jar is for any version of Delphi, possibly from at least 10.4

**Comment by DelphiWorlds** [comment]
> I'm studying delphi and compiling only the demo gives me the same error (when closing the application)

Unfortunately I do not have a Xiaomi device to test on. Can you give the exact details of the error?

**Comment by alissonrodrigo** [comment]
No device lens returns me the following messages.
I indicated with the arrow where the error appears as soon as I close the application and enter the service.
The error presents seconds after closing the application. The android tells me that the application does not respond and asks to close... If I remove the service from the project, the error no longer exists.
![erro](https://github.com/DelphiWorlds/Kastri/assets/8572209/6c32734f-3226-4a2e-834b-d66b4a62a1b4)
[erro.log](https://github.com/DelphiWorlds/Kastri/files/11451778/erro.log)

**Comment by alissonrodrigo** [comment]
the device lens log txt file

**Comment by alissonrodrigo** [comment]
Android error report


java.lang.RuntimeException: Unable to start receiver com.delphiworlds.kastri.DWMultiBroadcastReceiver: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.cruxsistemas.zapcargas/com.embarcadero.services.CrossPlatformLocationService
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4469)
	at android.app.ActivityThread.access$1700(ActivityThread.java:271)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2145)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.cruxsistemas.zapcargas/com.embarcadero.services.CrossPlatformLocationService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelable(Parcel.java:3334)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2421)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6218)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1858)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1834)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:791)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:791)
	at com.delphiworlds.kastri.DWMultiBroadcastReceiver.checkStartupIntent(DWMultiBroadcastReceiver.java:225)
	at com.delphiworlds.kastri.DWMultiBroadcastReceiver.onReceive(DWMultiBroadcastReceiver.java:344)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4456)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:735)
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:656)
	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:12281)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2632)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2559)

**Comment by alissonrodrigo** [comment]
It seems that as of android 12 (used in testing by me) they cannot start services in the foreground while running in the background.

https://stackoverflow.com/questions/69604951/getting-android-app-foregroundservicestartnotallowedexception-in-android-12-sdk/69604952#69604952

**Comment by DelphiWorlds** [comment]
I have an Android 13 device and it works for me. Can you check to make sure the `Foreground service` permission is checked?
![image](https://github.com/DelphiWorlds/Kastri/assets/22670829/32b04eab-d382-4d36-9bbb-72a161593d7c)

**Comment by alissonrodrigo** [comment]
As I said I'm using your demo. and it is not marked this option for service
![Screenshot_1](https://github.com/DelphiWorlds/Kastri/assets/8572209/5578bb68-08b0-48fb-a7fd-8346fa824f55)

**Comment by DelphiWorlds** [comment]
The permission is for the *Application* part, not the service. Please look at my screenshot again

**Comment by alissonrodrigo** [comment]
Sorry and true! Yes, then it's checked. And it still doesn't work.
Another doubt in the documentation says to add "play-services-location.16.0.0.jar" (ThirdParty\Android) but in the demo it is not there, should I add?

**Comment by DelphiWorlds** [comment]
It says to add the jar when building your own project. It is already added to the demo.

**Comment by alissonrodrigo** [comment]
just the default play-services-location-18.0.0.dex.jar

**Comment by DelphiWorlds** [comment]
You are correct - the Delphi 11 project does not need it, since the default is `play-services-location-18.0.0.dex.jar`.

**Comment by alissonrodrigo** [comment]
right, to be able to find the source of the error me! the service is started by message when the application is closed, correct? The app works correct only when I close it after a few seconds about an error message! I have no memory leak. From the messages I left here, what do you believe it could be? remembering that the same message appears in the default kastri demo

**Comment by DelphiWorlds** [comment]
> Looking at the manifest I saw that the following line
>  it's like false. Is correct? 

What line is false?

**Comment by DelphiWorlds** [comment]
Not sure if that affects the application... it does not in my case.

**Comment by alissonrodrigo** [comment]
And very strange I've been trying to solve this for 5 days without success! Incredible when I close the application the error message appears and 15 seconds later the service starts to run

**Comment by DelphiWorlds** [comment]
Is it working?

**Comment by DelphiWorlds** [comment]
Closing due to lack of response

**Comment by alissonrodrigo** [comment]
Sorry for the delay I was out. Unfortunately the error remains. Testing on moto e22 phones does not load.
