### ISSUE TITLE
[Push] Huawei

### ISSUE THREAD

**Issue by sfoms** [DelphiWorlds/Kastri#160]
Good afternoon.
Is it possible to use Huawei Push Kit to receive notifications?
Or tell me which way to look?
I will be very grateful! Thank you!

**Comment by DelphiWorlds** [comment]
Please refer to: https://www.wikigain.com/install-google-play-store-on-huawei/
I do not have a Huawei phone so I do not know whether this works

**Comment by sfoms** [comment]
Thank you!  But this solution is for a special case.  I would still like to use the system capabilities ...

**Comment by DelphiWorlds** [comment]
Sorry, I misread your original question. I don't have a Huawei device so I would be unable to test it if I did implement their Push Kit for Delphi. I expect it would be easier to install Google Play Services on the device and use the existing implementation, as per my other reply\
