### ISSUE TITLE
[swiperefreshlayout]  example

### ISSUE THREAD

**Issue by whacharachai** [DelphiWorlds/Kastri#163]
Could you guide me to include androidx.swiperefreshlayout with example please.

**Comment by DelphiWorlds** [comment]
It might help to indicate exactly what you want to do with it, and provide a link to an example done in Java or Kotlin.

**Comment by whacharachai** [comment]
Thank you very much for your reply sir.

I'm working with delphi 10.4 (have a plan to move to 11) for Android App
developing. My current app is simple as calling some api on my server
receiving data and show them on a stringgrid. I make a "refresh button" for
users. But they seem to familia with "Pull screen down to refresh" as the
basic feature for mostly app.

I have been doing research for the pull down refresh and found Embarcadero
PulltoRefresh function, but it only work on Listview and do not look very
well.

And then I found your excellent coding for delphi to cover many feature on
Android. I wonder if you can show some example of doing such thing with
efficient way.

Thank you very much.

Sincerely,

Whacharachai Prawatlertudom.
Thailand.

**Comment by DelphiWorlds** [comment]
Since SwipeRefreshLayout is a "native" control you would be limited in what controls you can place on top of it. I have had a look at what it does, and I think it would be possible to implement something like this without having to use SwipeRefreshLayout itself. I will look into it

I note that you are from Thailand - I was in Koh Samui only a couple of weeks ago :-)

**Comment by whacharachai** [comment]
Thank you very much in advance sir.

I 'm very happy to hear that you have been to Koh Samui. Please visit us
more in the future and be happy in other beautiful part of Thailand.

Sincerely,
W. Prawatlerdudom.

**Comment by DelphiWorlds** [comment]
I've published a demo in the HowTo repository, [here](https://github.com/DelphiWorlds/HowTo/tree/main/Demos/SwipeRefresh)

**Comment by whacharachai** [comment]
Awesome, thanks!

**Comment by whacharachai** [comment]
Sir, I can't find DW.SwipeRefreshLayout

**Comment by DelphiWorlds** [comment]
Sorry.. I have now added the missing files to the same folder as the project

**Comment by whacharachai** [comment]
Thank you!
