### ISSUE TITLE
[Share Items] share multiple images at once

### ISSUE THREAD

**Issue by maTEChard** [DelphiWorlds/Kastri#165]
If your issue is for a particular feature (e.g. Camera, Connectivity, Biometric etc), please prefix the issue title with the feature in square brackets, e.g. "[Camera] Crash when image is captured"

**Description**
Share multiple images at once. Unfortunately, that doesn't work.

**Error messages**
no error. message: Share completed. Under debugging: DW.ShareItems.Android.pas not found, but under Project - Delphi Compiler -Serach path I have insert ..\Kastri-master\Features\ShareItems

**Please indicate**
Delphi Version: Delphi 11.3 Patch 1
Platform(s) that the issue occurs on (i.e. iOS, Android etc): Android 10
If mobile, device model and OS version (e.g. Pixel 3a, Android 11): 

**Steps To Reproduce**
procedure TForm1.Share;
var
  LSharedFileName: string;
begin
  //LSharedFileName := TPath.Combine('Files', 'Lorem.txt');
  // FShareItems.AddText('Share Test');
  // Uncomment the following line and comment out the next one, to test sharing of a file
//   FShareItems.AddFile(TPath.Combine(TPath.GetDocumentsPath, LSharedFileName));
  FShareItems.AddImage(Image1.Bitmap); // On Android, don't attempt to share an image as well as text
  FShareItems.AddImage(Image2.Bitmap); // I have insert a new TImage
  FShareItems.Share(Button1, FExcluded);
end;

**Comment by DelphiWorlds** [comment]
Looks like it's an exception for later versions of Android. I think the original code was probably tested around Android 8 or 9!
I've pushed a fix for it (in [DW.ShareItems.Android.pas](https://github.com/DelphiWorlds/Kastri/blob/master/Features/ShareItems/DW.ShareItems.Android.pas), so please try out the changes.

**Comment by maTEChard** [comment]
Great job. Works perfect. thx
