### ISSUE TITLE
[SMS] Add functionality for SMS Retriever API

### ISSUE THREAD

**Issue by MahindiBoiro** [DelphiWorlds/Kastri#170]
It would be nice to have this functionality: https://developers.google.com/identity/sms-retriever/overview

**Comment by DelphiWorlds** [comment]
Looks like it might be a pretty extensive task

**Comment by MahindiBoiro** [comment]
any way I can help?

**Comment by DelphiWorlds** [comment]
If you're asking for this functionality, I doubt it :-) It'll just take time

**Comment by DelphiWorlds** [comment]
I have a test project for you to try:

[SMSRetrieverTest.zip](https://github.com/DelphiWorlds/Kastri/files/12414089/SMSRetrieverTest.zip)

Note that when sending an SMS to be intercepted by your app, you need to send a message that includes a hash of your application ID, for example:

```
Your verification code is: 123456

Qi8V1qJZopF
```

The last part is the application ID hash. I have created an application that helps create this hash:

[AppHashGen.zip](https://github.com/DelphiWorlds/Kastri/files/12414267/AppHashGen.zip)

This utility will work only if you have Delphi 11.x installed, and you have installed the Adoptium JDK (the default for Delphi 11.x). If you're just debugging, click the `Use Debug` button to populate the keystore file, alias and password fields. Enter the package name in the Package Name edit (the package name value for the demo is: com.embarcadero.SMSRDemo) and click the `Generate` button - this will generate the application id hash and copy it to the clipboard.

In the SMS Retriever demo, click the button to start the app listening for SMS messages. Once the message is received you should see the details in the memo

**Comment by DelphiWorlds** [comment]
Closing due to no response. I'll re-open the issue if anyone wants this, however for now it is shelved.
