### ISSUE TITLE
Android Service not working

### ISSUE THREAD

**Issue by diegoverdan** [DelphiWorlds/Kastri#175]
None of the demos that use Android Service (CrossPlatformLocation, ForegroundService) are working anymore. When starting the app it freezes. Until recently these features were functional. Has anyone had this problem before and managed to resolve it?

**Please indicate**
Delphi Version: 11.3
Platform(s): Android 8, Android 11, Android 12

**Comment by diegoverdan** [comment]
That! It simply crashes and freezes the app. If disabling the call to the service works, then there is something in the service (I tested it using the CrossPlatformLocation demo) that does not go up and does not respond to the app that is using it. Is there a way to capture more information to pass here?

**Comment by DelphiWorlds** [comment]
> If disabling the call to the service works, then there is something in the service..

Yes, if you make it so the service is not started, and it does not crash, presumably there's an issue with the service. Can you attach the `.apk` file that is generated to this issue, or make it available somewhere for download?

Also, please indicate what device(s) you have

**Comment by diegoverdan** [comment]
Here is the apk link:
https://we.tl/t-duFgmPjPA1

Devices used in the tests:
Samsung Galaxy A22 (SM-A225M/DSN)
Motorola MotoOne (XT2013-1)
Azuz Zenfone (ZE552KL)

**Comment by DelphiWorlds** [comment]
Thanks for the APK - you appear to be suffering from this issue:

https://docs.code-kungfu.com/books/hotfix-113-alexandria/page/fix-jar-libraries-added-to-android-64-bit-platform-target-are-not-compiled

**Comment by hraztan** [comment]
I have the same issue with the CrossPlatformLocation demo. I've followed the steps above. The app starts and crashes. FYI, the app initially starts fine and asks for permissions. Immideiately after that it crashes.
Here is the apk: 
[https://i.diawi.com/bVWe3k](url)

HUAWEI P Smart 2019 (POT-LX1)
Android 10

**Comment by hraztan** [comment]
I performed all the steps above. The app still crashes on startup.
You can download the new apk here: [https://i.diawi.com/uoYkoZ](url)

BTW, the readme file mentions a modified "AndroidManifest.template.xml" file in the demo's application folder. It seems to be missing.

**Comment by diegoverdan** [comment]
Unfortunately even doing the steps described in the link above did not resolve. I deleted the .java files, the IIDE created them again but I was unsuccessful. I uninstalled the APK from the device, and installed it again after compiling it with the new .java files created by the IDE. In the images you can see that after starting the app for the first time (after compilation) permission is requested. When permission is granted, the app no longer responds (https://we.tl/t-UDkoYfkWoy). If you close and open it again (as you already have permission) it already starts with the message that the app does not respond (https://we.tl/t-gLi2P2c0gc).

**Comment by DelphiWorlds** [comment]
> Unfortunately even doing the steps described in the link above did not resolve.

Can you post your `.apk` file here (rename the extension as `.zip`) or somewhere it can be downloaded from?

**Comment by diegoverdan** [comment]
Hello. Via the link below, follow the clone images from the git repository + running the project directly on the device with android 11. The font update did not solve. I checked the AndroidManifest and the merge was successful. Also follows the APK compressed by 7Zip (password: 102030).

Files:
https://we.tl/t-YKjSAO6nce

**Comment by DelphiWorlds** [comment]
The password you gave does not appear to be working for me.

**Comment by hraztan** [comment]
> I see that here, too. Not sure why yours does. Are you compiling with the latest versions of the files from Kastri?
> Yes!!

A stupid question :-) : Does the app need a cellular data connection or wifi is enough?

**Comment by DelphiWorlds** [comment]
> Does the app need a cellular data connection or wifi is enough?

Wifi should be enough, though it should still function without it

**Comment by DelphiWorlds** [comment]
> Is there anything else I can do?

I've just noticed there may have been changes between late April and now that might be causing the problem. I just need to work out what

**Comment by hraztan** [comment]
Nice. Tx!!

BTW, in the readme file, you have included "play-services-location.16.0.0.jar" which you don't seem to be including in the latest demo files. Probably because "play-services-location.18.0.0.dex.jar" is already included.

**Comment by diegoverdan** [comment]
> The password you gave does not appear to be working for me.

https://we.tl/t-BX9hkcEuFH

**Comment by DelphiWorlds** [comment]
Now pushed a fix (in `DW.Toast.Android`). [This discussion](https://github.com/DelphiWorlds/Kastri/discussions/176) sent me in the right direction as to what the problem was - ultimately the service was using FMX units, which is a big [no-no for services in Delphi](https://quality.embarcadero.com/browse/RSP-17857).

**Comment by diegoverdan** [comment]
Wow, it worked! Thank you so much for your effort and help!!!

**Comment by hraztan** [comment]
I don't know what to say. Things get fixed in no time here. Working perfectly (just tested the Android version). Tx.

Great work!!

**Comment by DelphiWorlds** [comment]
Actually, I should have recognized what the problem was sooner, but thanks!
