### ISSUE TITLE
AndroidStartAtBoot   change name and message

### ISSUE THREAD

**Issue by MarianoAsa** [DelphiWorlds/Kastri#177]
How can I change the message and the name of the program when the notification "Please tap this notification for the ..." appears at boot

**Comment by DelphiWorlds** [comment]
I will need to change the code in order for this message to be customized

**Comment by MarianoAsa** [comment]
This is inside de-kastri-base-2.0.0.jar, how can I change it?

**Comment by DelphiWorlds** [comment]
It's Java code, and is contained in this file:

https://github.com/DelphiWorlds/Kastri/blob/9dbfbd5778df1cbe5e39637e9792fe44fe1413d9/Java/Base/DWMultiBroadcastReceiver.java#L133

You'd need to change that, and rebuild the .jar file. I can change it sometime today to make it more flexible

**Comment by MarianoAsa** [comment]
any tips on how to do this I don't understand much about java only delphi

**Comment by DelphiWorlds** [comment]
If you don't understand much about Java, it would be better if you waited for my changes, which will be later today (Australian time)

**Comment by MarianoAsa** [comment]
Ok I'll be waiting. thanks.

**Comment by DelphiWorlds** [comment]
I want to make sure that the code is flexible enough to be supported in different languages, so it is taking a while. I plan to have it ready sometime tomorrow, Australian time

**Comment by DelphiWorlds** [comment]
I have now pushed changes that allow customization of the title and body of the startup notification. Please read the [updates to the readme](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/AndroidStartAtBoot#startup-notification-resource), as it has important information about how to achieve the customization.

**Comment by MarianoAsa** [comment]
Okay, it worked fine. Thanks a lot, cool.
