### ISSUE TITLE
Adaptive AdMob banners aren't resizing the adBanner control after the ad has loaded

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#178]
The control itself needs to be resized on AdLoaded or the control will crop the banner.
A temporary fix was proposed while this was in the playground but may have been missed off when transferred into Kastri.

Current workaround is to make these changes:

```Delphi
procedure TiOSAdMobBannerAd.AdLoaded;
begin
  AdControl.Height := GetAdSize.size.height;
  AdControl.DoAdLoaded;
end;

procedure TAndroidAdMobBannerAd.AdLoaded;
begin
  AdControl.Height := GetAdSize.getHeight;
  AdControl.DoAdLoaded;
end;
```

Thanks

**Comment by DelphiWorlds** [comment]
I don't see those changes in Playground, but I'll take your word for it that they're needed :-)

**Comment by MyBuzzTechnologies** [comment]
Thanks David.
For ref, the original issue raised was here:
https://github.com/DelphiWorlds/Playground/issues/11

Maybe the change didn't make it into Playground then - I was using a local copy with the fix in until recently :)

**Comment by DelphiWorlds** [comment]
Ooops! Thanks!
