### ISSUE TITLE
Android App crashes when receive push notification 

### ISSUE THREAD

**Issue by jtrejodarkness** [DelphiWorlds/Kastri#179]
My Android app crashes when receive a push notification while is active in the background, on IOS it works ok.

Delphi 11.3
Android
Samsung S23 Ultra

**Comment by DelphiWorlds** [comment]
Needs more detail: 

* Is it your own project, based on one of the demos, or is it one of the demos?
* Are there any error messages when it crashes?
* Have you used a logcat viewer to check for error messages in the log when it crashes?

**Comment by jtrejodarkness** [comment]
Own project based on the demos.
No, I dont get any error.
No, I haven't use a logcat

**Comment by DelphiWorlds** [comment]
> Own project based on the demos.

Which one? Does the demo work that you based your project on?

**Comment by jtrejodarkness** [comment]
I based my project on the next demo:

Kastri-master\Demos\EMBTFCM

I receive notifications without problems when the apps is closed or when its inactive, also on IOS works no matter the state of the app.
Only on Android the app close when receive the notification while the app is on the screen.

**Comment by DelphiWorlds** [comment]
Just tried the demo again here, and it does not crash for me when the app is active, but is in the background. Have you tried running the app via the debugger in Delphi, and see what the IDE does when the push notification is received?

**Comment by jtrejodarkness** [comment]
Yes, but only close the app. No exception error show me. I also put breakpoints but still closes. I'm gonna try with the demo again.

**Comment by DelphiWorlds** [comment]
Is this still an issue?

**Comment by jtrejodarkness** [comment]
Yes, haven't found where the problem is, I needed to put it on stand by to work on another project. 
You can close the issue.

thanks
