### ISSUE TITLE
CrossPlatformLocation stopped working on delphi 11.3

### ISSUE THREAD

**Issue by pagadores** [DelphiWorlds/Kastri#180]
The demo CrossPlatformLocation works well when compiled with Delphi 11 but when compiled with Delphi 11.3 CE it gets hang up on Android. Revert the library to system default but still it doesnt work

**Comment by DelphiWorlds** [comment]
Can you attach the .apk (rename it as .zip) here, or put it somewhere it can be downloaded from, please?

**Comment by pagadores** [comment]
> Can you attach the .apk (rename it as .zip) here, or put it somewhere it can be downloaded from, please?
Hi, Of course! thank for the support:

https://dobitcloudcom-my.sharepoint.com/:u:/g/personal/aldo_victoria_dobitcloud_com/Ec-YZKueYo1BlC7-UoOwDW0BHHW3CSpXwAF0uDnRp1BkpA?e=1llrB6

**Comment by DelphiWorlds** [comment]
I'm unable to install the `.apk` you provided because the activity is missing the `android:exported` attribute. Please delete the `AndroidManifest.template.xml` in the demo folder, and do a Clean and Build. If the app does not run properly on your device, please provide a link to the updated `.apk`

**Comment by pagadores** [comment]
> `android:exported`

Hi,

Deleted the AndroidManifest.template.xml. Did a clean all / build all, now im getting this error only with the Demo CrossPlatformLocation project:

[Exec Error] The command "..\..\..\Tools\manifestmerge AndroidManifest.merge.xml Android\Debug\AndroidManifest.xml
" exited with code 1.

Attach actual project (this is a copy of Kastrimaster downloaded a couple of days ago from Github):

https://dobitcloudcom-my.sharepoint.com/:u:/g/personal/aldo_victoria_dobitcloud_com/EYgV0-75KaRAi-qQBbk8dt8BzH_jNAaOmdEVeF-WrO5uaA?e=TrpxDN

**Comment by DelphiWorlds** [comment]
There's no point in attaching the project, because it comes from the repository, which I can access too. Note that the project will not compile just on its own - as the error suggests, it cannot find the files it needs

**Comment by pagadores** [comment]
Hi,

Sorry my mistake, when deleting the  Androidmanifiest also deleted the manifiest mergefile. Did a restore of the file and compiled again the APK. The new version is on it: 

https://dobitcloudcom-my.sharepoint.com/:u:/g/personal/aldo_victoria_dobitcloud_com/EeXRi4AWsMRItvgGo-KE8WkBYexg4cOD4OKM1q3aOkd1UA?e=MQiKyk

From what i have been available to debug, the app is establishing connection with the service. The service ask for the location and background permission well. After the permission is granted then the service hangups. Tried to debug but havent been able because the service detachs from the source code debugging.

I think might be a problem with the new android version on 11.3 and the jars that the project needs, but is just a guess since i havent being able to debug further

**Comment by DelphiWorlds** [comment]
> I think might be a problem with the new android version on 11.3 and the jars that the project needs

I'm looking into it, however note that this has already been tested with Delphi 11.3. The issue may be specific to your device, or something else that you may have missed.

**Comment by DelphiWorlds** [comment]
> Did a restore of the file and compiled again the APK. The new version is on it

Once again, I am unable to install the `.apk`, due to the missing `android:exported` attribute in the `activity` in the manifest. It appears you may have restored the incorrect `AndroidManifest.template.xml` file from earlier

**Comment by pagadores** [comment]
Im using AndroidSDK-2525-22.0.48361.3236 that ships with Delphi 11.3 CE. Could you please confirm me in with Android SDK 11.3 you have tested and is working. I could do a downgrade maybe of the Android version that im using.

Thanks

**Comment by pagadores** [comment]
> > Did a restore of the file and compiled again the APK. The new version is on it
> 
> Once again, I am unable to install the `.apk`, due to the missing `android:exported` attribute in the `activity` in the manifest. It appears you may have restored the incorrect `AndroidManifest.template.xml` file from earlier

could you please send me a copy of the android manifiest that is working for you? the compiled app is working at your site with D11.3?

**Comment by DelphiWorlds** [comment]
I should not need to send it - if you delete the one you have (that is errant), the IDE should replace it with the correct one when you do Clean, Build. If that does not solve it, you may have the issue where upgrading Delphi has not replaced all the required files. In the folder: `C:\Users\username\AppData\Roaming\Embarcadero\BDS\22.0` (where `username` is your logged in user name), the `AndroidManifest.xml` file (note: no `template` in this filename) should have a date of November 2022. Similarly, the files ending in `.java` should have a date of Jan 2023. If they do not, delete the `AndroidManifest.xml` and `.java` files and restart Delphi - it will recreate these files on startup. After that, again delete `AndroidManifest.template.xml` from your project folder, and do Clean and Build.

**Comment by pagadores** [comment]
Hi, Noticed that i had a enviroment problem with Dephi 11.3, uninstall all component and did a fresh install with new paths. Java files and AndroidManifiest.xml have the dates as you mention. Checked that also the new androidmanifiest.xml have the intent listener declared and exported is true, but still the application hangs

**Comment by DelphiWorlds** [comment]
Please provide an .apk

**Comment by pagadores** [comment]
Hi Nate,

https://dobitcloudcom-my.sharepoint.com/:u:/g/personal/aldo_victoria_dobitcloud_com/ETrFnW60ImNOgGlWHeZZ_poB0UuKNiI27gpTb1okvIU-DQ?e=rorF6j

Thanks

**Comment by DelphiWorlds** [comment]
> Hi Nate,

Who is Nate? I'm Dave :-)

You need to delete the `.java` files (i.e. `CrossPlatformLocationService.template.java` and `CrossPlatformLocationServiceProxyInterface.template.java`) from the `Service` folder of the demo, then Clean and Build.

**Comment by pagadores** [comment]
Hi Dave,

Sorry for wrong name! That was the problem now the app is working again like a champ.

Great as always for supporting Delphi community! you are a legend

**Comment by pagadores** [comment]
Just need to delete all template files from the project
