### ISSUE TITLE
[Connectivity] [Android] - it is not identifying internet in 4G 

### ISSUE THREAD

**Issue by marlonnardi** [DelphiWorlds/Kastri#181]
**Description**
It is not firing when the 4g connection drops and comes back, this problem does not occur on IOS.

Delphi 11.3 Version 28.0.47991.2819 
moto g(7) play - Android 10
Galaxy A30s [SM-A307GT] - Android 11

**Steps To Reproduce**
Test Demo:  ..\Kastri\Demos\Connectivity\ConnectivityDemoD11.dproj

**Comment by DelphiWorlds** [comment]
I've pushed a change in `DW.Connectivity.Android` that should fix the problem - the delay to check for a connection (in `TNetworkCallbackDelegate.CheckConnectivityChange`) has been changed from 250ms to 500ms. In future, I may add a property for `TConnectivity` so you can adjust this delay in your own code

**Comment by marlonnardi** [comment]
Perfect, now it's working, thanks
