### ISSUE TITLE
ShareItems Demo - Pls clarify sending image and text at the same time

### ISSUE THREAD

**Issue by Rollo62b** [DelphiWorlds/Kastri#184]
Hi Dave,

I'm trying with the DW.ShareItems demo from the current version, and have the following questions:

1.) In the demo, there is a notice:
On Android, don't attempt to share an image as well as text

I'm a little unsure about that meaning, because in my tests (at Android 13 only so far), this works perfectly well under all conditions,
I can share 1 image, 1 text file, 2 images, 1 image / 1 text file, 2 images / 1 text file, seems all to work.

Maybe this warning related to Android comes from an older release and is deprecated meanwhile ?

2.) Moreover, why did you add RequestPermissions( [ cPermissionReadExternalStorage, cPermissionWriteExternalStorage ] ?
     The sharing should work from a local folder, without special permissions, or am I wrong?

Sorry for these silly questions, but maybe those precautionary measures were already obsolete.

**Comment by DelphiWorlds** [comment]
Updated the demo and readme
