### ISSUE TITLE
ShareItems - sharing files

### ISSUE THREAD

**Issue by db0321** [DelphiWorlds/Kastri#187]
need NSPreviewRepresentingActivityItem and NSPreviewRepresentableActivityItem for sharing files on MacOS Venture 13.3 with NSSharingServicePicker

**Comment by DelphiWorlds** [comment]
For my reference, and for anyone else interested in how this may be approached:
https://developer.apple.com/documentation/sharedwithyou/adding_shared_content_collaboration_to_your_app?language=objc

**Comment by DelphiWorlds** [comment]
Having said that, can you indicate the reasons for wanting support for this? This is just to clarify the requirement

**Comment by db0321** [comment]
I am trying to send files via share sheet on Mac with OS Ventura 13.3. The ShareItems demo seems to work with texts and images, but not with files. An empty share sheet appears when I try to share file. I think the problem is in unit DW.ShareItems.Mac in procedure Share in line LActivityItems.addObject(TNSFileWrapper.Alloc.initWithURL(LURL, 0)); 
I think thar LURL needs other type of conatiner to appear in share sheet.

**Comment by db0321** [comment]
Thnak you ... also, it would be great to be be able to use share sheet in Microsoft Windows as well.

**Comment by DelphiWorlds** [comment]
Regarding Windows, please [see this](https://github.com/DelphiWorlds/HowTo/blob/main/ChatGPTConversations/WindowsShareSheet.md). If you know of a close equivalent, please let me know

**Comment by db0321** [comment]
It seems to me that Windows.ApplicationModel.DataTransfer could do the similar thing on MS Windows, i.e. access share sheet panel. It initiates the user interface for sharing content with another app programmatically.

Where IDataTransferManagerInterop is alternative for desktop applications 

https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/display-ui-objects#for-classes-that-implement-idatatransfermanagerinterop

and static class DataTransferManager is for UWP apps
https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datatransfermanager?view=winrt-22621

**Comment by DelphiWorlds** [comment]
I think the problem on macOS may be that TNSFileWrapper is not needed, i.e. the line instead of

```
  LActivityItems.addObject(TNSFileWrapper.Alloc.initWithURL(LURL, 0))
```

should be:

```
  LActivityItems.addObject(LURL);
```

I'll test later this evening, but you might also like to try

**Comment by db0321** [comment]
I have just found out that this works for me:
LActivityItems.addObject(TNSitemProvider.Alloc.initWithContentsOfURL(LURL));

**Comment by DelphiWorlds** [comment]
Thanks.. I'll incorporate the change

**Comment by db0321** [comment]
If possible, I would also suggest to replace line

FPicker.showRelativeToRect(MakeNSRect(0,,0,0,0), LView, CGRectMinYEdge); // <----- Might need to adjust the values in MakeNSRect

with this code

mR.TopLeft:=aControl.LocalToAbsolute(pointf(0,0));
mR.BottomRight:=aControl.LocalToAbsolute(pointf(aControl.Width, aControl.Height));
FPicker.showRelativeToRect(MakeNSRect(mR.Left, LView.Bounds.size.height-mR.Bottom, mR.Width, mR.Height), LView, CGRectMinYEdge); 

where mR is TRectF

**Comment by DelphiWorlds** [comment]
Closing as the requirements have been met, other than the request for Windows support, which is now in [this issue](https://github.com/DelphiWorlds/Kastri/issues/190).
