### ISSUE TITLE
Compiler errors under Delphi 12

### ISSUE THREAD

**Issue by westner** [DelphiWorlds/Kastri#191]
Hello,

I downloaded the current version and tried to compile under Delphi 12 but I get a lot of warnings and errors:

Android32:
[DCC Hint] DW.Android.Helpers.pas(484): H2164 Variable 'LAttribute' is declared but never used in 'TAndroidHelperEx.HasClass'
[DCC Error] DW.Location.Android.pas(30): E2291 Missing implementation of interface method JLocationListener.onFlushComplete
[DCC Fatal Error] DW.Location.Android.pas(136): F2063 Could not compile used unit 'DW.Geodetic.pas'

Android64:
[DCC Hint] DW.Android.Helpers.pas(484): H2164 Variable 'LAttribute' is declared but never used in 'TAndroidHelperEx.HasClass'
[DCC Error] DW.Location.Android.pas(30): E2291 Missing implementation of interface method JLocationListener.onFlushComplete
[DCC Fatal Error] DW.Location.Android.pas(136): F2063 Could not compile used unit 'DW.Geodetic.pas'

iOS64
[DCC Warning] DW.OSTimer.pas(171): W1000 Symbol 'DisposeOf' is deprecated: 'Use Free instead'
[DCC Hint] DW.FilesSelector.iOS.pas(61): H2219 Private symbol 'GetImageRotation' declared but never used

MacOS64
[dccosx64 Warning] DW.OSTimer.pas(171): W1000 Symbol 'DisposeOf' is deprecated: 'Use Free instead'
[dccosx64 Hint] DW.ShareItems.Mac.pas(132): H2164 Variable 'LSize' is declared but never used in 'BitmapToNSImage'

Win32
[dcc32 Warning] DW.OSTimer.pas(171): W1000 Symbol 'DisposeOf' is deprecated: 'Use Free instead'
[dcc32 Error] DW.UIHelper.pas(73): E2029 Identifier expected but 'CLASS' found
[dcc32 Error] DW.UIHelper.pas(73): E2029 Declaration expected but identifier 'TUIHelper' found
[dcc32 Error] DW.UIHelper.pas(78): E2003 Undeclared identifier: 'Result'
[dcc32 Error] DW.UIHelper.pas(80): E2029 '.' expected but ';' found
[dcc32 Error] DW.UIHelper.pas(82): E2037 Declaration of 'CopyImageToClipboard' differs from previous declaration
[dcc32 Error] DW.UIHelper.pas(34): E2065 Unsatisfied forward or external declaration: 'TUIHelper.CopyImageToClipboard'
[dcc32 Error] DW.UIHelper.pas(40): E2065 Unsatisfied forward or external declaration: 'TUIHelper.GetOffsetRect'
[dcc32 Fatal Error] DW.Precompile.pas(332): F2063 Could not compile used unit 'DW.UIHelper.pas'

Win64
[dcc64 Warning] DW.OSTimer.pas(171): W1000 Symbol 'DisposeOf' is deprecated: 'Use Free instead'
[dcc64 Error] DW.UIHelper.pas(73): E2029 Identifier expected but 'CLASS' found
[dcc64 Error] DW.UIHelper.pas(73): E2029 Declaration expected but identifier 'TUIHelper' found
[dcc64 Error] DW.UIHelper.pas(78): E2003 Undeclared identifier: 'Result'
[dcc64 Error] DW.UIHelper.pas(80): E2029 '.' expected but ';' found
[dcc64 Error] DW.UIHelper.pas(82): E2037 Declaration of 'CopyImageToClipboard' differs from previous declaration
[dcc64 Error] DW.UIHelper.pas(34): E2065 Unsatisfied forward or external declaration: 'TUIHelper.CopyImageToClipboard'
[dcc64 Error] DW.UIHelper.pas(40): E2065 Unsatisfied forward or external declaration: 'TUIHelper.GetOffsetRect'
[dcc64 Fatal Error] DW.Precompile.pas(332): F2063 Could not compile used unit 'DW.UIHelper.pas'

**Comment by westner** [comment]
For Win32/64 the ; is missing due to wring defines:

uses
  FMX.Platform,
{$IF Defined(ANDROID)}
  DW.UIHelper.Android;
{$ELSEIF Defined(IOS)}
  DW.UIHelper.iOS;
{$ELSEIF Defined(MACOS)}
  DW.UIHelper.Mac;
{$ENDIF}

**Comment by DelphiWorlds** [comment]
Thanks for this report!

Can you update from the repo and try again? Incidentally, the `KastriBuild.dproj` in the root of the Packages folder can now be used to build.

**Comment by DelphiWorlds** [comment]
Sorry, I need to resolve the JLocationListener error first.. working on it

**Comment by westner** [comment]
Under Mac OS 64 still the Hint:
[dccosx64 Hint] DW.ShareItems.Mac.pas(132): H2164 Variable 'LSize' is declared but never used in 'BitmapToNSImage'

iOS, Win32/Win64 compiles now.

Under Android - you noticed for yourself - the JLocationListener-error is still there.

**Comment by DelphiWorlds** [comment]
Pushed further changes
