### ISSUE TITLE
Compiler errors under Delphi 12 Admob

### ISSUE THREAD

**Issue by metinayhan** [DelphiWorlds/Kastri#193]
Hello,

I downloaded the current version and tried to compile under Delphi 12 but I get a lot of warnings and errors:

    {$IF CompilerVersion >= 35}
    function setAdInfo(adInfo: JAdInfo): JAdManagerAdRequest_Builder; cdecl; // Not documented at https://developers.google.com/android/reference/com/google/android/gms/ads/admanager/AdManagerAdRequest.Builder
    {$ENDIF}

[DCC Error] DW.Androidapi.JNI.AdMob.pas(215): E2003 Undeclared identifier: 'JAdInfo'
[DCC Fatal Error] DW.AdMobBannerAd.Android.pas(67): F2063 Could not compile used unit 'DW.Androidapi.JNI.AdMob.pas'

**Comment by DelphiWorlds** [comment]
I've removed the method now. It's not needed by Kastri yet, and has apparently [changed in a later version of AdMob](https://developers.google.com/admob/android/migration) anyway.
