### ISSUE TITLE
Barcode Reader

### ISSUE THREAD

**Issue by sametkayaoglu** [DelphiWorlds/Kastri#194]
Hello,
I am getting the following error in the barcode reader.

Delphi 12
Android 12

![barcode](https://github.com/DelphiWorlds/Kastri/assets/21238095/b80ff47b-8222-4bb3-a4ed-bf4125d915a3)

**Comment by DelphiWorlds** [comment]
I've added [instructions here](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/BarcodeReader#manifest) as to how to resolve this issue.
