### ISSUE TITLE
Connectivity Demo not working on Android 13 device (Samsung Note20)

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#195]
The Connectivity demo in Kastri on my Android (Samsung Note20 5G Android 13) doesn't seem to be working correctly.
When I run it with Airplane mode active on the phone, the app says I'm connected to the internet.
When I change the internet state (e.g. turn off airplane mode) it doesn't trigger the change handler.

Looking at the Android code, it looks from the Android docs that you may be using deprecated APIs but not sure if that's the problem or not. https://developer.android.com/reference/android/net/NetworkInfo

No errors reported, just incorrect behaviour.

**Comment by DelphiWorlds** [comment]
It may be that it needs a delay similar to when onAvailable is called, because there can be a lag between when the method is called, and when the connection really is available. Android has to be one of the most problematic OS's between devices. At least iOS is 99.9% consistent!

**Comment by MyBuzzTechnologies** [comment]
Thanks Dave, I added the delays in and it made no difference, but it helped to rule that out.
I did figure out what was happening.

On my device I have an antivirus app installed which added a VPN to my internet connection (to check the traffic as it passes through, I assume).

The call to ConnectivityManager.getAllNetworks was returning the VPN as the first network.
The NET_CAPABILITY_INTERNET of this was true and although the network the VPN was connected to wasn't connected (airplane mode is on), the IsConnected property of the VPN was returning true which was confusing everything.

GetAllNetworks seemed to list the proper wifi/mobile connection separately, so I just ignored the VPN case and it now works properly.

I'm sure there's a better way, but the following change worked when made in GetCOnnectedNetworkInfoFromNetwork:

  if (LCapabilities <> nil) and
      LCapabilities.hasCapability(TJNetworkCapabilities.JavaClass.NET_CAPABILITY_INTERNET) and
      LCapabilities.hasCapability(TJNetworkCapabilities.JavaClass.NET_CAPABILITY_NOT_VPN) then

**Comment by DelphiWorlds** [comment]
After a bit of searching, I think you may have found the best way! This [SO answer (about if VPN is active)](https://stackoverflow.com/a/35274808/3164070) has a potentially additional check:

```
  caps.hasTransport(NetworkCapabilities.TRANSPORT_VPN))
```

However I think it may be redundant, since:

```
  LCapabilities.hasCapability(TJNetworkCapabilities.JavaClass.NET_CAPABILITY_NOT_VPN)
```

 returns `True` for non-VPN connections as well as inactive ones. I'll test out the changes on my device(s) and report my findings

**Comment by DelphiWorlds** [comment]
I had SmartVPN on my device, and was able to replicate the issue. Now pushed a fix, thanks!!
