### ISSUE TITLE
Latest AdMob components (with UMP) shows a runtime error on iOS 15.5

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#196]
The latest AdMob demo crashes when run on an iOS 15.5 device. It runs ok on iOS 17.

```
dyld[1366]: Library not loaded: /usr/lib/swift/libswift_StringProcessing.dylib Process AdTest (1366)
  Referenced from: /private/var/containers/Bundle/Application/C4FDA082-3F77-45A0-840F-69BC70F7B9D1/AdTest.app/AdTest Process AdTest (1366)
  Reason: tried: '/usr/lib/swift/libswift_StringProcessing.dylib' (no such file), '/usr/local/lib/libswift_StringProcessing.dylib' (no such file), '/usr/lib/libswift_StringProcessing.dylib' (no such file) Process AdTest (1366)
First chance exception at $0000000107A32EDC. Exception class 6. Process AdTest (1366)
```

Previous versions of Kastri before the UMP addition work perfectly on the same iOS 15.5 device so suspect the UMP framework may be using the _StringProcessing.dylib reported above, which may not have been installed by default on iOS 15.5.

**Comment by MyBuzzTechnologies** [comment]
Commenting out the fake loader in line 28 of DW.iOSapi.SwiftCompat.pas seems to work!

**Comment by DelphiWorlds** [comment]
As per private discussion, commenting out the libswift_StringProcessingLoader might cause problems with other features, such as FCM, so that needs to be tested.
