### ISSUE TITLE
SpeechRecognition

### ISSUE THREAD

**Issue by firemen01** [DelphiWorlds/Kastri#199]
how to choose which microphone to read the voice from when there are several microphones in the system?

**Comment by DelphiWorlds** [comment]
To do so in the speech recognition support in Kastri would require enhancements to the code. It would probably be wise to have this code separate from `TSpeechRecognizer`. I'll take a look at how - it might be possible with existing FMX code.

**Comment by DelphiWorlds** [comment]
On further investigation, it appears that Android and iOS do not allow you to select the default microphone programmatically.  Only the user can do this via the settings app on the respective OS.
