### ISSUE TITLE
[Firebase Messaging] DW.Firebase.Messaging.iOS.pas(34): E2003 Undeclared identifier: 'FIRMessagingRemoteMessage'

### ISSUE THREAD

**Issue by crishead** [DelphiWorlds/Kastri#201]
Hello, 
In Delphi 12 with the latest Katri library, the compilation failed with the following errors:

[DCC Error] DW.Firebase.Messaging.iOS.pas(34): E2003 Undeclared identifier: 'FIRMessagingRemoteMessage'
[DCC Error] DW.Firebase.Messaging.iOS.pas(37): E2005 'FIRMessagingRemoteMessage' is not a type identifier
[DCC Error] DW.Firebase.Messaging.iOS.pas(39): E2005 'FIRMessagingRemoteMessage' is not a type identifier
[DCC Error] DW.Firebase.Messaging.iOS.pas(31): E2291 Missing implementation of interface method FIRMessagingDelegate.messaging

Looking at the code, DW.iOSapi.FirebaseMessaging contains this on line 67:
```
  {$IF Defined(FIREBASE_PRE_V10)}
  FIRMessagingRemoteMessageClass = interface(NSObjectClass)
    ['{EF45D074-C7A5-4DB2-BCD1-53B8650419F4}']
  end;

  FIRMessagingRemoteMessage = interface(NSObject)
    ['{6E2F8E14-FD8D-4B5D-8026-A607BE0B8F9C}']
    function appData: NSDictionary; cdecl;
  end;
  TFIRMessagingRemoteMessage = class(TOCGenericImport<FIRMessagingRemoteMessageClass, FIRMessagingRemoteMessage>) end;

  FIRMessagingDelegate = interface(IObjectiveC)
    ['{264C1F0E-3EA9-42AC-9802-EF1BC9A7E321}']
    procedure applicationReceivedRemoteMessage(remoteMessage: FIRMessagingRemoteMessage); cdecl; // Deprecated?
    [MethodName('messaging:didReceiveMessage:')]
    procedure didReceiveMessage(messaging: FIRMessaging; remoteMessage: FIRMessagingRemoteMessage); cdecl;
    [MethodName('messaging:didRefreshRegistrationToken:')]
    procedure didRefreshRegistrationToken(messaging: FIRMessaging; fcmToken: NSString); cdecl;
    [MethodName('messaging:didReceiveRegistrationToken:')]
    procedure didReceiveRegistrationToken(messaging: FIRMessaging; fcmToken: NSString); cdecl;
  end;
  {$ELSE}

  FIRMessagingDelegate = interface(IObjectiveC)
    ['{D2E4D0A8-B2CD-4C69-B6C8-01619DC5E09B}']
    procedure messaging(messaging: FIRMessaging; didReceiveRegistrationToken: NSString); cdecl;
  end;
  {$ENDIF}
```

Which in our case is not compiled because of the condition (FIREBASE_PRE_V10) is not defined. 

However, the DW.Firebase.Messaging.iOS unit does not contain this condition:
```
  TFIRMessagingDelegate = class(TOCLocal, FIRMessagingDelegate)
  private
    FFirebaseMessaging: TPlatformFirebaseMessaging;
    procedure ReceivedMessage(remoteMessage: FIRMessagingRemoteMessage);
  public
    constructor Create(const AFirebaseMessaging: TPlatformFirebaseMessaging);
    procedure applicationReceivedRemoteMessage(remoteMessage: FIRMessagingRemoteMessage); cdecl;
    [MethodName('messaging:didReceiveMessage:')]
    procedure didReceiveMessage(messaging: FIRMessaging; remoteMessage: FIRMessagingRemoteMessage); cdecl;
    [MethodName('messaging:didReceiveRegistrationToken:')]
    procedure didReceiveRegistrationToken(messaging: FIRMessaging; fcmToken: NSString); cdecl;
    [MethodName('messaging:didRefreshRegistrationToken:')]
    procedure didRefreshRegistrationToken(messaging: FIRMessaging; fcmToken: NSString); cdecl;
  end;
```
This causes FIRMessagingRemoteMessage not to be found and the build fails.

Delphi Version: Athens 12. target: iOS.

**Comment by DelphiWorlds** [comment]
Unfortunately when I did some re-arranging of code to support the newer implementation in [FCMRebooted](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FCMRebooted), I managed to break the old code. I highly recommend migrating to use `DW.FCMManager` from FCMRebooted, however I will look into a fix if you want to stay with the old code

**Comment by DelphiWorlds** [comment]
I've pushed a change to the FCMDemoD11 project to add the required define (`FIREBASE_PRE_V10`), and fixes to `DW.Firebase.Messaging.iOS.pas`, so it should compile with these changes.

As mentioned above, I strongly recommend migrating to the implementation used by the `FCMRebooted` demo, as Google have deprecated the older Firebase SDKs and there is no guarantee that they will continue to work.

**Comment by crishead** [comment]
Thank you for the very quick fix! 
Indeed, in the meantime I have reviewed the FCMRebooted demo and will update the code based on it.
Thanks again!
