### ISSUE TITLE
Notification feature doesn't work correctly on Android 14 due to denied-by-default SCHEDULE_EXACT_ALARM permission

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#203]
In the Notification feature, setExactAndAllowWhileIdle() is used when scheduling the notification.
This requires special permission checking from Android 12+ and is denied by default on Android 14. At the moment, using this feature crashes the app on Android 14.

Details are here:

https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

Could this feature be upgraded to trigger permission requests on Android 12+ and protected with AlarmManager.canScheduleExactAlarms() as described in the above article?
We use this Kastri feature as it's a better implementation than the Embarcadero one.

**Comment by DelphiWorlds** [comment]
This is currently the proposed change:

```delphi
class function TAndroidHelperEx.InternalSetAlarm(const AAction: string; const AAlarm: TDateTime; const AFromLock: Boolean;
  const ARequestCode: Integer = 0; const AServiceName: string = ''): JPendingIntent;
var
  LStartAt: Int64;
  LPendingIntent: JPendingIntent;
begin
  Result := GetAlarmPendingIntent(AAction, AFromLock, ARequestCode, AServiceName);
  LStartAt := GetTimeFromNowInMillis(SecondsBetween(Now, AAlarm));
  // Allow for alarms while in "doze" mode
  if TOSVersion.Check(6) then
  begin
    if TOSVersion.Check(14) and not AlarmManager.canScheduleExactAlarms then
    begin
      LPendingIntent := Result;
      PermissionsService.RequestPermissions([cPermissionScheduleExactAlarm],
        procedure(const APermissions: TPermissionArray; const AGrantResults: TPermissionStatusArray)
        begin
          if AGrantResults.AreAllGranted then
            InternalSetExactAlarm(LStartAt, LPendingIntent)
          else
            ; // Suggestions as to what to do? Show a toast? What should it say?
        end
      );
    end
    else
      InternalSetExactAlarm(LStartAt, Result);
  end
  else
    TAndroidHelper.AlarmManager.&set(TJAlarmManager.JavaClass.RTC_WAKEUP, LStartAt, Result);
```

Note how I'm pondering what to do if they decline the permission. Note also that the PendingIntent will be returned regardless of whether or not the alarm is actually set. I thought of adding a custom extra to the PendingIntent to indicate they declined, however that would not be present until *after* the call has returned.

Suggestions welcome :-)

**Comment by MyBuzzTechnologies** [comment]
At face value, that looks like a good implementation, thanks Dave. It uses the canScheduleExactAlarms which is only available in D12, so I assume this implementation only works D12+?

Google say to offer graceful degradation if permission is denied so you could use AlarmManager.setAndAllowWhileIdle() in that case. This doesn't need the permission but also isn't exact.
I experimented with this and it really isn't very reliable but kind-of works and should be as good as you can get in that situation.

The other thing I noticed is, to use scheduled notifications it means you'll now need to request permission to show notifications, then a second permission prompt to request exact scheduling. Not a great UX from Google here, but doesn't seem to be any way around it.

**Comment by DelphiWorlds** [comment]
Updated proposed changes:

```delphi
type
  [JavaSignature('android/app/AlarmManager')]
  JAlarmManagerEx = interface(JObject)
    ['{A03543C2-BB1C-4857-9E68-8EA1328C23A4}']
    function canScheduleExactAlarms: Boolean; cdecl;
  end;
  TJAlarmManagerEx = class(TJavaGenericImport<JAlarmManagerClass, JAlarmManager>) end;

class function TAndroidHelperEx.InternalSetAlarm(const AAction: string; const AAlarm: TDateTime; const AFromLock: Boolean;
  const ARequestCode: Integer = 0; const AServiceName: string = ''): JPendingIntent;
var
  LStartAt: Int64;
  LPendingIntent: JPendingIntent;
begin
  Result := GetAlarmPendingIntent(AAction, AFromLock, ARequestCode, AServiceName);
  LStartAt := GetTimeFromNowInMillis(SecondsBetween(Now, AAlarm));
  // Allow for alarms while in "doze" mode
  if TOSVersion.Check(6) then
  begin
    if TOSVersion.Check(14) and not TJAlarmManagerEx.Wrap(AlarmManager).canScheduleExactAlarms then
    begin
      LPendingIntent := Result;
      PermissionsService.RequestPermissions([cPermissionScheduleExactAlarm],
        procedure(const APermissions: TPermissionArray; const AGrantResults: TPermissionStatusArray)
        begin
          if AGrantResults.AreAllGranted then
            InternalSetExactAlarm(LStartAt, LPendingIntent)
          else
            AlarmManager.setAndAllowWhileIdle(TJAlarmManager.JavaClass.RTC_WAKEUP, LStartAt, LPendingIntent);
        end
      );
    end
    else
      InternalSetExactAlarm(LStartAt, Result);
  end
  else
    TAndroidHelper.AlarmManager.&set(TJAlarmManager.JavaClass.RTC_WAKEUP, LStartAt, Result);
end;
```

`TJAlarmManagerEx` is declared to ensure it will compile in Delphi 11.x as well as Delphi 12

**Comment by MyBuzzTechnologies** [comment]
You read my mind! Thanks for the updated code Dave. I'll give that a test soon but looks like it should work well 👍

**Comment by MyBuzzTechnologies** [comment]
I've reviewed the change and there's a potential problem with this approach.

If you're scheduling multiple alarms (e.g. in a loop), it will call the permission prompt repeatedly which raises a crash. My use-case is that I'm using scheduled notifications as a reminder system, so my app schedules 2 weeks of notifications at once.
A better solution may be to call the permission request once along with the notification permission request when initialising. Or perhaps manually by the app, in order to allow the app to determine when this is shown, rather than at the time of setting the alarm.

A bug I found was:
TJAlarmManagerEx = class(TJavaGenericImport<JAlarmManagerClass, JAlarmManager>) end;

should be:

TJAlarmManagerEx = class(TJavaGenericImport<JAlarmManagerClass, JAlarmManagerEx>) end;

Also, there are a few code issues/typos (e.g. "AlarmManager.setAndAllow..." needs to be TAndroidHelper.AlarmManager... etc) but these are easy to spot during compile time so not going to list them here.

I hope this helps.

**Comment by MyBuzzTechnologies** [comment]
It looks like none of this is going to work anyway sadly. I having re-read the Google page on this, it isn't possible to request permission for SCHEDULE_EXACT_ALARMS from inside your app. It's denied by default for all new installs of the app on Android 14 and not possible to request it programatically. If you try to (as in your code sample) it always returns "denied" and won't prompt the user.

You have to push the user out to the appropriate page in the settings of the phone to allow access to the app, then re-check the canScheduleExactAlarms when the app is resumed.

https://developer.android.com/about/versions/14/changes/schedule-exact-alarms#migration

It looks like there's no point doing much of what you propose. I suggest guarding on canScheduleExactAlarms for Android 14 (as you are), remove the permission request and just use the non-exact scheduling API AlarmManager.setAndAllowWhileIdle as a fallback if canScheduleExactAlarms returns false, otherwise keep using the exact alarm version of the call.

**Comment by DelphiWorlds** [comment]
Thanks for the update! So now the proposed changes are:

```delphi
const
  // String constant defined since the property does not exist on JSettings in Delphi 11.3
  cActionRequestScheduledExactAlarm = 'android.settings.REQUEST_SCHEDULE_EXACT_ALARM';

type
  [JavaSignature('android/app/AlarmManager')]
  JAlarmManagerEx = interface(JObject)
    ['{A03543C2-BB1C-4857-9E68-8EA1328C23A4}']
    function canScheduleExactAlarms: Boolean; cdecl;
  end;
  TJAlarmManagerEx = class(TJavaGenericImport<JAlarmManagerClass, JAlarmManagerEx>) end;

// New function
class function TAndroidHelperEx.CanScheduleExactAlarms: Boolean;
begin
  Result := not TOSVersion.Check(14) or TJAlarmManagerEx.Wrap(AlarmManager).canScheduleExactAlarms;
end;

// New function
class function TAndroidHelperEx.ShowExactAlarmPermissionSettings: Boolean;
begin
  Result := False;
  if not CanScheduleExactAlarms then
  begin
    TAndroidHelper.Context.startActivity(TJIntent.JavaClass.init(StringToJString(cActionRequestScheduledExactAlarm)));
    Result := True;
  end;
end;

class function TAndroidHelperEx.InternalSetAlarm(const AAction: string; const AAlarm: TDateTime; const AFromLock: Boolean;
  const ARequestCode: Integer = 0; const AServiceName: string = ''): JPendingIntent;
var
  LStartAt: Int64;
begin
  Result := GetAlarmPendingIntent(AAction, AFromLock, ARequestCode, AServiceName);
  LStartAt := GetTimeFromNowInMillis(SecondsBetween(Now, AAlarm));
  // Allow for alarms while in "doze" mode
  if TOSVersion.Check(6) then
  begin
    if CanScheduleExactAlarms then
      AlarmManager.setExactAndAllowWhileIdle(TJAlarmManager.JavaClass.RTC_WAKEUP, LStartAt, Result)
    else
      AlarmManager.setAndAllowWhileIdle(TJAlarmManager.JavaClass.RTC_WAKEUP, LStartAt, Result);
  end
  else
    TAndroidHelper.AlarmManager.&set(TJAlarmManager.JavaClass.RTC_WAKEUP, LStartAt, Result);
end;
```

Before they set any alarms, developers can call `ShowExactAlarmPermissionSettings`, and if it returns `True`, wait until the app becomes active (using application events) and check the return value of `CanScheduleExactAlarms` (rather than use a receiver, per the documentation), or just attempt to set the alarm anyway - it just won't be "exact". Developers would need to keep track of whether or not they have already prompted the user - don't want to annoy them with a request every time :-)
