### ISSUE TITLE
[AppUpdate] Add support for iOS

### ISSUE THREAD

**Issue by igorbastosib** [DelphiWorlds/Kastri#204]
Is there any solution for in-APP Update for iOS?

I saw online some solutions about WebService/API for checking the version, but it would really check the APP Store for the logged user.

As happens on Android, it depends on the Play Store cache, the user might not see the update because the cache is out of date, in come point Android updates the cache and our APP shows up the PopUp for updating.

Is there any way for checking the APP Store doing something like Android does? Based on the APP Store cache for the current Device or something alike

**Comment by DelphiWorlds** [comment]
There's a way of checking what the current version of your app is from within your app - it involves making an HTTP request to iTunes, e.g: to a URL of: `https://itunes.apple.com/lookup?bundleId=com.example.yourapp`, where you would replace `com.example.yourapp` with the bundle identifier (CFBundleIdentifier in the version info in Project Options) with the value for your app. 

The result is JSON, which you could parse to find the `version` value. This is a **very** truncated result for the app I have on App Store:

```json
{
  "resultCount":1,
  "results":[
    {
      "fileSizeBytes":"55140352",
      "sellerUrl":"https://www.delphiworlds.com/Memorizor",
      "formattedPrice":"Free",
      "contentAdvisoryRating":"4+",
      "averageUserRatingForCurrentVersion":0,
      "userRatingCountForCurrentVersion":0,
      "averageUserRating":0,
      "trackViewUrl":"https://apps.apple.com/us/app/memorizor/id1303293864?uo=4",
      "trackContentRating":"4+",
      "version":"1.0.0",
      "wrapperType":"software",
      "userRatingCount":0
    }
  ]
}
```

Unfortunately iOS does not provide any means for an app to update itself, and there is also no way of checking if auto-updates are turned on, however if you do the check described above, and the version does not match, it's very likely that the user does not have auto-updates turned on

**Comment by igorbastosib** [comment]
Ty, I'll try it out
