### ISSUE TITLE
[AppleSignIn] Potentionally wrong value stored in TAppleIDCredentials.AuthorizationCode

### ISSUE THREAD

**Issue by havrlisan** [DelphiWorlds/Kastri#207]
When signing in with Apple, the _TAuthorizationControllerDelegate_ stores the received authorization credentials to a TAppleIDCredentials record. However, it seems you've accidentally stored the wrong value in one of the records fields:
```pascal
{ DW.AuthenticationServices.iOS.pas:151 }
LCredentials.AuthorizationCode := NSStrToStr(LAppleIDCredential.email);
``` 
Should it not be the value _LAppleIDCredential.authorizationCode_? Something like this, considering it is of type NSData:
```pascal
if LAppleIDCredential.authorizationCode <> nil then
begin
  var
  LAuthCode := TNSString.Wrap(TNSString.Alloc.initWithData(LAppleIDCredential.authorizationCode, NSUTF8StringEncoding));
  if LAuthCode <> nil then
    LCredentials.AuthorizationCode := NSStrToStr(LAuthCode);
end;
```

**Comment by DelphiWorlds** [comment]
Weird.. not sure how I missed that.. thanks!
