### ISSUE TITLE
[GoogleSignin] manifestmerge giving error code 3

### ISSUE THREAD

**Issue by kmarbach** [DelphiWorlds/Kastri#208]
I have the current version of Kastri. I had D11.1 installed and was getting this error when I compiled the GoogleSignInDemo for 32-bit android:

[Exec Error] The command "\Tools\manifestmerge AndroidManifest.merge.xml Android\Debug\AndroidManifest.xml" exited with code 3.

I completely removed Delphi and installed D12 2 days ago. Getting same error.

I tried several of the other demos, and while the barcode reader is wonky for me, it does compile and run on my Samsung phone.

I get the same error trying to compile for 64-bit:

[Exec Error] The command "\Tools\manifestmerge AndroidManifest.merge.xml Android64\Debug\AndroidManifest.xml" exited with code 3.

Can you point me in the right direction for a solution? I haven't found anything online that addresses this.

**Comment by DelphiWorlds** [comment]
I've pushed a fix for the paths.

**Comment by kmarbach** [comment]
Thank you - I will check that out.
