### ISSUE TITLE
Feature Request: VisionKit

### ISSUE THREAD

**Issue by wcoder18** [DelphiWorlds/Kastri#21]
Are there plans to implement VisionKit?

**Comment by DelphiWorlds** [comment]
The Vision framework has a number of pieces of functionality. Was there something in particular you were looking for? Note that the framework has been imported, here: 
https://github.com/DelphiWorlds/Kastri/blob/master/API/DW.iOSapi.Vision.pas

**Comment by wcoder18** [comment]
I am trying to use the document scanner function in VisionKit. I am developing a receipt app for my organization.

**Comment by DelphiWorlds** [comment]
Please email me personally. My email := 'davidn' + '@' + 'radsoft.com' + '.au";
