### ISSUE TITLE
[Firebase] Is new FCM library compatible with iOs17?

### ISSUE THREAD

**Issue by jmonty77** [DelphiWorlds/Kastri#210]
I 've tested new messaging implementation described in FCM Rebooted demo.

In iOS17, no devicetoken obtained.

My project was working when using firebase 8.6. Also it works with D12 default implementation. So, Firebase and project is correctly configured (GoogleServices-info.plist, CFBundleIdentifier)

Tested with iphone SE2020 iOs 17.2.1, Firebase iOS SDK v10.8.0.

**Comment by DelphiWorlds** [comment]
[Doctor.zip](https://github.com/DelphiWorlds/Kastri/files/14225416/Doctor.zip)
Can you unzip and run the attached utility? It will check for possible issues

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
