### ISSUE TITLE
FCMRebooted error on Android devices with FCM.ShowBannerIfForeground

### ISSUE THREAD

**Issue by elcharlie** [DelphiWorlds/Kastri#213]
I'm trying to run the FCMREbooted demo on  Android Devices it works fine, but I have a problem with the property of FCM object ShowBannerIfForeground.
If i put the property to true, and if a notification is sent, of type no data, and the app is running in the foreground, it crashes. If the application is not running, it is working correctly.
I have tested it on an Android device with version 13 and another with Android 10.

**Comment by DelphiWorlds** [comment]
I'm not receiving an AV when setting `ShowBannerIfForeground` is `True`, however it is not working as expected, i.e. the banner still shows if the value is `False`. Looking into it..

**Comment by DelphiWorlds** [comment]
I've pushed a fix for the issue I mentioned in my last comment, however this is unlikely to solve your issue.

Can you let me know which version of Delphi you are using?\

**Comment by elcharlie** [comment]
Yes, I am testing it with Delphi 12. Without updating the modifications made yesterday, if I set the ShowBannerIfForeground property to false, it does not show the notification when the app is running, it works for me correctly, but if I set it to false, upon receiving the notification, the app closes.
And if I update the modifications made yesterday, it works the same way, if it is set to false, it is not shown but if it is set to true, the application crashes.
I have tested it on an Android device with version 13 and another with Android 10 with delphi 12

**Comment by DelphiWorlds** [comment]
Can you attach the .apk here? You will need to rename the file extension to .zip

**Comment by DelphiWorlds** [comment]
I missed a step in the readme, about when creating your own projects for Android, namely:

https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FCMRebooted#build-event

This is an important step, as it ensures that the `FirebaseMessagingService` from Kastri is used, rather than Embarcadero's

**Comment by elcharlie** [comment]
That was indeed the problem. Thank you very much for your help and sorry for the inconvenience.
Best regards.
