### ISSUE TITLE
Connectivity demo crashes with method not found TJDWNetworkCallback on D11.3

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#216]
I've discovered a crash in the connectivity feature, which raises an EMethodNotFound exception for TJDWNetworkCallback class.

Seems to be raising this on all my test devices (Samsung, OnePlus, Oppo).

This exception is being raised in DW.Connectivity.Android.pas in TNetworkCallbackDelegate.Create (when initialising the JDWNetworkCallback instance). Commenting out this call (or wrapping with exception handling), and the app runs ok.

dw-kastri-base-2.0.0.jar is in the Libraries, and I'm using Delphi 11.3.

Any ideas?

**Comment by MyBuzzTechnologies** [comment]
It looks like you've updated the header to .init() in that Java class to include a new parameter but didn't update/rebuild the dw-kastri-base-2.0.0 jar so it's expecting the old signature still.

**Comment by DelphiWorlds** [comment]
Updated jar has been pushed
