### ISSUE TITLE
SMS: could not send

### ISSUE THREAD

**Issue by alissonrodrigo** [DelphiWorlds/Kastri#219]
I compiled and installed the demo on an Android device (I didn't change anything in the demo) when I put phones from my country (Brazil, +55) it gives me the error "could not send".
I only need to send the message on a single device, the app would not be published on Google Play.
Would it be possible to do this with the demo + kastri in my country?
Grateful

**Comment by alissonrodrigo** [comment]
[SMS.log](https://github.com/DelphiWorlds/Kastri/files/14763862/SMS.log)
 File log

**Comment by alissonrodrigo** [comment]
print device lens
![sms](https://github.com/DelphiWorlds/Kastri/assets/8572209/9da93fb3-c5ac-495e-ab87-f9335e6888b1)

**Comment by DelphiWorlds** [comment]
Are you filtering on Errors only? Please make sure all messages show. Those that appear in the screenshot may be unrelated to the problem

**Comment by alissonrodrigo** [comment]
There is no filter, I also thought it was strange but only this message appeared

**Comment by DelphiWorlds** [comment]
Could you do the same steps as described earlier, but without the Filter On Application filter?

**Comment by alissonrodrigo** [comment]
I'm not using a filter as you can see in the image. Device lens is only loading error messages
![Screenshot_5](https://github.com/DelphiWorlds/Kastri/assets/8572209/8b0025b5-d626-45b9-a7a1-1b922e0f1e96)

**Comment by DelphiWorlds** [comment]
The latest screenshot does not show any messages like in the first one. Are you sure you repeated the process, or is there more messages off-screen? If so, please save the log and attach it following these steps:

1. Start the app, to the point where you are about to click Send (but do not click it)
2. Start Device Lens, and click the "Play" button in the top left
3. Press Send in the app - you should see a number of messages in Device Lens
4. If sending an SMS requires any confirmation, do that
5. If sending fails, right-click the grid in Device Lens, click Save To File to save the log, and attach it to this issue

Screenshots are extremely hard to work with.

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
