### ISSUE TITLE
Google Sign In fail to deploy only works when building the project only

### ISSUE THREAD

**Issue by pejuangdelphi** [DelphiWorlds/Kastri#221]
Dear Team,

I just want to share an interesting issue that need to be fixed soon.

I tried to build project **..\Demos\GoogleSignIn** and worked properly

But... when i tried to run (deploy) the project, the **AndroidManifest.xml** failed to be merged by your tool

I upload the screenshot to help you investigate the problem is

Thank you so much for the attention

![Fail to Sign In](https://github.com/DelphiWorlds/Kastri/assets/45804972/35baf032-b096-472c-ad44-75b6a7a6e1f8)

**Comment by DelphiWorlds** [comment]
It's because of a [change to the build process in Delphi 12.1](https://github.com/DelphiWorlds/Kastri/issues/220). The [readme has been updated](https://github.com/DelphiWorlds/Kastri/blob/master/Demos/GoogleSignIn/Readme.md#build-eventandroid-manifest) to add instructions on how to manually modify `AndroidManifest.template.xml`

**Comment by pejuangdelphi** [comment]
Thank you so much for the respond but still error in my IDE Delphi

I tried to merge manually with command prompt then using the result as the AndroidManifest.template and run well now

Now, the problem after try to login with gmail, i got error code 10

I have setup my Firebase project using this article

https://docwiki.embarcadero.com/RADStudio/Sydney/en/Firebase_Android_Support

Do you have the same experience how to solve it?

**Comment by DelphiWorlds** [comment]
Error 10 is almost certainly an incorrect SHA1 signature value in your project configuration in Firebase Console. 

As per the demo readme, you need to create a SHA1 signature for your project, [as per these instructions](https://github.com/grijjy/DelphiGoogleSignIn#getting-started-with-the-google-signin-sdk) in Grijjy's repo. Once you've created a SHA1 signature (fingerprint), go to [Firebase Console](https://console.firebase.google.com), select your project, click the cog icon in the top left corner and click Settings. Select the Android app and add a signature, as per this image:

![image](https://github.com/DelphiWorlds/Kastri/assets/22670829/1498a618-1b5c-4ebb-9ae8-5d19fccefa6e)

**Comment by pejuangdelphi** [comment]
Thank you so much for your best support

I have setup before and check it again and alerady the same

still get the same error code 10
![Fail to Sign In](https://github.com/DelphiWorlds/Kastri/assets/45804972/57af8228-50d8-4d54-8729-9ba2ed1b2abe)
![Fail to Sign In 2](https://github.com/DelphiWorlds/Kastri/assets/45804972/56efc6a7-4ff5-468c-91fe-a0af345b0246)

**Comment by DelphiWorlds** [comment]
I'm having the same issue now. Something might have changed in the requirements. Looking into it...

**Comment by pejuangdelphi** [comment]
For your information, I have sent message to Google Tim about this issue. Waiting for their respond too

Please let me know when you can solved it first and i will let you know when i can solve it

**Comment by pejuangdelphi** [comment]
Maybe you can use this information as the clue how to solve the problem.

https://developers.google.com/identity/gsi/web/guides/migration.

**Comment by DelphiWorlds** [comment]
That link is related to signing in with web applications, however it has alerted me to this regarding migrating from Google SignIn to Google Identity Services: https://developers.google.com/identity/android-credential-manager

I'm still looking into why Google SignIn is not working. Despite there being a new API, Google SignIn should still work

**Comment by DelphiWorlds** [comment]
I managed to get mine working again.. I expect it was because on the OAuth 2 Consent page, I had changed it to "Production". Switching it back to "Testing" seems to have fixed it:

<img width="1551" alt="image" src="https://github.com/DelphiWorlds/Kastri/assets/22670829/998d9cce-50fe-4107-9873-60cee88b931b">

**Comment by pejuangdelphi** [comment]
The Google Team has also responded to my email, stating that I need to add scopes and resubmit in order to activate the button for re-verification.

![Untitled](https://github.com/DelphiWorlds/Kastri/assets/45804972/4579b83d-c518-4502-9182-f5bfca9191a8)

**Comment by DelphiWorlds** [comment]
Which scopes did they suggest you add?

**Comment by pejuangdelphi** [comment]
You can see the response, and as an alternative, can changing the icon.

![Untitled](https://github.com/DelphiWorlds/Kastri/assets/45804972/3d7f8055-a766-4edb-b958-2157b82c30e5)

**Comment by pejuangdelphi** [comment]
My OAuth consent screen is already verified.

![Fail to Sign In 1](https://github.com/DelphiWorlds/Kastri/assets/45804972/ec0d494a-e08e-4611-bbf0-c6fcf861bea8)

Then my app ownership has been verified. 

![Fail to Sign In 2](https://github.com/DelphiWorlds/Kastri/assets/45804972/3ca70cd5-e2a3-4df0-8dc0-f82e4137d6da)

Still get error code 10

**Comment by pejuangdelphi** [comment]
I use this one

![Untitled](https://github.com/DelphiWorlds/Kastri/assets/45804972/3e68efed-0df2-4549-a094-c63f0b337371)

**Comment by DelphiWorlds** [comment]
Not sure if I can help, then. Seems you may have to ask Google.

**Comment by pejuangdelphi** [comment]
I still communicate with them over email and report about this issue.

Then, I also describe the steps that I already did until the last process in order for them to be easier to investigate.

**Comment by pejuangdelphi** [comment]
I have integrated to Firebase too.

Could you help me to check my AndroidManifest.xml

Then... I try both of these code with the same result

1. FGoogleSignIn.SignIn('cClientID, ['email']);
2. FGoogleSignIn.SignIn('cClientID, ['[email](https://www.googleapis.com/auth/userinfo.email)']);

[AndroidManifest.zip](https://github.com/DelphiWorlds/Kastri/files/14933437/AndroidManifest.zip)

**Comment by DelphiWorlds** [comment]
If you are still receiving error 10, it is unlikely to be anything to do with your manifest. I highly suspect you are not using the correct SHA-1 value which you assign in Firebase Console, as per this reply: https://github.com/DelphiWorlds/Kastri/issues/221#issuecomment-2041279813.

I've added code to the demo which can help determine whether or not you are using the correct SHA-1, as it retrieves the value from **within the app**

**Comment by avitos** [comment]
I am also getting error -10. True, SHA-1 is used by androiddebugkey (local and not associated with Google Play). But SHA-1 is loaded in Firebase Console.

By the way SHA-1 is not shown in the demo. Can you tell me if Google SignIn is working now?

**Comment by DelphiWorlds** [comment]
It works for me - I'm not sure why it does not work for you or pejuangdelphi

**Comment by avitos** [comment]
> У меня это работает - не знаю, почему это не работает у вас или pejuangdelphi.

It's working. In my case, the problem was in the package name - it must be named by the standard “com.company.app” . I made just “com.app” for the test (and firebase treated it fine), and was getting the error.

Thanks a lot Dave!

**Comment by DelphiWorlds** [comment]
Thanks for letting me know!
