### ISSUE TITLE
[CrossPlatformLocation] demo crashes in Delphi DX12.1

### ISSUE THREAD

**Issue by edwin-completesolutions** [DelphiWorlds/Kastri#222]
The CrossPlatformLocation works in DX11. We are testing the upgrade to DX12.1 using the [CPLAndroidGroupD11.groupproj](https://github.com/DelphiWorlds/Kastri/blob/master/Demos/CrossPlatformLocation/CPLAndroidGroupD11.groupproj) demo. 
Using the 3.0.0.jar files (e.g. dw-kastri-base-3.0.0.jar.) we compiled the project as found in Demos/CrossPlatformLocation.
As soon as the app starts on Android it crashes. First time it starts it does request for location permissions, which were granted. We tested on Android v12 and Android v14. Both the 32 bit as the 64 bit versions of the application seem to crash.
Would it be possible to fix this and perhaps add a D12 version?

**Comment by DelphiWorlds** [comment]
I expect you did not change the reference for `dw-fusedlocation.jar` to `dw-fusedlocation-3.0.0.jar`, however I have added group and project files for Delphi 12.x with all the necessary configuration, and updated the readme to detail what is required to configure your own (i.e. not the demo) project
