### ISSUE TITLE
Firebase Analytics doesnt work with Delphi 12.1 on Android devices.

### ISSUE THREAD

**Issue by elcharlie** [DelphiWorlds/Kastri#228]
I updated a project, which uses firebase analytics, from delphi 12 to delphi 12.1, and it stopped working on Android devices.
Push notifications, with the new modification of AndroidManifest.template.xml, work correctly for me, but analytics does not.
 I don't know, if I have to change something in the AndroidManifest.merge.xml, or just remove it. 
My AndroidManifest.merge.xml is:

```
<manifest xmlns:merge="http://www.delphiworlds.com/xmlns/merge" xmlns:android="http://schemas.android.com/apk/res/android">
    <application>
        <meta-data android:name="com.google.android.gms.version" android:value="12451000" />
        <service merge:update="android:name=&quot;com.google.firebase.components.ComponentDiscoveryService&quot;">
            <meta-data android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>
    </application>
</manifest>
```

how can I solve that?

**Comment by DelphiWorlds** [comment]
See [this issue](https://github.com/DelphiWorlds/Kastri/issues/220) regarding why manifest merging does not work with Delphi 12.1. 

I need to update the Firebase Analytics demo to account for this issue

**Comment by elcharlie** [comment]
Oh, sorry. I thought the error had not been reported, sorry.
I'm trying to modify the AndroidManifest.template.xml to make it work, but so far without any success. If I get it, I'll let you know.

**Comment by DelphiWorlds** [comment]
That's OK - it was me that reported it :-)

It's going to be a challenge. It might need the manifest to be deployed separately, i.e instead of the "default" one that Delphi deploys.

**Comment by elcharlie** [comment]
Ok, I will wait for a solution to be found, since no matter how much I try to modify the AndroidManifest.template.xml, I get no results.
Thank you.

**Comment by elcharlie** [comment]
I've been trying things.
I have customized my AndroidManifest.template.xml, I have removed <%services%> and I have added the services one by one.
I added this:
`<service android:name="com.google.firebase.components.ComponentDiscoveryService"
       			android:directBootAware="true"
       			android:exported="false">
			<meta-data android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />
			<meta-data android:name="com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar"
         				android:value="com.google.firebase.components.ComponentRegistrar"/>
			<meta-data android:name="com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar"
         				android:value="com.google.firebase.components.ComponentRegistrar"/>
			<meta-data android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar"
         				android:value="com.google.firebase.components.ComponentRegistrar"/>
		</service>`
and yet it still doesn't work for me. I don't know where to continue.

**Comment by DelphiWorlds** [comment]
I'll have a look at it in a few hours

**Comment by elcharlie** [comment]
Ok, I appreciate it, I can't make it work

**Comment by DelphiWorlds** [comment]
I have managed to make it work using the attached `AndroidManifest.template.xml` (zipped)

If you use the following adb command (in a command line window on the machine that the device is connected to):

```
adb shell setprop debug.firebase.analytics.app <packagename>
```

(where <packagename> is the value you have for package in the Version Info of the Project Options)
You should be able to see the events using the Analytics > Debug View in Firebase console like this:

<img width="1526" alt="image" src="https://github.com/DelphiWorlds/Kastri/assets/22670829/a30b62b5-3ea6-4370-9f72-a4176490b0c2">

[AndroidManifest.template.xml.zip](https://github.com/user-attachments/files/15687677/AndroidManifest.template.xml.zip)

**Comment by elcharlie** [comment]
It has worked perfectly for me, I have adapted your AndroidManifest.template.xml to mine, and it worked for me on the first try. Hopefully in the future, it can be done as before, but for now it is a good solution.
Thank you very much for the help, it makes me angry that I couldn't do it myself, but thank you very much for everything.
All the best,

**Comment by elcharlie** [comment]
The key is that I have had to add
`<meta-data android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />`

on the service 
`<service android:name="com.google.firebase.components.ComponentDiscoveryService" android:directBootAware="true" android:exported="false">`

and with this modification, it has worked for me.
