### ISSUE TITLE
Ask for about VideoPlayer

### ISSUE THREAD

**Issue by jiangwei7480** [DelphiWorlds/Kastri#229]
Hello：
   I think know VideoPlayer demo, it player from rtsp?

**Comment by DelphiWorlds** [comment]
I'm adding support for it, but I cannot find any RTSP links that actually work, that I can test against. I've tried these so far:

```
rtsp://b03773d78e34.entrypoint.cloud.wowza.com:1935/app-4065XT4Z/80c76e59_stream1
rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream
rtsp://rtsp-test-server.viomic.com:554/stream
rtsp://rtsp.stream/movie
rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa
rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
```

**Comment by jiangwei7480** [comment]
Hello:
I test VideoPlayer Demo, Happen error. system hint: java .lang.IllegalStateException:No suitable media source
factory found for content type:3.
I edit streams.json, add a rstp url:
{ 
"Channel": "KC.Test", 
"Location": "Global", 
"URL": "rtsp:\/\/192.168.1.164:554\/ch01.264", 
"MaxResolution": "" 
} 
I very much hope to so function. 
Good luck implementing this feature soon.
Buy a webcam that has rtsp capabilities, so you can use it to test.
---- Replied Message ----
***@***.***>Date6/12/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
I'm adding support for it, but I cannot find any RTSP links that actually work, that I can test against. I've tried these so far:
rtsp://b03773d78e34.entrypoint.cloud.wowza.com:1935/app-4065XT4Z/80c76e59_stream1 rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream rtsp://rtsp-test-server.viomic.com:554/stream rtsp://rtsp.stream/movie rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov

**Comment by DelphiWorlds** [comment]
> Buy a webcam that has rtsp capabilities, so you can use it to test

It would be nice if I could buy one ;-)

Since you have one, I have pushed the changes to Kastri (including the demo) so you can test. Please let me know if it works.

**Comment by jiangwei7480** [comment]
Hello:
Very happy. I would love to take the test.
---- Replied Message ----
***@***.***>Date6/13/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
Buy a webcam that has rtsp capabilities, so you can use it to test
It would be nice if I could buy one ;-)
Since you have one, I have pushed the changes to Kastri (including the demo) so you can test. Please let me know if it works.

**Comment by DelphiWorlds** [comment]
I managed to find this software: https://www.deskcamera.com/
Which turns the camera on my Windows PC into an RTSP stream. Works OK on Android. Fails on iOS, so I need to work that out

**Comment by DelphiWorlds** [comment]
OK.. I had mistakenly thought that AVPlayer on iOS supports RTSP - unfortunately it does not. For now, the notion of playing RTSP on iOS is shelved, as far as the VideoPlayer feature goes. 

Seems to work fine on Android now, though :-)

**Comment by jiangwei7480** [comment]
Hello:
I download kastri library from new GitHub, compile and run after clicking no response, the screen is black and there is no error. However, I run the VLC player on the computer is able to perform rstp pull stream playback.
There is nothing more to it than adding rstp files！
---- Replied Message ----
***@***.***>Date6/13/2024 ***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
Hello:
Very happy. I would love to take the test.
---- Replied Message ----
***@***.***>Date6/13/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
Buy a webcam that has rtsp capabilities, so you can use it to test
It would be nice if I could buy one ;-)
Since you have one, I have pushed the changes to Kastri (including the demo) so you can test. Please let me know if it works.

**Comment by DelphiWorlds** [comment]
I don't understand your latest response - are you running the app on Android? It is working for me.

You may need to do a Clean, then Build

**Comment by jiangwei7480** [comment]
Hello：
My app demo is running on android13 version, Delphi compilation environment is D12.1.
App Demo is compiled after the new Clean, and VideoPlayerdemo.R.ar is also repackaged, the built-in VideoPlayerdemo.R.ar is not good
---- Replied Message ----
***@***.***>Date6/13/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
I don't understand your latest response - are you running the app on Android? It is working for me.
You may need to do a Clean, then Build

**Comment by DelphiWorlds** [comment]
> the built-in VideoPlayerdemo.R.ar is not good

What do you mean by "is not good"? It works fine for me. Pixel 6 Pro running Android 14

**Comment by jiangwei7480** [comment]
Hello:
yes, the built-in VideoPlayerdemo.R.ar don't use direct. I repackage it, run ok.
now the trouble don't can player rstp stream. Test env: My android version is 13.
---- Replied Message ----
***@***.***>Date6/13/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
the built-in VideoPlayerdemo.R.ar is not good
What do you mean by "is not good"? It works fine for me. Pixel 6 Pro running Android 14

**Comment by DelphiWorlds** [comment]
Do you see media3-exoplayer-rtsp-1.3.0.jar in the Libraries under Android 32-bit in Project Manager, like in this screenshot?

<img width="344" alt="image" src="https://github.com/DelphiWorlds/Kastri/assets/22670829/c57e0fb0-fc6c-4cbb-a8b0-5918a4d1b503">

If not, you need to synch the project from the repo.

**Comment by jiangwei7480** [comment]
The media3-exoplayer-rtsp-1.3.0.jar file you mentioned is available, otherwise clicking to run will prompt an error.
---- Replied Message ----
***@***.***>Date6/13/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
Do you see media3-exoplayer-rtsp-1.3.0.jar in the Libraries under Android 32-bit in Project Manager, like in this screenshot?
image.png (view on web)If not, you need to synch the project from the repo.

**Comment by jiangwei7480** [comment]
hello:
I tried many times, but I still couldn't perform rtsp pull stream playback, and nothing worked properly after clicking the play button. My programming environment is Delphi12.1, and the installation tablet is Xiaomi Pro5. For Android version 13, here are the streaming configuration URIs:
{ 
"Channel": "KC.Test.rtsp", 
"Location": "Global", 
"URL": "rtsp:\/\/192.168.1.164:554\/ch01.264", 
"MaxResolution": "1080p" 
}
I hope it can help me find the problem and the reason, thank you!
---- Replied Message ----
***@***.***>Date6/13/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
Do you see media3-exoplayer-rtsp-1.3.0.jar in the Libraries under Android 32-bit in Project Manager, like in this screenshot?
image.png (view on web)If not, you need to synch the project from the repo.

**Comment by DelphiWorlds** [comment]
You might have to [use a log viewer](https://github.com/DelphiWorlds/HowTo/tree/main/Solutions/LogViewers) to check for log messages as to why it is not playing. Incidentally, what RTSP server are you using?

**Comment by jiangwei7480** [comment]
hello:
The following is a screenshot of debugging related error messages, I can not understand, please look at the problem? thank you!
---- Replied Message ----
***@***.***>Date6/14/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
You might have to use a log viewer to check for log messages as to why it is not playing. Incidentally, what RTSP server are you using?

**Comment by DelphiWorlds** [comment]
I don't see a screenshot

**Comment by DelphiWorlds** [comment]
There is no attachment. Please use the Github issue page to add the screenshot. The text of log as an attachment would be way better, though

**Comment by jiangwei7480** [comment]
The following picture is the debugging information I captured. What is the problem
![image](https://github.com/DelphiWorlds/Kastri/assets/80150274/93577890-83d2-4155-8438-b1deecdd547e)

**Comment by jiangwei7480** [comment]
hello, I have submitted pictures on github issue, please take a look.
---- Replied Message ----
***@***.***>Date6/14/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
There is no attachment. Please use the Github issue page to add the screenshot. The text of log as an attachment would be way better, though

**Comment by DelphiWorlds** [comment]
Unfortunately, too much information in your screenshot is cut off. This is one reason why text logs are much preferred. Since you are using Device Lens, you can right click the grid, and click `Save To File...`

**Comment by jiangwei7480** [comment]
hello:
Today, the run test was successful, and later I knew why it was successful, because I set the camera code to 720P, stream: 320K. The camera default is 2592*1904, the stream: 2Mbps. Why is it too high?
---- Replied Message ----
***@***.***>Date6/15/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
Unfortunately, too much information in your screenshot is cut off. This is one reason why text logs are much preferred. Since you are using Device Lens, you can right click the grid, and click Save To File...

**Comment by DelphiWorlds** [comment]
> Why is it too high?

I do not know. If I had complete error information (error messages were cut off in your screenshot), I might be able to find out

**Comment by jiangwei7480** [comment]
Hello:
This time, there was a new problem. After I restored the coding Settings to the default, I played the app again and directly exited. The original was not exited but a black screen, and the attachment was saved debugging information.
---- Replied Message ----
***@***.***>Date6/15/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [DelphiWorlds/Kastri] Ask for about VideoPlayer (Issue #229)
Why is it too high?
I do not know. If I had complete error information (error messages were cut off in your screenshot), I might be able to find out

**Comment by DelphiWorlds** [comment]
> The original was not exited but a black screen, and the attachment was saved debugging information.

Is there meant to be an attachment? Again, there is none. Please use the Github issue page, as it seems attaching to emails does not work

**Comment by jiangwei7480** [comment]
[VideoPlayer_debug.log](https://github.com/user-attachments/files/15846121/VideoPlayer_debug.log)

Please check log file.

**Comment by DelphiWorlds** [comment]
These seem to be the relevant lines:

```
2024/06/15 15:32:27.795	E	com.embarcadero.VideoPlayerDemo	17018	17018	linker	library "/system_ext/lib64/libmigl.so" ("/system_ext/lib64/libmigl.so") needed or dlopened by "/system/lib/libEGL.so" is not accessible for the namespace: [name="(default)", ld_library_paths="", default_library_paths="/system/lib:/system_ext/lib", permitted_paths="/system/lib/drm:/system/lib/extractors:/system/lib/hw:/system_ext/lib:/system/framework:/system/app:/system/priv-app:/system_ext/framework:/system_ext/app:/system_ext/priv-app:/vendor/framework:/vendor/app:/vendor/priv-app:/system/vendor/framework
2024/06/15 15:32:27.795	E	com.embarcadero.VideoPlayerDemo	17018	17018	libEGL	open /system_ext/lib64/libmigl.so failed! dlopen - dlopen failed: library "/system_ext/lib64/libmigl.so" needed or dlopened by "/system/lib/libEGL.so" is not accessible for the namespace "(default)"
```

..and some Googling reveals that it seems to affect Xiaomi devices. Not sure if I can help with this.
