### ISSUE TITLE
Closed due to inactivity

### ISSUE THREAD

**Issue by alpires** [DelphiWorlds/Kastri#23]
Hi, but if I use DW.Notifications of kastri, I get the error in:

function TPlatformNotificationChannel.GetSound: string;
begin
  Result := JURIToStr(FChannel.getSound);
end;
[DCC Error] DW.Notifications.Android.pas(186): E2003 Undeclared identifier: 'getSound'

Closed due to inactivity

_Originally posted by @DelphiWorlds in https://github.com/DelphiWorlds/Kastri/issues/15#issuecomment-724373914_

**Comment by DelphiWorlds** [comment]
Updated Core\DW.Androidapi.JNI.App.pas and Features\Notifications\DW.Notifications.Android.pas to fix this issue
