### ISSUE TITLE
Unable to compile DW.AdMobBannerAd.iOS.pas with latest Kastri sources and D12.1

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#230]
Fresh Kastri clone (latest sources 25th June 2024).
BannerAd control built and installed into the IDE from the Kastri\Controls folder.

New FMX app.
Drop an AdMobBannerAd onto the form (align bottom, etc - makes no difference).
Add the necessary paths to the project search property is needed.

Build.

Seems that the version of UIViewController in the DW sources seems to be incompatible with the ones deployed by Delphi.

[DCC Error] DW.AdMobBannerAd.iOS.pas(141): E2010 Incompatible types: 'DW.iOSapi.UIKit.UIViewController' and 'iOSapi.UIKit.UIViewController'

**Comment by DelphiWorlds** [comment]
Committed a fix

**Comment by MyBuzzTechnologies** [comment]
That's working thanks Dave
