### ISSUE TITLE
Unable to build FCMBaseDemoD12 for iOS due to missing TUITraitEnvironment

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#231]
When I try to build the FCMBaseDemoD12 project (FCMRebooted) in Delphi 12.1, it errors due to a missing type in DW.iOSapi.UIKit.pas.

[DCC Error] DW.UIHelper.iOS.pas(118): E2003 Undeclared identifier: 'TUITraitEnvironment'

**Comment by DelphiWorlds** [comment]
Committed a fix

**Comment by MyBuzzTechnologies** [comment]
That's now working, thanks Dave
