### ISSUE TITLE
No longer able to build iOS apps containing the AdMobBannerAd control

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#232]
Run the Admob Demo App from Kastri.
Also does it on a new, empty app.

First chance exception at $0000000102B80BB4. Exception class EAccessViolation with message 'Access violation at address 0000000102B80BB4, accessing address 800000003F800008'. Process FMTest (833)

<img width="744" alt="image" src="https://github.com/DelphiWorlds/Kastri/assets/37405280/e85cb95b-76c3-4d6e-b336-a170331416dc">

**Comment by DelphiWorlds** [comment]
Pushed a fix

**Comment by MyBuzzTechnologies** [comment]
Thanks Dave, that's now working again 🎉
