### ISSUE TITLE
In the FCM Rebooted demo app (iOS, D11.3 or D12.1), first run of the app doesn't receive a token unless FCM.SubscribeTopic() is called in FCMStarted callback

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#233]
I spent days trying to work out why my app wasn't receiving push tokens when first run on iOS, but was on subsequent runs.

Tracing the code, the TFIRMessagingDelegate.messaging callback never gets called with the token on first run.

After comparing to the FCMRebooted demo, I found that you have to include an FCM.SubscribeTopic() call in the FCMStarted callback. If you do this, it receives a token every time!

I have no idea whether this is a bug in FCM or in Kastri, but I wanted to log it here for others who might experience the same issue.

**Comment by DelphiWorlds** [comment]
That's pretty weird - `SubscribeToTopic` should be independent from the other workings of FCM. Might be that something `SubscribeToTopic` does causes some initialization that can be done some other way. Looking at this today

**Comment by DelphiWorlds** [comment]
Can you try again with the changes which have just been pushed? Essentially, it defers calling `TFIRApp.OCClass.configure` until `Start` is called.

**Comment by MyBuzzTechnologies** [comment]
That seems to have worked 🎉 Thanks Dave
