### ISSUE TITLE
Crash with Biometrics demo on Android 10 (Samsung Galaxy S9 series)

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#238]
Installing the Biometrics demo app from Kastri (Delphi 12.1) onto an Android 10 device crashes the app due to a missing resource.
I've checked and the BiometricsDemoD12.R.jar, dw-biometrics-2.0.0 and dw-kastri-base-3.0.0 jar files are in the project Libraries list.

Works fine on newer Android versions. I've tested on Android 11 through 14

Exception from logcat:

android.content.res.Resources$NotFoundException: String array resource ID #0x7f0e0003

<img width="937" alt="Screenshot 2024-07-26 at 12 17 14" src="https://github.com/user-attachments/assets/ccc218cc-3897-466a-a4e4-59f834f64669">

**Comment by DelphiWorlds** [comment]
When does the error occur? Unfortunately I do not have an Android 10 device with biometrics on it to test

**Comment by MyBuzzTechnologies** [comment]
It shows the system dialog asking you to authenticate, which works fine. This device uses fingerprint but if you use that or the backup code, it says that it's successful then the app crashes.
Almost as if it's when returning to the app?
Almost looks like the R file isn't quite right given it's an error about a missing lookup reference but not sure why that would be.

Unfortunately I can't debug onto that device - the debugger just hangs when it tries to attach, but that's pretty normal for me in D12.1

I'm happy to test anything you want to send over.

**Comment by DelphiWorlds** [comment]
[BiometricDemoD12.R.zip](https://github.com/user-attachments/files/16419233/BiometricDemoD12.R.zip)

Can you try this replacement? Note: It's for D12.1

**Comment by MyBuzzTechnologies** [comment]
Thanks Dave. When I build your latest code I'm getting:

[PAClient Error] Error: E8200 C:\Development\Components\kastri-master\Demos\Biometric\Android64\Debug\AndroidManifest.xml:81: error: resource style/Theme.AppCompat.Light (aka com.delphiworlds.BiometricDemoD12:style/Theme.AppCompat.Light) not found.

Is there a style.xml file I'm missing?

**Comment by DelphiWorlds** [comment]
> Is there a style.xml file I'm missing?

Yes - I had not realised that the resources for the demo were not checked in - they are now

**Comment by MyBuzzTechnologies** [comment]
Thanks Dave, that seems to have worked 🎉
