### ISSUE TITLE
VideoPlayerDemo Build and Another Error

### ISSUE THREAD

**Issue by bo3l4q** [DelphiWorlds/Kastri#242]
I use Delphi 11 Alexandria
Building VideoPlayerDemo.dproj (Debug, Android) - Android 32-bit

**1. ERROR**
[DCC Error] DW.Androidapi.JNI.Guava.pas(222): E2003 Undeclared identifier: 'JMap_Entry'
[DCC Error] DW.Androidapi.JNI.Guava.pas(255): E2005 'JMap_Entry' is not a type identifier
[DCC Error] DW.Androidapi.JNI.Guava.pas(556): E2005 'JMap_Entry' is not a type identifier
[DCC Error] DW.Androidapi.JNI.Guava.pas(616): E2005 'JMap_Entry' is not a type identifier
[DCC Fatal Error] DW.Androidapi.JNI.AndroidX.Media3.Common.pas(21): F2063 Could not compile used unit 'DW.Androidapi.JNI.Guava.pas'
**-- I tried to fix it by adding unit: DW.Androidapi.JNI.Util**

**2. ERROR**
[DCC Error] DW.Androidapi.JNI.AndroidX.Media3.ExoPlayer.pas(737): E2003 Undeclared identifier: 'JLogSessionId'
[DCC Error] DW.Androidapi.JNI.AndroidX.Media3.ExoPlayer.pas(745): E2005 'JLogSessionId' is not a type identifier
[DCC Fatal Error] DW.VideoPlayer.View.Android.pas(22): F2063 Could not compile used unit 'DW.Androidapi.JNI.AndroidX.Media3.ExoPlayer.pas'
**-- I can't find a suitable unit. I had to skip it by adding a comment "//"**

**3. ERROR**
PAClient Error] Error: E2312
 D:\Embacadero\Component\Android\Kastri\Demos\VideoPlayer\Android\Debug\VideoPlayerDemo\AndroidManifest.xml:22: error: No resource identifier found for attribute 'requestLegacyExternalStorage' in package 'android'
**-- Error if using platforms Android-29 and below, if platforms Android-29 and above OK**

**4. ERROR**
![Screenshot_8](https://github.com/user-attachments/assets/a0fd9fbe-0472-4f08-9e1a-e9c5d73b54c9)
![WhatsApp Image 2024-08-11 at 19 50 47_52559e87](https://github.com/user-attachments/assets/7d8d1e42-4684-4d44-8a7c-715db2768388)

**HOW TO FIX**

**Comment by DelphiWorlds** [comment]
I have pushed fixes for the compile errors. Not sure what the problem with the manifest is, but you might want to take a look at [this StackOverflow post](https://stackoverflow.com/a/71600417/3164070). I'll double-check the Android 10 issue, but I'm pretty sure I had it working on an Android 10 device, but that was using Delphi 12.1

**Comment by bo3l4q** [comment]
![image](https://github.com/user-attachments/assets/4d7a4625-b13d-4bab-90b3-a9508fea89f7)

I tried using Delphi 12.1 Athens, the result is the same.
And it turns out the bug is here: **"FPlayer := TVideoPlayer.Create;"**

**Comment by DelphiWorlds** [comment]
Not sure why it is not working for you using Delphi 12.1 - it works on Android 10 here for me. Can you rename your .apk to have a .zip extension, and attach it here?

**Comment by bo3l4q** [comment]
![image](https://github.com/user-attachments/assets/4e656cfc-d678-46b9-a2af-e1d1606ce730)

**Comment by bo3l4q** [comment]
[APK_Compiled_D12.1_VideoPlayerDemo.rar](https://www.mediafire.com/file/xrjx4pljqvopt7k/APK_Compiled_D12.1_VideoPlayerDemo.rar/file)

I tested, if this is marked with a comment, that's normal.
but the video player can't be opened.

![image](https://github.com/user-attachments/assets/f1e18f6a-34ac-41d0-96f3-f552ebe57423)

**Comment by DelphiWorlds** [comment]
Can you make sure that the `VideoPlayerDemo.R.jar` file in the `Lib` folder of the demo is [this one](https://github.com/DelphiWorlds/Kastri/blob/master/Demos/VideoPlayer/Lib/VideoPlayerDemo.R.jar), i.e. the one that is currently checked in to the repo?

**Comment by bo3l4q** [comment]
![image](https://github.com/user-attachments/assets/5e478865-936f-4b4b-9b31-4fab452dd06b)
I haven't changed any of my previously uploaded APKs

**Comment by bo3l4q** [comment]
Can you upload the APK you created?.
for me to test

**Comment by DelphiWorlds** [comment]
> I haven't changed any of my previously uploaded APKs

I meant make sure that `VideoPlayerDemo.R.jar` is **exactly** the same one as in the repo.

> Can you upload the APK you created?.

[32 bit version](https://www.delphiworlds.com/files/temp/VideoPlayerDemo.32bit.zip)
[64 bit version](https://www.delphiworlds.com/files/temp/VideoPlayerDemo.64bit.zip)

**Comment by bo3l4q** [comment]
wait, I'll test

**Comment by bo3l4q** [comment]
Tested Android 11 ---> OK
Tested Android 13 ---> OK
So where did it go wrong?
What API platform do you use?

![boelaq](https://github.com/user-attachments/assets/5f86465b-2e38-4a9b-baf9-d41d0182a1ab)

**Comment by DelphiWorlds** [comment]
> So where did it go wrong?

With your APK, using [Device Lens](https://github.com/DelphiWorlds/DeviceLens) I see these messages when starting the app:

```
2024/08/14 12:35:04.224	W	com.embarcadero.VideoPlayerDemo	6675	6675	System.err	android.content.res.Resources$NotFoundException: Resource ID #0x7f090006
2024/08/14 12:35:04.224	W	com.embarcadero.VideoPlayerDemo	6675	6675	System.err	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:266)
2024/08/14 12:35:04.224	W	com.embarcadero.VideoPlayerDemo	6675	6675	System.err	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2558)
```

Which suggests to me either you are *not* using the `VideoPlayerDemo.R.jar` from the repo, **or** you have changed the deployment in the demo (i.e. required resources are not being deployed). Easiest way to find out is to get a complete new copy of the repo, or if you are using a Git client, check for changes you might have made and discard them, and rebuild the app.

> What API platform do you use?

I am using the default platform level for Delphi 12.1, which is android-34.

**Comment by bo3l4q** [comment]
I've done 2x git clones, I haven't changed anything about the Video Player Demo project.
I decompiled your APK. Then I compared it with my APK, it turned out to be very different. Your APK resources contain a lot of them.
In the Delphi Deployment section, you have the directory location: "Resources\Merged\res\"
But the git clone results don't have that directory, Maybe I should make a video to convince you.

**Comment by DelphiWorlds** [comment]
> But the git clone results don't have that directory

Ah... very sorry! I thought I had included them. They are now included.

**Comment by bo3l4q** [comment]
Thank You...
Thank you very much, I just built it.
100% Working.

Tested --> Android 11
Tested --> Android 13
Tested --> BlueStacks

![image](https://github.com/user-attachments/assets/e8248f08-1a72-4255-9217-96150918ccc2)

**Comment by DelphiWorlds** [comment]
Great to hear!
