### ISSUE TITLE
iOs 18 OpenUrl don't work

### ISSUE THREAD

**Issue by maurobotta** [DelphiWorlds/Kastri#253]
Hi @DelphiWorlds 

i have a problem, i have update Delphi to 12.2 and i have a problem with my ios 18 Mobile App. 

App "Apple Map" don't open when i call it.

code:

  NSU := StrToNSUrl(URL);
  if SharedApplication.canOpenURL(NSU) then
    begin
    SharedApplication.openUrl(NSU);
    end;

I had doubts that it was KASTRI then I saw this link of yours:

Fix OpenURL for iOS 18+

https://github.com/DelphiWorlds/Kastri/commit/69f608e65259f4b56eb3ebe5a36f386348ac365c

I'm using Kastri Commits on Sep 26, 2024

Thank you. again.

Delphi 12.2
IOS 18,  iPhone 12

Mauro

**Comment by DelphiWorlds** [comment]
> I had doubts that it was KASTRI then I saw this link of yours:

Are you saying the recent fix does not work for you? If so, please supply a reproducible example. If you're looking for an example of how to use the change:

```delphi
unit Unit1;

interface

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,
  FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs, FMX.Controls.Presentation, FMX.StdCtrls;

type
  TForm1 = class(TForm)
    Button1: TButton;
    procedure Button1Click(Sender: TObject);
  private
    procedure OpenCompletionHandler(success: Boolean);
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.fmx}

uses
  DW.OSDevice;

procedure TForm1.Button1Click(Sender: TObject);
begin
  TOSDevice.OpenURL('https://www.embarcadero.com', OpenCompletionHandler);
end;

procedure TForm1.OpenCompletionHandler(success: Boolean);
begin
  // Take some action if it failed?
end;

end.
```

I have also tested this using no completion handler, i.e:

```delphi
  TOSDevice.OpenURL('https://www.embarcadero.com');
```

**Comment by maurobotta** [comment]
Is a iOS 18 Bug ?
https://github.com/pointfreeco/swift-dependencies/issues/220


This link work fine :)
https://github.com/DelphiWorlds/HowTo/tree/main/Demos/OpenURL

**Comment by DelphiWorlds** [comment]
> Is a iOS 18 Bug ?

No, the change was intentional
