### ISSUE TITLE
FCMRebooted: DeveloperToolsSupport still required for Firebase iOS SDK 10.8.0 on Delphi 12.2

### ISSUE THREAD

**Issue by alexsawers** [DelphiWorlds/Kastri#257]
**Description**
The readme for the [FCMRebooted demo](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FCMRebooted) reads:

> If you choose Firebase iOS SDK 11.2.0, will need to add:
> - DeveloperToolsSupport

So when working with Firebase 10.8.0 its assumed that by importing `CoreTransferable`, `SwiftUI` and `SwiftUICore` should be enough, however when building the iOS app it fails at linking phase.

**Error messages**
If the `DeveloperToolsSupport` framework is not imported for Firebase 10.8.0 the iOS app build fails with:

`[DCC Error] E2597 ld: file not found: /System/Library/Frameworks/DeveloperToolsSupport.framework/DeveloperToolsSupport for architecture arm64`

**Please indicate**
Delphi Version: 12.2
Platform(s) that the issue occurs on (i.e. iOS, Android etc): iOS

This was tested with iOS 17.5, XCode 15.4. As a side note I can't remember importing `DeveloperToolsSupport` on Delphi 12.1, so this could be a perk with the updated linker on Delphi 12.2.

**Comment by DelphiWorlds** [comment]
I've updated the readme. Thanks, Alex!
