### ISSUE TITLE
FConnectivity stopped working in latest version

### ISSUE THREAD

**Issue by alpires** [DelphiWorlds/Kastri#26]
Hi, I download the latest version to fix the notification bug, but now TConnectivity has stopped working. 
When I create the object with "FConnectivity := TConnectivity.create;" the app freezes. 
I tested the demo and freezes too. No error message appears, only the app freezes.
I am using Delphi 10.3.3
Some idea?
Thanks

**Comment by DelphiWorlds** [comment]
Please indicate which platform, and what version of that platform

**Comment by alpires** [comment]
Android 10 with sdk 29

**Comment by DelphiWorlds** [comment]
Connectivity feature now requires dw-kastri-base.jar to be added to the Libraries node of the Android target in Project Manager. I've updated the demo
