### ISSUE TITLE
file not found GTMSessionFetcher

### ISSUE THREAD

**Issue by Gebhard-AddIn** [DelphiWorlds/Kastri#262]
I am using the current Delphi version 12.2 with update 1. 
This linker error is displayed when compiling for iOS:
[DCC Error] E2597 ld: file not found: GTMSessionFetcher
[DCC Fatal error] F2588 Linker error code: 1 ($00000001)
Do you have any advice on what to do here? 
The file libGTMSessionFetcher.a is located in the directory \Documents\GitHub\Kastri\ThirdParty\iOS. Everything looks correct. The zip files for Firebase.6.18.0 and for the MLKitBarcodeScanning.framework are unpacked.

**Comment by DelphiWorlds** [comment]
Are you compiling your own project or a demo? If a demo, I assume that it's the [Barcode Reader demo](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/BarcodeReader)? If your own project, please show what values you have for Framework search path and Search path in the project options.

**Comment by Gebhard-AddIn** [comment]
Its my own project.

Framework path: 
C:\Users\gebhard.blank\Documents\GitHub\Kastri\ThirdParty;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\ThirdParty\iOS;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseMessaging

SearchPath:
C:\Users\gebhard.blank\Documents\GitHub\Kastri\Features\Barcode;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\ThirdParty\iOS\MLKitCommon.framework;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\API;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\Core;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\Include;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\Features\FilesSelector;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\Features\ShareItems;
C:\Users\gebhard.blank\Documents\GitHub\Kastri\Features\Firebase;
\\filedeveloper\Entwicklung\Entwicklung\Rad Studio XE12\Forschung\PocketReadBlueListe;
$(TMSREG)\TMS FNC UI Pack;$(TMSREG)\TMS FNC Core;
$(TMSREG)\TMS Cryptography Pack;
$(TMSREG)\TMS Cryptography Pack\libiOSDevice64;
\\filedeveloper\Entwicklung\Entwicklung\Rad Studio XE12\Forschung\PackageKalenderD12;
\\filedeveloper\Entwicklung\Entwicklung\Rad Studio XE12\Forschung\FGX-FireMonkey-master\Library;
\\filedeveloper\Entwicklung\Entwicklung\Rad Studio XE12\Forschung\FMX-ImageLayout-master;
\\filedeveloper\Entwicklung\Entwicklung\Rad Studio XE12\Forschung\PRBarCodeScanner;
\\filedeveloper\Entwicklung\Entwicklung\Rad Studio XE12\Forschung\TMSFMXZBarReader

**Comment by DelphiWorlds** [comment]
> C:\Users\gebhard.blank\Documents\GitHub\Kastri\ThirdParty\iOS\MLKitCommon.framework;

This does not need to be in the project search path, but it is missing: `C:\Users\gebhard.blank\Documents\GitHub\Kastri\ThirdParty\iOS`

**Comment by Gebhard-AddIn** [comment]
Thank you Dave for the quick reply.
Unfortunately, the error message still appears.

**Comment by DelphiWorlds** [comment]
Can you attach the .dproj file of the project here? You may need to zip file file in order to add it as an attachment.

**Comment by Gebhard-AddIn** [comment]
I compared my project with your barcode demo.
I was missing the Firebase iOS SDK 11.2.0.
I'm just finishing setting it up. Hope it works after that.
I will let you know then.

**Comment by Gebhard-AddIn** [comment]
Now I get this error:
[DCC Error] ld: file not found: /usr/lib/swift/libswift_Concurrency.dylib
[DCC Fatal error] Linker error code: 1 ($00000001)

The same Error on your BarcodeDemo.
Do I have to add anything on the Mac side or XCode?

Attached the dproj file.
[pocketBLUE.zip](https://github.com/user-attachments/files/17798103/pocketBLUE.zip)

**Comment by DelphiWorlds** [comment]
I missed some importation [information in the Readme regarding Swift Compatibility libraries](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/BarcodeReader#swift-compatibility-libraries), which I have now added.

**Comment by Gebhard-AddIn** [comment]
Thank you. its compiling now!
