### ISSUE TITLE
[BarcodeReader] FBLPromises library not loaded

### ISSUE THREAD

**Issue by Ztaclie** [DelphiWorlds/Kastri#263]
**Description**
i am using BarcodeReader with FCM i followed steps of readme in demo and successfully created working project with firebase and barcodereader. but when i tried to active camera even i gave permission. it crashes app immedietly. while trying to solve this issue i changed GoogleService-Info.plist in Deployment. Now app crashes on startup. i changed back to previous GoogleService-Info.plist still crashes on startup. when i looked into MacOS Console for logging i came cross this error attached to this link: `https://drive.google.com/file/d/10efZGm5OMC6st5hM_HaW5qbuYVUHhi8O/view?usp=sharing`

when i asked this issue to Embarcadero support they said:
**The library should be statically linked but the app is looking for a dylib. FBLPromises looks to be one of the frameworks from Kastri. You should ask Dave Nottage how to link it statically**

**Error messages**
FBLPromises library not loaded

**Please indicate**
Delphi Version: 12.2
IOS 18.1

**Comment by DelphiWorlds** [comment]
The implementation in Kastri links everything statically. Perhaps there is some other code in your app that needs to load it dynamically. Without seeing your code, I would not be able to tell.

**Comment by Ztaclie** [comment]
i deleted this project i will gonna start with new demo project and then gonna provide you.
