### ISSUE TITLE
[BarcodeReader] + [FirebaseMessaging] Compitiblity issue

### ISSUE THREAD

**Issue by Ztaclie** [DelphiWorlds/Kastri#264]
# Tried to run PushNotif with BarcodeReader
i created a demo project for BarcodeReader with FirebaseMessaging. In this project firstly i got a few errors.

## Noticed
With 6.28.0 it raises duplicate symbol '_OBJC_CLASS_$_PodsDummy_nanopb' and duplicate symbol '_OBJC_METACLASS_$_PodsDummy_nanopb'
With 10.8.0 it raises File Not Found: PromisesObjC
With 11.2.0 it raises File Not Found: PromisesObjC
With 11.5.0 it raises File Not Found: PromisesObjC

## Steps i do
i did read readme file in barcorereader demo. i did the neccessery steps:

- [x] Conditional Defines:
- [x] Framework Search Path
- [x] Search Path
- [x] Minimum IOS Version Supported
- [x] Options passed to the LD Linker
- [x] Deployment has GoogleService-Info.plist 
- [x] CFBundleIdentifier and Provisioning Profile matches

## Demo Project Link
i added tested firebase versions and kastri to demo folder.
[Download From Google Drive](https://drive.google.com/file/d/13uUo8dFnH72cOG2_Twvxq-PcGfH15oGP/view?usp=sharing)

## Tech
Delphi: 12.2
IOS SDK: 18.1 with a few frameworks added
frameworks: AVKit,CoreMotion,MultipeerConnectivity,Social,GameController,VideoToolbox

**Comment by Ztaclie** [comment]
i got it. but i did use v10.8 within this project still raised "file not found PromisesObjC". i did all the steps in readme file.

**Comment by DelphiWorlds** [comment]
> but i did use v10.8 within this project

Using the built-in FCM support, or using the Kastri FCM support? As I mentioned in my last reply, it will probably not work with the built-in FCM support, which is what the project you linked to uses.

**Comment by Ztaclie** [comment]
aah you mean insted of FMX.PushNotification.IOS or FMX.PushNotification.Android i should use libraries in the Features/Notification and Features/Firebase

**Comment by DelphiWorlds** [comment]
Yes, see [this demo](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FCMRebooted).

**Comment by Ztaclie** [comment]
i see let me try it thanks for quick reply

**Comment by Ztaclie** [comment]
### **Issue Summary**

After integrating and patching with **FCMRebooted**, including modifications to `FMX.PushNotification.iOS` and changes to library usage, I successfully linked the app and deployed it to a physical iOS device. However, I am encountering two critical issues:

1. **Camera Crash**  
   - When I click the "Scan" button to activate the camera, it opens for a split second, briefly displays the view (in the wrong rotation), and then crashes the app instantly.  
   - I followed all steps in the README file to address the camera issue, but the problem persists.

2. **Device Token Retrieval for iOS**  
   - I am currently unable to retrieve the device token for iOS.  
   - I haven't thoroughly investigated this issue yet, as my focus has been on resolving the camera crash.

---

### **Steps Taken to Address the Camera Crash**

- Rechecked the implementation against the README documentation.
- Verified the patch and library changes were applied correctly.

Despite these efforts, the issue remains unresolved.

---

### **Request**

- Guidance on debugging the **camera crash** issue (potential causes or additional steps to troubleshoot).  
- Support or recommendations for retrieving the **iOS device token** once the camera issue is addressed.

**Comment by Ztaclie** [comment]
Hi,

I followed the steps, and after commenting out the lines mentioned, the camera worked as expected. The rotation angle was correct, and the camera feed was clear. However, when I uncomment the following line:


`FReader.Scan(FSectionBitmap);`

the application crashes.

Regarding the iOS device token, I went through the troubleshooting steps yesterday but couldn’t retrieve the token at that time. Interestingly, the device did receive the token today. This might have been due to caching or a similar issue, as both my Windows and Mac computers were restarted last night.

Once I resolve the scanning crash, I plan to look into Android support as well.

Thank you for your help! What steps can I take to address this crash? Here is how I’ve initialized FReader in the FormCreate event:


```
if FSectionBitmap = nil then
  FSectionBitmap := TBitmap.Create;
if FReader = nil then
begin
  FReader := TBarcodeReader.Create;
  FReader.Formats := [TBarcodeFormat.All];
  FReader.OnBarcode := ReaderBarcodeHandler;
end;
```

Looking forward to your guidance!

**Comment by DelphiWorlds** [comment]
Do you have an updated demo that reproduces the crash?

**Comment by Ztaclie** [comment]
Of course here is link:

[Download From Drive](https://drive.google.com/file/d/19Q_anCTekwPlWVOmXqoI1Mgb6HZFJLG9/view?usp=sharing)

also i did android support too but like on ios when i tried to scan. It crashes on android ass well.

**Comment by DelphiWorlds** [comment]
I've fixed the bug on iOS - a range check error on `barcodes.count - 1` in this routine (which is the fixed version):

```delphi
procedure TPlatformBarcodeReader.ScannerProcessImageCompletionHandler(barcodes: NSArray; error: NSError);
var
  LMLKBarcode: MLKBarcode;
  LBarcode: TBarcode;
  LBarcodes: TBarcodes;
  I: Integer;
  LError: string;
begin
  if error = nil then
  begin
    LError := '';
    if barcodes.count > 0 then
    begin
      for I := 0 to barcodes.count - 1 do
      begin
        LMLKBarcode := TMLKBarcode.Wrap(barcodes.objectAtIndex(I));
        LBarcode.Value := NSStrToStr(LMLKBarcode.displayValue);
        LBarcode.Format := GetBarcodeFormat(LMLKBarcode.format);
        LBarcodes := LBarcodes + [LBarcode];
      end;
    end;
  end
  else
    LError := NSStrToStr(error.localizedDescription);
  DoBarcodes(LBarcodes, LError);
end;
```
You'll need to synchronize Kastri to get the change.

On Android, you missed [this part of the configuration](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/BarcodeReader#manifest), i.e. the metadata entry

**Comment by Ztaclie** [comment]
Hi,

i tried it on both ios and android it worked like a charm. Thanks a lot for helping me solve this issue together.

**Comment by DelphiWorlds** [comment]
> Thanks a lot for helping me solve this issue together.

Thank you for highlighting that there was something to fix!
