### ISSUE TITLE
[AppReview] Compatibility with Delphi 12.2 [Add play-core-1.10.0.jar]

### ISSUE THREAD

**Issue by marlonnardi** [DelphiWorlds/Kastri#267]
Add play-core-1.10.0.jar

[DW.AppReview](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/AppReview)

IOS = OK
Android = Fail

![image](https://github.com/user-attachments/assets/dba13dfa-8494-4a34-9f17-d9a75a19dac1)

Simple Code:

uses -> DW.AppReview;
code -> AppReview.RequestReview;

Google Play
https://play.google.com/store/apps/details?id=br.com.falconsistemas.financas
Apple Store
https://apps.apple.com/br/app/falcon-finan%C3%A7as/id1474465261?platform=iphone

**Comment by DelphiWorlds** [comment]
It's literally telling you what the problem is. See [here](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/AppReview#java-libraries).

**Comment by marlonnardi** [comment]
![image](https://github.com/user-attachments/assets/52b8dae6-4e8e-449d-88da-d4b1373adda3) sorry, rsrsrs

This can't have happened, I missed it.

Thanks
