### ISSUE TITLE
Connectivity feature now requires dw-kastri-base.jar

### ISSUE THREAD

**Issue by alpires** [DelphiWorlds/Kastri#27]
OK, I put dw-kastri-base.jar in demo and it worked, but not in my app (my app already uses dw-kastri-base.jar). In my app TConnectivity is created in a background service and it's just not working on the latest version.

Connectivity feature now requires dw-kastri-base.jar to be added to the Libraries node of the Android target in Project Manager. I've updated the demo

_Originally posted by @DelphiWorlds in https://github.com/DelphiWorlds/Kastri/issues/26#issuecomment-730025351_

**Comment by DelphiWorlds** [comment]
I've marked this as "question" because I have it working in an app where an instance of TConnectivity is created in a service. 

Please describe what you mean by "just not working", and possibly provide a test project which demonstrates the issue.

**Comment by alpires** [comment]
In OnCreate event of my service I put:

```
  if FConnectivity = nil then
  begin
    FConnectivity := TConnectivity.create;
    FConnectivity.OnConnectivityChange := ConnectivityChangeHandler;
  end;
```
When the host app execute TServiceCommander.StartService(cServiceName); the application just freezes, I can't even minimize the application in my phone. if I remove these lines, the application works perfectly.

**Comment by DelphiWorlds** [comment]
Try setting the `OnConnectivityChange` handler in the `OnStartCommand` event of the service instead of `OnCreate`

**Comment by alpires** [comment]
Very strange, if I put only FConnectivity := TConnectivity.create; in OnStartCommand my app freezes, but I put the same line in CrossPlatformLocation demo and works. I will investigate further and give you a feedback.

**Comment by alpires** [comment]
In debug mode I get this error: Project myproject.apk raised exception class EJNIException with message 'java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader java.lang.Class.getClassLoader()' on a null object.

Any tips?

**Comment by DelphiWorlds** [comment]
Seems like you may be adding the .jar to the service, rather than to the application.

**Comment by alpires** [comment]
Well, I clean service and host, rebuild them and add .jar again. Now works 👍 
Thanks
