### ISSUE TITLE
[Camera] Handled null exception (iOS)

### ISSUE THREAD

**Issue by valberhcustodio** [DelphiWorlds/Kastri#272]
If your issue is for a particular feature (e.g. Camera, Connectivity, Biometric etc), please prefix the issue title with the feature in square brackets, e.g. "[Camera] Crash when image is captured"

**Description**
I am running the CameraDemoD12 app on iPhone 13, iPhone 13 Pro Max and iPhone 14 Pro Max.
On iPhone 13 and 13 ProMax there was no problem.
On iPhone 14 ProMax we received the following error: Handled null exception.
On all devices we are running OS version 18.1.1.

**Error messages**
![image](https://github.com/user-attachments/assets/ab49ae91-abfd-4491-8181-856fe89a1f9e)

**Please indicate**
Delphi Version: 12.2 Update 2
Platform(s) that the issue occurs on (i.e. iOS, Android etc): iOS
If mobile, device model and OS version (e.g. Pixel 3a, Android 11):  18.1.1

**Steps To Reproduce**
Run the CameraDemo12 app and touch on button Start.

**Comment by DelphiWorlds** [comment]
Did the app ever get to the point of requesting permission to access the camera? This is so I know where in the code to look. Meanwhile, the demo works OK on my iPhone 15 with iOS 18.1.1, so I'm assuming it's an issue with a specific model.

**Comment by DelphiWorlds** [comment]
Can you pull the recent changes from the Kastri repo and retry? If it does not crash, but you see no video, it means either you denied permission, or the OS is not allowing access to any video devices for some other reason.

**Comment by DelphiWorlds** [comment]
I've just pushed a couple more changes, based on a report from another user - can you try them out?

**Comment by valberhcustodio** [comment]
The problem still happens the same way.

**Comment by valberhcustodio** [comment]
Great!!!!
This problem was solved!
Thanks a lot!!!
