### ISSUE TITLE
TConnectivity strange behavior

### ISSUE THREAD

**Issue by alpires** [DelphiWorlds/Kastri#29]
Hi, I downloaded the latest version of kastri but I am having a strange behavior in the TConnectivity component. if I disconnect the wifi only, the component already says that it has no internet connection, if I reconnect it says it is connected and then immediately shows that it is disconnected, this did not happen in previous versions. (tested on ConnectivityDemo app). See the attachment.
![TConnect](https://user-images.githubusercontent.com/6544557/99825312-a1a2e380-2b35-11eb-8c87-0f51cd1476e5.png)

**Comment by DelphiWorlds** [comment]
Odd. Mine is firing the disconnect event, but not the connect. I'm taking a look at it

**Comment by DelphiWorlds** [comment]
What device do you have, and what version of Android?

**Comment by alpires** [comment]
I have a xiaomi redmi 8 with Android 10

**Comment by DelphiWorlds** [comment]
Storing a couple of links for possible explanations/solutions:

https://stackoverflow.com/questions/61773466/android-communicate-with-mobile-data-while-connected-to-wifi-without-internet-a
https://www.366service.com/jp/qa/effab059a5e063bc4dfc9aa87e129e64 (might need to use specific types in the request)

**Comment by alpires** [comment]
The strange thing is that in an old version of kastri, it was working perfectly in my device.

**Comment by DelphiWorlds** [comment]
I could change it so that you can select the "old" way. The change was introduced due to API deprecations

**Comment by alpires** [comment]
I will remove the OnConnectivityChange event from my project, I think it's better.
