### ISSUE TITLE
TConnectivity is not detecting bridged internet connection from within Virtual Machine

### ISSUE THREAD

**Issue by stuartclennett** [DelphiWorlds/Kastri#3]
Environment: Delphi 10.3.2,  VMWare Workstation Pro 15.5.1,  Windows 10 on both guest and host. 

Open ConnectivityDemo and run (win32) & result is "Device is NOT connected to the internet".

**Comment by DelphiWorlds** [comment]
Labeled as enhancement since Windows is not supported with the Connectivity feature

**Comment by DelphiWorlds** [comment]
Added Windows support
