### ISSUE TITLE
ScheduledServiceDemo

### ISSUE THREAD

**Issue by barnisoft** [DelphiWorlds/Kastri#32]
Hi there, Can you help me please! I want uese the ScheduledDemo, but when start run the app, the app closed! I want to use this on the Android64 bit. I did try this on Android32 bit too, but after one time this closed too. I did downloaded the refresh too, but not working! Sorry that I little bit speak English! Thank you so much help and your time!

**Comment by DelphiWorlds** [comment]
Which version of Delphi are you using?

**Comment by barnisoft** [comment]
I use the delphi 10.4.1

**Comment by barnisoft** [comment]
I use the delphi 10.4.1

**Comment by barnisoft** [comment]
Hi there! How to import Java code in delphi 10.4.1 android 64bit, (DWMultiBroadcastReceiver.java)? Help me please!

**Comment by barnisoft** [comment]
This Now is Good! ;) Thank You so Much this code!
