### ISSUE TITLE
Make kastri work with MQTT - The Standard for IoT Messaging 

### ISSUE THREAD

**Issue by RaySa74** [DelphiWorlds/Kastri#35]
it will be great if kastri work with  MQTT - The Standard for IoT Messaging.

thanks

**Comment by DelphiWorlds** [comment]
Can you be more specific about how Kastri should work with MQTT? Kastri covers a pretty broad spectrum of aspects of coding

**Comment by DelphiWorlds** [comment]
Closed due to no feedback received
