### ISSUE TITLE
the  SubscribeToTopic  of  TFirebaseMessaging function gets an error ?

### ISSUE THREAD

**Issue by systrader** [DelphiWorlds/Kastri#37]
When i try to use the SubscribeToTopic feature,  raised exception 'Invoke error: method not found'.
Both versions 10.3.3 and 10.4.1 get the same error
What's the problem?

**Comment by DelphiWorlds** [comment]
When reporting a bug, please use the template provided when providing information.

It is important to know which platform, for instance i.e Android or iOS

**Comment by DelphiWorlds** [comment]
I've updated DW.Androidapi.JNI.Firebase, which should solve the problem:

https://github.com/DelphiWorlds/Kastri/commit/b72ff2625a67a2e149f5c82df3ce52b39952643f

**Comment by systrader** [comment]
thnank you
