### ISSUE TITLE
CrossPlatformLocation demo from google play

### ISSUE THREAD

**Issue by alpires** [DelphiWorlds/Kastri#38]
Hi, I made an application with a background service (based on the CrossPlatformLocation demo), when I install the apk directly from delphi 10.3 Rio it works perfectly, however if I install from google play the service not start. Any idea what might be going on?

**Comment by DelphiWorlds** [comment]
Please make sure you have applied this patch: https://cc.embarcadero.com/item/30905

**Comment by alpires** [comment]
Thnaks, do you know if it works in delphi 10.4.1?

**Comment by DelphiWorlds** [comment]
The patch is not required in Delphi 10.4.1. About your specific case, I don't know - it could be failing for some other reason

**Comment by alpires** [comment]
I am using delphi 10.3 but I will try to use it in 10.4.1 version.
Thanks

**Comment by alpires** [comment]
Worked in version 10.4.2
Thanks
