### ISSUE TITLE
Can fingerprint authentication return a consistent signature for an identified finger?

### ISSUE THREAD

**Issue by darnocian** [DelphiWorlds/Kastri#4]
Very nice project. I discovered it fairly recently. I was playing with the fingerprint authentication. 

With the fingerprint authentication, I can see it returns success if the fingerprint matches a finger that is registered on the device. If there are multiple fingers registered, it may be useful to identify which one was used.

I plan to dig into this at some stage. I realise it is probably different between IOS and Android, but presume there may be some sort of hash on both.

**Comment by DelphiWorlds** [comment]
"If there are multiple fingers registered, it may be useful to identify which one was used"

Simple answer: not possible.

Longer answer - please refer to these links:

https://android.developreference.com/article/15300105/Limit+Android+to+use+one+single+fingerprint+for+authentication
https://blog.torib.io/2019/04/11/adding-fingerprint-authentication-on-xamarin-forms/
https://stackoverflow.com/questions/30546870/how-to-get-finger-id-which-finger-is-used-for-touch-id-or-unique-touch-id-on

**Comment by darnocian** [comment]
Thanks for the instant response and interesting reference links.
