### ISSUE TITLE
[Connectivity] Android not detecting reconnect network

### ISSUE THREAD

**Issue by Spelt** [DelphiWorlds/Kastri#40]
Hi

I think I found a problem:

Delphi Version: 10.4.2.
Platform(s) that the issue occurs on: Android 10, Pixel3a

When starting the connectivity demo it writes:

'Device is connected via the Internet via wifi.'   Great.

Disable wifi:
' Disconnected!'. Great.

Enable wifi:
nothing. 

**Error messages**
No Error messages,

**Comment by DelphiWorlds** [comment]
I confirm the behaviour, and am looking into it

**Comment by DelphiWorlds** [comment]
[Added a small delay for the check](https://github.com/DelphiWorlds/Kastri/commit/df2fadc75b951cef486aadd45f5b535961a6e767#diff-8655b9817cf0dea771ea8997c7b5c3edbeb3bdafd1c38d6bcb4b9e4d57d83663) when the network becomes available. Please let me know how it goes

**Comment by Spelt** [comment]
It works. Thanks.
