### ISSUE TITLE
NativeShape + Stroke

### ISSUE THREAD

**Issue by kazuser** [DelphiWorlds/Kastri#41]
Thanks for NativeShape! 👍 

A little problem — stroke is hidden in DesignTime:

![screencast](https://user-images.githubusercontent.com/3335273/118022439-2f8db780-b37e-11eb-868f-e0f97847451e.gif)

but still visible in RunTime
![screenshot](https://user-images.githubusercontent.com/3335273/118022381-243a8c00-b37e-11eb-9234-376419adc516.png)

**Comment by DelphiWorlds** [comment]
Fixed in https://github.com/DelphiWorlds/Kastri/compare/d0dcdd34c2ef...efb7222012b2

Note: Only basic support for Stroke at the moment. I'll update the docs to reflect this
