### ISSUE TITLE
iOS NFC demo compile fails  if not on Simulator

### ISSUE THREAD

**Issue by HassoEccard** [DelphiWorlds/Kastri#44]
If your issue is for a particular feature (e.g. Camera, Connectivity, Biometric etc), please prefix the issue title with the feature in square brackets, e.g. "[Camera] Crash when image is captured"

Compile error of NFC demo on iOS - not on Simulator
Compiling the NFC demo on iOS Device 64 Development or Application Store, an error occurred.
It builds fine on iOS Simulator

Error messages
[DCC Error] E2597 Id: file not found: /System/Library/Frameworks/CoreNFC.framework/CoreNFC

**Please indicate**
Delphi Version: 10.4.2

Platform(s) that the issue occurs on (i.e. iOS, Android etc):
iOS

Steps To Reproduce
1. Load the NFC demo
2. Select iOS Device 64 bit
3. Select Application Store of Development
4. Build all.

**Comment by DelphiWorlds** [comment]
You need to import the CoreNFC framework into the iOS SDK, in the Delphi SDK Manager. Please refer to [this article](https://delphiworlds.com/2013/10/adding-other-ios-frameworks-to-the-sdk-manager/)
