### ISSUE TITLE
Camera sample for iOS missing Vision framework

### ISSUE THREAD

**Issue by manuelspataro** [DelphiWorlds/Kastri#45]
If your issue is for a particular feature (e.g. Camera, Connectivity, Biometric etc), please prefix the issue title with the feature in square brackets, e.g. "[Camera] Crash when image is captured"

**Description**
Brief description of the issue:

**Error messages**
If any. Please ensure they are the **exact** message(s):

**Please indicate**
Delphi Version:
Platform(s) that the issue occurs on (i.e. iOS, Android etc):
If mobile, device model and OS version (e.g. Pixel 3a, Android 11): 

**Steps To Reproduce**
Concise steps to reproduce the behaviour:

**Comment by manuelspataro** [comment]
Hi, 
I am compiling camera sample on ios. I am using Rad Studio 10.4.2, XCode 12.5 but linker raise an error : 
[DCC Error] E2597 ld: file not found: /System/Library/Frameworks/Vision.framework/Vision.
This framework is mission in my iOS sdk and in Kastrimaster.zip.
Can you help me ? Where I can found this library ? Seems in XCode 12.5 is missing or I have not found in my XCode folders.

Thanks.

**Comment by DelphiWorlds** [comment]
Hi Manuel,

You need to add the Vision framework manually. [This article](https://delphiworlds.com/2013/10/adding-other-ios-frameworks-to-the-sdk-manager) shows how to add other frameworks to the imported SDK in Delphi.
