### ISSUE TITLE
FCMDemo (Firebase Cloud Messaging) [DCC Error] E2597 ld: warning: directory not found for option '-L\FirebaseAnalytics\FirebaseAnalytics.framework'   

### ISSUE THREAD

**Issue by thebugger2000** [DelphiWorlds/Kastri#46]
Hi there!

I Just installed the Kastri.  
Added the files to the library path from the demo video: https://www.youtube.com/watch?v=yp6Ds7umkbU
I Went straight to the FCMDemo
[DCC Error] E2597 ld: warning: directory not found for option '-L\FirebaseAnalytics\FirebaseAnalytics.framework'

I feel like I might be missing a library install.  I skimmed the readme and didn't see anything.

These is the message Log:

dcciosarm64 command line for "FCMDemo.dpr"
  c:\program files (x86)\embarcadero\studio\21.0\bin\dcciosarm64.exe -$O- --no-config -M -Q -AGenerics.Collections=System.Generics.Collections;
  Generics.Defaults=System.Generics.Defaults -DDEBUG -E.\iOSDevice64\Debug -I"c:\program files (x86)\embarcadero\studio\21.0\lib\iOSDevice64\debug";
  \FirebaseAnalytics\FirebaseAnalytics.framework;\FirebaseAnalytics\FirebaseCore.framework;\FirebaseAnalytics\FirebaseCoreDiagnostics.framework;
  \FirebaseAnalytics\FirebaseInstallations.framework;\FirebaseAnalytics\GoogleAppMeasurement.framework;\FirebaseAnalytics\GoogleDataTransport.framework;
  \FirebaseAnalytics\GoogleUtilities.framework;\FirebaseAnalytics\nanoPB.framework;\FirebaseAnalytics\PromisesObjC.framework;
  \FirebaseMessaging\FirebaseInstanceID.framework;\FirebaseMessaging\FirebaseMessaging.framework;\FirebaseMessaging\Protobuf.framework;..\..\API;
  ..\..\Core;..\..\Include;..\..\Features\Firebase;..\..\Features\Notifications;"c:\program files 
  (x86)\embarcadero\studio\21.0\lib\iOSDevice64\Release" -LEC:\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl\iOSDevice64 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp\iOSDevice64 -NU.\iOSDevice64\Debug -NSSystem;Xml;Data;Datasnap;Web;Soap; 
  -O\FirebaseAnalytics\FirebaseAnalytics.framework;\FirebaseAnalytics\FirebaseCore.framework;\FirebaseAnalytics\FirebaseCoreDiagnostics.framework;
  \FirebaseAnalytics\FirebaseInstallations.framework;\FirebaseAnalytics\GoogleAppMeasurement.framework;\FirebaseAnalytics\GoogleDataTransport.framework;
  \FirebaseAnalytics\GoogleUtilities.framework;\FirebaseAnalytics\nanoPB.framework;\FirebaseAnalytics\PromisesObjC.framework;
  \FirebaseMessaging\FirebaseInstanceID.framework;\FirebaseMessaging\FirebaseMessaging.framework;\FirebaseMessaging\Protobuf.framework;..\..\API;
  ..\..\Core;..\..\Include;..\..\Features\Firebase;..\..\Features\Notifications;"c:\program files 
  (x86)\embarcadero\studio\21.0\lib\iOSDevice64\Release" -R\FirebaseAnalytics\FirebaseAnalytics.framework;\FirebaseAnalytics\FirebaseCore.framework;
  \FirebaseAnalytics\FirebaseCoreDiagnostics.framework;\FirebaseAnalytics\FirebaseInstallations.framework;
  \FirebaseAnalytics\GoogleAppMeasurement.framework;\FirebaseAnalytics\GoogleDataTransport.framework;\FirebaseAnalytics\GoogleUtilities.framework;
  \FirebaseAnalytics\nanoPB.framework;\FirebaseAnalytics\PromisesObjC.framework;\FirebaseMessaging\FirebaseInstanceID.framework;
  \FirebaseMessaging\FirebaseMessaging.framework;\FirebaseMessaging\Protobuf.framework;..\..\API;..\..\Core;..\..\Include;..\..\Features\Firebase;
  ..\..\Features\Notifications;"c:\program files (x86)\embarcadero\studio\21.0\lib\iOSDevice64\Release" -U"c:\program files 
  (x86)\embarcadero\studio\21.0\lib\iOSDevice64\debug";\FirebaseAnalytics\FirebaseAnalytics.framework;\FirebaseAnalytics\FirebaseCore.framework;
  \FirebaseAnalytics\FirebaseCoreDiagnostics.framework;\FirebaseAnalytics\FirebaseInstallations.framework;
  \FirebaseAnalytics\GoogleAppMeasurement.framework;\FirebaseAnalytics\GoogleDataTransport.framework;\FirebaseAnalytics\GoogleUtilities.framework;
  \FirebaseAnalytics\nanoPB.framework;\FirebaseAnalytics\PromisesObjC.framework;\FirebaseMessaging\FirebaseInstanceID.framework;
  \FirebaseMessaging\FirebaseMessaging.framework;\FirebaseMessaging\Protobuf.framework;..\..\API;..\..\Core;..\..\Include;..\..\Features\Firebase;
  ..\..\Features\Notifications;"c:\program files (x86)\embarcadero\studio\21.0\lib\iOSDevice64\Release" 
  --syslibroot:C:\Users\Linda\Documents\Embarcadero\Studio\SDKs\iPhoneOS14.5.sdk 
  --frameworkpath:C:\Users\Linda\Documents\Embarcadero\Studio\SDKs\iPhoneOS14.5.sdk\System\Library\Frameworks;
  C:\Users\Linda\Documents\Embarcadero\Studio\SDKs\iPhoneOS14.5.sdk\System\Library\PrivateFrameworks -V -VN --linker-option:"-ObjC -arch arm64" 
  -NO.\iOSDevice64\Debug  FCMDemo.dpr   
[DCC Error] E2597 ld: warning: directory not found for option '-L\FirebaseAnalytics\FirebaseAnalytics.framework'
  ld: warning: directory not found for option '-L\FirebaseAnalytics\FirebaseCore.framework'
  ld: warning: directory not found for option '-L\FirebaseAnalytics\FirebaseCoreDiagnostics.framework'
  ld: warning: directory not found for option '-L\FirebaseAnalytics\FirebaseInstallations.framework'
  ld: warning: directory not found for option '-L\FirebaseAnalytics\GoogleAppMeasurement.framework'
  ld: warning: directory not found for option '-L\FirebaseAnalytics\GoogleDataTransport.framework'
  ld: warning: directory not found for option '-L\FirebaseAnalytics\GoogleUtilities.framework'
  ld: warning: directory not found for option '-L\FirebaseAnalytics\nanoPB.framework'
  ld: warning: directory not found for option '-L\FirebaseAnalytics\PromisesObjC.framework'
  ld: warning: directory not found for option '-L\FirebaseMessaging\FirebaseInstanceID.framework'
  ld: warning: directory not found for option '-L\FirebaseMessaging\FirebaseMessaging.framework'
  ld: warning: directory not found for option '-L\FirebaseMessaging\Protobuf.framework'
  ld: file not found: Protobuf

**Comment by DelphiWorlds** [comment]
The readme says:

"iOS
Unzip the latest Firebase SDK in the ThirdParty\Firebase\iOS folder of Kastri"

Have you done that?

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
