### ISSUE TITLE
ios app crashes after FPushNotifications.Start

### ISSUE THREAD

**Issue by jtrejodarkness** [DelphiWorlds/Kastri#47]
Hello,
until yesterday nerly 5pm everythings working ok with the push notifications on my IOS App. Before that, the app crashes when the FPushNotifications.Start.
If comment this line, works correctly.

Debuging the app, the compiler works fine until the line FServiceConnection.Active:= True; in DW.PushNotification.pas unit

procedure TPushNotifications.CreateConnection;
var
  LPushService: TPushService;
begin
  Try
    LPushService := GetPushService;
    FServiceConnection := TPushServiceConnection.Create(LPushService);
    FServiceConnection.Active := True;   <----  
 
Can anybody help me??

**Comment by DelphiWorlds** [comment]
When reporting an issue, please follow the template given, i.e. provide the version of Delphi you are using etc. Also indicate when you last updated the files from Kastri

**Comment by jtrejodarkness** [comment]
Sorry it's my first time...

Delphi 10.4.2

Kastri I downloaded in January'21 and works fine until yesterdar... today I download again and try but still crashing

**Comment by jtrejodarkness** [comment]
This is the errors when execute FServiceConnection.Active := True;

Exception EAccessViolation in module <unknown> at 0000000000000000. Process HVM (396)
Access violation at address 0000000000000000, accessing address 0000000000000000. Process HVM (396)
Exception EAccessViolation in module <unknown> at 0000000000000000. Process HVM (396)
Access violation at address 0000000000000000, accessing address 0000000000000000. Process HVM (396)
Runtime error 217 at 00000001009D0C00 Process HVM (396)
Runtime error 217 at 00000001009D0C00 Process HVM (396)

**Comment by jtrejodarkness** [comment]
I found the problem, I dont know why but when use a component using the unit FireDAC.Phys.SQLiteWrapper.Stat, throws the EAccessViolation exception on DW.PushNotificacion unit.
Removing the FireDAC unit everything its ok.

I'm interesting to know why this, but by the moment I wont use the component.
