### ISSUE TITLE
Problem "FirebaseCloudMessaging" Mobile iOS

### ISSUE THREAD

**Issue by zomorango** [DelphiWorlds/Kastri#48]
I successfully compile and run the FCMDemo on both ios and Android,
So I configure my project to work as in the FCMDemo, on Android everything is just fine, super cool,
But in iOS I cannot compile my app,  I got this error : **[DCC Error] E2597 ld: file not found: PromisesObjC**
If I compile the FCMDemo for iOS it works just as expected, which is great. :)

But I have the exact same search paths in my app and in the FCMdemo, Just made a copy-paste from the search path of the FCDemo to my App and still got the message when building for iOS.

Error : 
[DCC Error] E2597 ld: file not found: PromisesObjC

Delphi Version: 10.4.2
Occurs when trying to build for iOS  sdk 14.5

Regards
José

**Comment by DelphiWorlds** [comment]
Are you using the Firebase 6.18.0 SDK that is in the `ThirdParty\Firebase\iOS` folder of Kastri? 
Please show what value you have for `Search path` in the Project Options

**Comment by zomorango** [comment]
Hi, Yes I'm using the 6.18 SDK, As I Said the FCMdemo works fine,  but my project gives this error when in the final linking process.
this is the search path both the projects
`H:\DelphiTools\Kastri\API;H:\DelphiTools\Kastri\Core;H:\DelphiTools\Kastri\Include;H:\DelphiTools\Kastri\Features\Firebase;H:\DelphiTools\Kastri\Features\Notifications;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\FirebaseAnalytics.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\FirebaseCore.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\FirebaseCoreDiagnostics.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\FirebaseInstallations.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\GoogleAppMeasurement.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\GoogleDataTransport.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\GoogleUtilities.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\nanopb.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\PromisesObjC.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\PromisesObjC.framework\Modules;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseAnalytics\PromisesObjC.framework\Headers;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseMessaging\FirebaseInstanceID.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseMessaging\FirebaseMessaging.framework;H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0\FirebaseMessaging\Protobuf.framework;H:\DelphiTools\alcinoe_master_1042\source;H:\DelphiTools\alcinoe_master_1042\embarcadero\sydney\10_4_2\fmx;H:\DelphiTools\alcinoe_master_1042\embarcadero\sydney\10_4_2\rtl;H:\DelphiTools\alcinoe_master_1042\embarcadero\sydney\10_4_2\rtl\android;H:\DelphiTools\alcinoe_master_1042\embarcadero\sydney\10_4_2\rtl\ios;H:\DelphiTools\alcinoe_master_1042\embarcadero\sydney\10_4_2\rtl\win;$(BDS)\source\rtl;$(BDS)\source\rtl\common;$(BDS)\source\rtl\net;$(BDS)\source\fmx;$(BDS)\source\rtl\osx;$(BDS)\source\rtl\ios;H:\DelphiTools\TFrameStandSydney\TFrameStand-master\source;H:\DelphiTools\TFrameStandSydney\TFrameStand-master;H:\DelphiTools\TFrameStandSydney\TFrameStand-master\lib;C:\Program Files (x86)\Embarcadero\Studio\21.0\source\databinding\components;C:\Program Files (x86)\Embarcadero\Studio\21.0\source\databinding\engine;C:\Program Files (x86)\Embarcadero\Studio\21.0\source\databinding\graph;C:\Program Files (x86)\Embarcadero\Studio\21.0\source\data\firedac;C:\Program Files (x86)\Embarcadero\Studio\21.0\source\data\rest;C:\Users\zemor\Documents\tmssoftware\TMS Cryptography Pack\libiOSDevice64;H:\DelphiTools\Kastri\ThirdParty\iOS`

**Comment by DelphiWorlds** [comment]
You do not need the `Headers` and `Modules` folders for the `PromisesObjC` framework in the search path, otherwise the paths look OK as long as H:\DelphiTools\Kastri\ThirdParty\Firebase\iOS\Firebase.6.18.0 actually exists and has the SDK files in it.

**Comment by zomorango** [comment]
I already remove the headers and modules folders from the path and the problem persists.....

Well, It's strange how the FCMDemo works and not my project, maybe its some kind of conflict with some other lib used on my project. Anyway thanks for the kind help and congrats for this wonderful Kastri project.

I'm using Alcinoe on my project maybe is some kind of incompatibility,

**Comment by DelphiWorlds** [comment]
It could be a conflict with Alcinoe - please check if it has units that link `PromisesObjC` - it might be using a path that it cannot find?

**Comment by zomorango** [comment]
Yes good idea, this is what I'm gone to do tomorrow, I will then give some feedback 
Thanks for the help

**Comment by zomorango** [comment]
Hi Dave,
I finally made the linking work,  I was nothing to do with alcinoe it was an old  DW. pushnotifications reference of an old version of kastri-free that was declared in the uses list in one form of my project, I remove it and now it compiles ok. Time for testing :)

once again thanks for your help

**Comment by zomorango** [comment]
Hi Dave, 
Well after lots of testing I can only make the FCMdemo work correctly on iOS, 
I've created a new empty project,  add the same form of the FCMDemo on it, copy-paste all the search paths configurations from the FCMdemo to mine, added the googleService-info.plist to deployment, etc.. 

The projects are identicals and mine just crash as soon as it starts.  Don't know what more can I do....

**Comment by zomorango** [comment]
the project crashes at the
 FFCM := TFirebaseMessaging.Create;

**Comment by DelphiWorlds** [comment]
Please ensure that you follow all of the configuration instructions for Android as detailed here:
https://github.com/DelphiWorlds/Kastri/blob/master/Demos/FirebaseCloudMessaging/Readme.md
Particularly the section at the bottom

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
