### ISSUE TITLE
[Notifications] custom local notifications in android?

### ISSUE THREAD

**Issue by dkounal** [DelphiWorlds/Kastri#50]
I want to create a  Notification in an android application that shows the progress in uploading an image.

I have seen many styled, multiline with icons notifications in existing applications, having also controls like a progress bar. 
I delphi I can not even change the icon it is showed
Looking inside DW.Androidapi.JNI.Notification I noticed some functions in JNotification_Builder and I started thinking if this can do the the above.
Is it possible? Is there a demo of how to use it?
Thank you in advance

**Comment by Morrismx** [comment]
Why do you need local notifications to show upload progress?  You can use a progres bar or A Tcircle, etc.

**Comment by dkounal** [comment]
Because it will be used by a service

**Comment by DelphiWorlds** [comment]
You are correct in that you use JNotification_Builder. There's an [example in Java at this link](https://medium.com/@britt.barak/notifications-part-2-progress-indicator-2aa4cdea24c6)

**Comment by dkounal** [comment]
Thank you very much. I will read it.

**Comment by DelphiWorlds** [comment]
A very basic example of how you might implement it in Delphi:

```
unit Unit1;

interface

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,
  FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs, FMX.Controls.Presentation, FMX.StdCtrls,
  Androidapi.JNI.Support;

type
  TForm1 = class(TForm)
    Button1: TButton;
  private
    FProgressNotificationBuilder: JNotificationCompat_Builder;
    procedure CloseDownloadNotification;
    procedure UpdateDownloadNotification(const AText: string; const AProgress: Integer = -1); overload;
    procedure UpdateDownloadNotification(const AProgress: Integer); overload;
  public
    constructor Create(AOwner: TComponent); override;
  end;

var
  Form1: TForm1;

implementation

{$R *.fmx}

uses
  Androidapi.Helpers,
  DW.Android.Helpers;

const
  cNotificationID = 1;

constructor TForm1.Create(AOwner: TComponent);
begin
  inherited;
  FProgressNotificationBuilder := TJNotificationCompat_Builder.JavaClass.init(TAndroidHelper.Context, StringToJString('MyChannel'));
  FProgressNotificationBuilder.setContentTitle(StrToJCharSequence('Download'));
end;

procedure TForm1.UpdateDownloadNotification(const AText: string; const AProgress: Integer = -1);
begin
  // Just update the progress
  if not AText.IsEmpty then
    FProgressNotificationBuilder.setContentText(StrToJCharSequence(AText));
  FProgressNotificationBuilder.setProgress(100, AProgress, AProgress = -1);
  TAndroidHelperEx.NotificationManager.notify(cNotificationID, FProgressNotificationBuilder.build);
end;

procedure TForm1.UpdateDownloadNotification(const AProgress: Integer);
begin
  // Just update the progress
  UpdateDownloadNotification('', AProgress);
end;

procedure TForm1.CloseDownloadNotification;
begin
  TAndroidHelperEx.NotificationManager.cancel(cNotificationID);
end;
```

When the notification needs to be shown, call something like this:

`UpdateDownloadNotification('Downloading file xyz', 0)` (or use -1 if indeterminate)
 
 As progress continues:

`UpdateDownloadNotification(SomeValue)` (where SomeValue is the value of the progress)

NOTE: The above is untested as yet

**Comment by dkounal** [comment]
Thank you again, I will test it.

**Comment by DelphiWorlds** [comment]
I should have mentioned you will need to create a channel with the same ID ('MyChannel') or use an ID of an existing one

**Comment by dkounal** [comment]
I am in a hurry with the work and I have not yet had the time to check it and report. Please allow me 2-3 days more

**Comment by dkounal** [comment]
The above source needs in the initialiazation to set the small icon. if not, it gives an exception telling you that. I did for example: 
`FProgressNotificationBuilder.setSmallIcon(17301514); `
After that, it does not give an error, but it does not do anything at the same time. I will keep providing my progress. 
Thanks again

**Comment by dkounal** [comment]
From Device monitor I am getting when trying to show the notification:
07-10 14:46:07.197: W/Notification(22635): Use of stream types is deprecated for operations other than volume control
07-10 14:46:07.197: W/Notification(22635): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case

**Comment by dkounal** [comment]
I can confirm, IT WORKS. It was my fault with setting the channel that caused the problem.
Thank you a lot @DelphiWorlds

**Comment by dkounal** [comment]
TJapp_NotificationCompat_Builder is used in Delphi 11 instead of TJNotificationCompat_Builder

**Comment by many-play** [comment]
Can someone please tell me how to create and do the settings with the needed channel?

**Comment by DelphiWorlds** [comment]
> Can someone please tell me how to create and do the settings with the needed channel?

What problems are you having, exactly?

**Comment by many-play** [comment]
I want to use a progress in notification on android and try out the demo here with all the modification hints here.

But i dont know how to create a channel, or what was ment with using a existing.

**Comment by DelphiWorlds** [comment]
> But i dont know how to create a channel

[This is one way you can create a channel](https://docwiki.embarcadero.com/RADStudio/Athens/en/Using_Notifications#Creating_a_notification_channel) (without using direct Android API calls). The `Id` value is what needs to be used in the place of `MyChannel` in the code example I gave earlier.

**Comment by many-play** [comment]
Thx!
Didnt recognize that a channel means and works together with the dragged delphi component called "TNotificationCenter"

On samsung phone/tablets, during my app is copying/moving several files,
it will be closed by the system, when the app moves to background.
If i allow there background processes, i badly can not find my app in the list
for apps "never in standby".
On other systems Lenovo, Nothing, LG  it is working also in background without 
this Samsung issue.
Can i use this notification (like it is used by ghislers total comander) when his app
run into background and show permanently the progress integrated in the taskbar 
and not like your demo here as a short time popup?

my english is not so pretty....

**Comment by DelphiWorlds** [comment]
> Can i use this notification (like it is used by ghislers total comander) when his app
run into background

If you wish to use the notification for when the app is in the background, you would probably need to use a service to do the actual work of copying/moving the files - a little like the Download Service demo, [here](https://github.com/Embarcadero/RADStudio12Demos/tree/main/Object%20Pascal/Multi-Device%20Samples/Device%20Sensors%20and%20Services/DownloadServiceDemo).

**Comment by many-play** [comment]
Thanks i had view this demo earlier and will take a deeper look inside...
