### ISSUE TITLE
[FirebaseMessaging] DW.Firebase.Messaging needs TFirebaseMessaging.PushFailToRegisterMessageHandler procedure to be finished

### ISSUE THREAD

**Issue by thebugger2000** [DelphiWorlds/Kastri#51]
in DW.Firebase.Messaging

PushFailToRegisterMessageHandler currently is empty (no code). See below:

procedure TFirebaseMessaging.PushFailToRegisterMessageHandler(const Sender: TObject; const M: TMessage);
begin

end;

It would be nice if it would have either a event handler or if it was a protected virtual method or both;

I'm currently having trouble getting push notifications to work and I'm going to hook into this to see if I get more clarity about my issue.  So I was surprised to see it looks incomplete maybe?

Thank you for your attention

**Comment by DelphiWorlds** [comment]
Can you verify that this method is actually being called?

**Comment by thebugger2000** [comment]
Before I used Kastri, I had to hook into that manually to find out why things weren't working on iOS (I believe).

**Comment by DelphiWorlds** [comment]
[Added event for fail to register message](https://github.com/DelphiWorlds/Kastri/commit/aacc0db96957ea850abb7b407be5a0722462eb5a)
