### ISSUE TITLE
[Firebase] Notification doesn't work when App is in foreground

### ISSUE THREAD

**Issue by thebugger2000** [DelphiWorlds/Kastri#52]
Hey David,

I'm on Delphi 10.4.2:

with Kastri, everthing works fine on iOS, but on Android, I cannot get the Kastri demo app to receive the messages for push notifications, beep or sound alert a notification at the top when it receives a new notification unless I close it or put it in the background.  but I'm still not seeing the payload either way.

I read your article:
https://delphiworlds.com/2020/01/expanding-embarcaderos-fcm-implementation-revisited/#comment-10092

I also found 
https://firebase.google.com/docs/cloud-messaging/android/client#manifest

In which they want 
`<service
    android:name=".java.MyFirebaseMessagingService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service> `
 added to the AndroidManifest.xml file.

That doesn't seem to work either.

Is there something wrong with the Kastri Messaging Demo Application or some settings I may have missed?

Thank you in advance.

**Comment by DelphiWorlds** [comment]
There's an apparent problem with EMBT's implementation, as you've discovered. You might like to try with [this demo instead](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FirebaseCloudMessaging).

**Comment by DelphiWorlds** [comment]
In EMBT's implementation, if the app is in the foreground, it does not present a notification, however the payload is received. Is that what you mean, or are you not receiving the payload, either?

**Comment by thebugger2000** [comment]
Thanks for the quick reponse.  I was using you "Firebase Cloud Messaging (FCM) Demo".  It will register the app and topics just fine for the notifcations when its in the background or off, but I don't seem to be getting the "FCMMessageReceivedHandler" to work correctly

**Comment by thebugger2000** [comment]
Also what is your $(Firebase) setting in your envornment options?

**Comment by DelphiWorlds** [comment]
Regarding Android: In the Kastri FCM implementation, you need to send a "data" type message, as per [the instructions here](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FirebaseCloudMessaging).

Regarding iOS: If the demo uses $(Firebase) in the paths, then it will need to be set as a a User Override in the Environment Variables section of the IDE options. It should point to the root of Firebase iOS SDK 6.18. There is a ["cut down" version of the SDK here](https://github.com/DelphiWorlds/Kastri/blob/master/ThirdParty/Firebase/iOS/Firebase.6.18.0.zip).

**Comment by thebugger2000** [comment]
Thank you for the response:

IOS: I cloned your FCMDemo.dproj file settings and I used the SDK you recommend.  After removing the CFBundleResourceSpecification from the .dproj file from [this suggestion](https://developer.apple.com/forums/thread/64265) It will compile and run.  but now I get this error:
---------------------------
Debugger Exception Notification
---------------------------
Project AlertNotificationExample raised exception class EObjectiveC with message 'ObjectiveC class FIRMessaging could not be found'.
---------------------------
Break   Continue   Help   
---------------------------

**Comment by thebugger2000** [comment]
iOS: I've about got a new application working but i get "no valid ""aps-environment"" entitlement string found for application" from the FCMFailedToRegister for my app.  the demo app works find and is granted.
Any thoughts on where that setting is in Delphi (i've been looking for at least a hour)

**Comment by DelphiWorlds** [comment]
If you have a "no valid ""aps-environment"" entitlement" error, you're likely using a provisioning profile that does not have an App ID with Push Notification entitlements. Please refer to the information here: https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FirebaseCloudMessaging#apple-developer-portal-ios

**Comment by thebugger2000** [comment]
I have two projects.  sharing the bundle identifer so I know it works on the apple side.  One I'm creating from scratch, the other  is the Kastri FCMDemo.dproj.   The FCMDemo.dproj with my own bundle identifier will work without generating the aps-environment error.  but My file new project generates that error.  I found the aps_development.cer file but I can't seem to figure out how to integrate it in Delphi. I just feel like theres a delployment option, a .pem .p12 .plist option strings.xml setting that I'm not seeing in the documentation you've provided.  Any other thoughts?

**Comment by thebugger2000** [comment]
Android: I keep getting Granted: -1.  What a other tools do I have in the Kastri FCM Library to findout more about this kind of issue?

**Comment by DelphiWorlds** [comment]
Can you clarify what you mean by "Granted: -1"?

**Comment by thebugger2000** [comment]
Ok.  everything is working except the android foreground thing (my original issue).  I read through one of the links you sent me about sending "data" in the message to get the foreground app to receive the message, but what that documentation was missing was a code example of a JSON payload that should work.  I've tried guessing a couple of different ways with no success. It would help me if I could see a working json payload sample you know works (minus personal info of course).  Could you post one here update your docs and send me that link please?   Thank you in advance.

**Comment by DelphiWorlds** [comment]
Can you let me know whether this is still an issue?

**Comment by DelphiWorlds** [comment]
Closed due to no response
