### ISSUE TITLE
USSD request and response 

### ISSUE THREAD

**Issue by TusurGPO** [DelphiWorlds/Kastri#58]
Add an example USSD request and receive a response to your program. On the Internet, there is no competent call to the sendUssdRequest function and passing TJTelephonyManager_UssdResponseCallback parameters to it.

**Comment by DelphiWorlds** [comment]
I've created an implementation and a basic demo for this, over in the [Playground repo](https://github.com/DelphiWorlds/Playground/tree/main/Demos/UssdRequester).
