### ISSUE TITLE
CrossPlatformLocation hangs when GPS is not in High Accuracy

### ISSUE THREAD

**Issue by monillo-hub** [DelphiWorlds/Kastri#59]
Hi Dave, 
I still cannot make the app work in another GPS Modes.
It only works in High Accuracy. Tested in (Samsung) Android 7,8
In the other modes, app hangs
What can I be missing?

![image](https://user-images.githubusercontent.com/70657322/129509616-ed9e0247-77aa-44cf-9ae5-5714d18d3550.png)
Thanks in advance.

**Comment by DelphiWorlds** [comment]
Note to myself: Needs a Priority property that can be set from the application, and read from the service

**Comment by bsu75** [comment]
I cannot run the demo, but it raise the below error:
[DCC Fatal Error] E2202 Required package 'DataSnapCommon' not found

I am using 10.4.2, and Datasnap already installed.

I cannot install the below
a) DataSnapCommon270.bpl 
b) dclDataSnapCommon270.bpl 
c) DataSnapFireDAC270.bpl

Can you advice me what to do?
Thank You.

**Comment by DelphiWorlds** [comment]
I don't understand why you are having this issue, since the demo does not use DataSnap.

**Comment by DelphiWorlds** [comment]
@monillo-hub Does this require any attention?

**Comment by DelphiWorlds** [comment]
Closed due to lack of response

**Comment by monillo-hub** [comment]
Seems that somebody added another issue to my initial issue.  (24 Aug 2021)
It has no relation with the initial issue.

I guess the issue is still alive and running.
