### ISSUE TITLE
Error using nfcdemo

### ISSUE THREAD

**Issue by gilfgfilho** [DelphiWorlds/Kastri#6]
@DelphiWorlds  try to debug nfcdemo in tree diferents devices (LG, Samsung an Sunmi) and all of the return an error when Delphi try to deploy de app to the device.

"project nfcdemo.apk raised exception class segmentation fault (11)"

Anybody had this problem alredy?

Thanks

**Comment by DelphiWorlds** [comment]
Fixed by https://github.com/DelphiWorlds/Kastri/commit/05f2fce4a22bc13633d1d34d60623c348693d527
