### ISSUE TITLE
Bug in Biometry for IOS causing GetBiometryKind detection to always return None

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Kastri#64]
There's a bug in DW.Biometry.iOS.pas which means GetBiometryKind will return None for phones with TouchID.

Because the TLAContext is being created within this function, the required .canEvaluatePolicy() is never called on it so it always return the default value of None regardless of the hardware available.
Wrapping the check in a .canEvaluatePolicy() fixes the call.

Fix:
class function TPlatformBiometric.GetBiometryKind: TBiometryKind;
var
  LContext: LAContext;
begin
  LContext := TLAContext.Create;
  if LContext.canEvaluatePolicy(cBiometryMode, nil) then
  begin
    case LContext.biometryType of
      LABiometryTypeFaceID:
        Result := TBiometryKind.Face;
      LABiometryTypeTouchID:
        Result := TBiometryKind.Touch;
    else
      Result := TBiometryKind.None;
    end;
  end
  else
    Result := TBiometryKind.None;
end;

**Comment by DelphiWorlds** [comment]
Fixed
