### ISSUE TITLE
JLocalBroadcastManager not found in Demo error

### ISSUE THREAD

**Issue by zburns** [DelphiWorlds/Kastri#66]
**Description**
Project FCMDemoD11.apk raised exception class EJNI with message 'Java type JLocalBroadcastManager could not be found' in the FCMDemo11 project.

**Error messages**
Compiles fine and I have the appropriate paths in the compiler.  (This is Delphi 11 side-by-side install with Develop 10.4.2 installed previously.)

**Please indicate**
Delphi Version: 11
Platform(s) that the issue occurs on (i.e. iOS, Android etc): Android 32-bit
If mobile, device model and OS version (e.g. Pixel 3a, Android 11): Android 9 Chinese Umidigi device

**Steps To Reproduce**
Concise steps to reproduce the behaviour: 

Downloaded current Kastri and placed in C:\Users\xxxxxxxxxx\Documents\Embarcadero\Studio\Kastri
Loaded FCMDemoD11 project, and changed target to 32-bit android debug live device
Run in debug mode and it compiles, but get the above run-time error.
(I saw something in the slack channel on September 15, but the user didn't state the full resolution to the issue.)
(Also first time playing with Kastri-so please advise if I'm doing something wrong.)  Thanks!

**Comment by DelphiWorlds** [comment]
Compile issue should be fixed now. You may find functionality issues, though. I am looking at those today
