### ISSUE TITLE
Demo\FilesSelector is not working under iOS 14

### ISSUE THREAD

**Issue by theodore74** [DelphiWorlds/Kastri#68]
I am using RAD 10.4.2 with iPhoneX (OS ver 14)
Just deploy FilesSelector demo to iphone and it get nothing. 

Any advice? Tks.

**Comment by DelphiWorlds** [comment]
What do you mean by "it get nothing."? Does nothing at all appear? This is what I see when it starts:

![image](https://user-images.githubusercontent.com/22670829/137418608-f5fd844d-285b-4bf3-8868-0966aab3a2f8.png)

**Comment by theodore74** [comment]
Thanks for quick response.
Of course, it should be. What I mean is click pics, popup a empty content form, nothing from MediaLibrary.

**Comment by DelphiWorlds** [comment]
>  I don't see photo gallery in your screen capture.
Yes, not sure why that is. I'll be looking into it

**Comment by theodore74** [comment]
hi, have any update?

**Comment by DelphiWorlds** [comment]
Not as yet, sorry. I have put it on my to-do list to attend to within the next few days.

**Comment by theodore74** [comment]
Is it unsolvable? 
RAD is good but is not friendly for iOS coding.

**Comment by DelphiWorlds** [comment]
I don't know whether it is unsolvable. I need to take a look at it

**Comment by DelphiWorlds** [comment]
Apologies that it has taken a while to address this, however I've just pushed some changes that will show the relevant picker for images in the media gallery if you use `TFileKind.Photo` for the `FileKinds` property. 

Note that this method _does not actually give direct access to the image file_, however using the `OnImageStream` event you can either use the image in the stream however you need to (in the demo the images are loaded into instances of `TImage`), and the original filename of the image is supplied in that event, so if you desire, you can save it to a file somewhere.
