### ISSUE TITLE
Speech Recognition Demo don´t work at Android (Delphi 11, Google Pixel Android 12)

### ISSUE THREAD

**Issue by AmandaSoftware** [DelphiWorlds/Kastri#69]
Speech Recognition Demo don´t work more on Android 12 and Delphi 11

with de_DE dont work but with en_US works. maybe a bug of android 12?

procedure TPlatformSpeechRecognition.DoStartRecording;
var
  LIntent: JIntent;
begin
  LIntent := TJIntent.JavaClass.init(TJRecognizerIntent.JavaClass.ACTION_RECOGNIZE_SPEECH);
  LIntent.putExtra(TJRecognizerIntent.JavaClass.EXTRA_LANGUAGE_MODEL, TJRecognizerIntent.JavaClass.LANGUAGE_MODEL_FREE_FORM);
  LIntent.putExtra(TJRecognizerIntent.JavaClass.EXTRA_LANGUAGE, stringToJString('en-US'));  
  LIntent.putExtra(TJRecognizerIntent.JavaClass.EXTRA_PROMPT, StringToJString(Speech.Prompt));
  FSpeechRecognizer.startListening(LIntent);

**Comment by DelphiWorlds** [comment]
@AmandaSoftware Can you specify what errors you're seeing?

**Comment by DelphiWorlds** [comment]
Closed due to lack of response
