### ISSUE TITLE
No FCM Push Token on Android first start after installation

### ISSUE THREAD

**Issue by SIG89** [DelphiWorlds/Kastri#7]
I‘m facing a weird situation with Kastri FCM on Android. I install my App on my Android Smartphone and toggle a switch to turn on the FCM. The component is created, handler get assigned as well but I don’t receive a PushToken right away. I close the app completely, restart, Toggle the switch again and I get a PushToken.

**Comment by DelphiWorlds** [comment]
Do you have an example project that reproduces the issue? The FCMDemo project in Demos\FirebaseCloudMessaging works OK for me

**Comment by SIG89** [comment]
Sorry for the delay, I added some sample Code.

`
unit FCM;

interface

uses
{$region 'Namespaces'}
  System.SysUtils
, System.Types
, System.UITypes
, System.Classes
, System.Variants
, System.JSON
, FMX.Types
, FMX.Controls
, FMX.Forms
, FMX.Graphics
, FMX.Dialogs
, FMX.StdCtrls
, FMX.Controls.Presentation
, FMX.ScrollBox
, FMX.Memo
, DW.PushNotification

;
{$endregion}

type
  TForm1 = class(TForm)
    Memo1: TMemo;
    Button1: TButton;
    procedure FormCreate(Sender: TObject);
  private
    { Private-Deklarationen }

    FPushNotifications : TPushNotifications;

    {$region 'procedure RPNInit'}
    ///<summary>
    /// Initialisieren der FCM Push Nachrichten
    ///</summary>
    procedure RPNInit;
    //
    {$endregion}

    {$region 'procedure PushNotificationsTokenReceivedHandler'}
    ///<summary>
    ///
    ///</summary>
    procedure PushNotificationsTokenReceivedHandler(Sender: TObject);
    //
    {$endregion}

    {$region 'procedure PushNotificationsMessageReceivedHandler'}
    ///<summary>
    ///
    ///</summary>
    procedure PushNotificationsMessageReceivedHandler(Sender: TObject; const AJSON: TJSONObject);
    //
    {$endregion}

  public
    { Public-Deklarationen }
  end;

var
  Form1: TForm1;

implementation

{$R *.fmx}
{$R *.LgXhdpiPh.fmx ANDROID}

procedure TForm1.FormCreate(Sender: TObject);
begin
    Memo1.Lines.Add('TForm1 erzeugt');
    RPNInit;
end;

procedure TForm1.RPNInit;
begin
  try
    if not Assigned(FPushNotifications) then
    begin
      Memo1.Lines.Add('RPNInit:');
      FPushNotifications := TPushNotifications.Create('ChannelID');
      FPushNotifications.OnMessageReceived := PushNotificationsMessageReceivedHandler;
      Memo1.Lines.Add('OnMessageReceived Handler zugewiesen');
      FPushNotifications.OnTokenReceived := PushNotificationsTokenReceivedHandler;
      Memo1.Lines.Add('OnTokenReceived Handler zugewiesen');
      FPushNotifications.Start;
      Memo1.Lines.Add('FPushNotifications.Start');
    end;
  except on E: Exception do
  begin
    Memo1.Lines.Add('procedure RPNInit ' + E.ClassName + ' ' + E.Message);
  end;
  end;
end;

procedure TForm1.PushNotificationsTokenReceivedHandler(Sender: TObject);
begin
  try
  Memo1.Lines.Add('PushNotificationsTokenReceivedHandler START');
  Memo1.Lines.Add('DeviceID erhalten: ' + FPushNotifications.DeviceID );
  Memo1.Lines.Add('DeviceToken erhalten: ' + FPushNotifications.DeviceToken);
  except on E: Exception do
    begin
      Memo1.Lines.Add('PushNotificationsTokenReceivedHandler ' + E.Message + ' ' + E.ToString);
    end;
  end;
end;

procedure TForm1.PushNotificationsMessageReceivedHandler(Sender: TObject; const AJSON: TJSONObject);
begin
  try
    Memo1.Lines.Add(AJSON.ToString);
  except on E: Exception do
    begin
    Memo1.Lines.Add('PushNotificationsMessageReceivedHandler' + e.Message);
    end;
  end;
end;

end.
`

**Comment by SIG89** [comment]
I was using the obsolete Kastri Free libs, I tried with the Kastri libs and it worked
