### ISSUE TITLE
[Connectivity] OnConnectivityChange does not fire in Windows 10

### ISSUE THREAD

**Issue by jkour** [DelphiWorlds/Kastri#70]
**Description**
In Windows 10, the OnConnectivityChange does not fire when the network status changes

**Error messages**
N/A

**Please indicate**
Delphi Version: 10.4.2
Windows 10

**Steps To Reproduce**
1. Run the demo
2. Disable the network adapter/wifi in Windows
3. The demo does not show the change to the network status

**Comment by DelphiWorlds** [comment]
Very odd.. it was all working when it was checked in. I'll take a look sometime this week

**Comment by DelphiWorlds** [comment]
I did take a look at it that week.. still no solution. Will try again within the next week

**Comment by jkour** [comment]
Hi David,
I know...I tried to see what is going on too but wasn't able to

**Comment by westner** [comment]
Any progress here?

**Comment by DelphiWorlds** [comment]
Fix committed
