### ISSUE TITLE
DW Camera Delphi 11

### ISSUE THREAD

**Issue by alissonrodrigo** [DelphiWorlds/Kastri#71]
[DCC Error] DW.Camera.Android.pas(831): E2250 There is no overloaded version of 'RequestPermissions' that can be called with these arguments

**Comment by SIG89** [comment]
Permission have changed in D11!
You need to change the definition of the calling parameter types of the RequestPermissions method from Stringlist to `const APermissions: TClassicStringDynArray; const AGrantResults: TClassicPermissionStatusDynArray.`

**Comment by DelphiWorlds** [comment]
> Have the properties been removed?
No. They may have been in the original Camera project (which was separate to KastrI), but you need only look at the commit history to see that they have never been in this source: https://github.com/DelphiWorlds/Kastri/commits/master/Features/Camera

**Comment by DelphiWorlds** [comment]
Fixed the compile issue

**Comment by alissonrodrigo** [comment]
Thank you all questions have been answered.
I don't know if here would be the place to ask this, but I'm studying your library right now and it's amazing. In the camera demo when I take a picture there is a deley of at least 2 seconds before showing the taken picture. i'm trying to create a wait message with the frozen photo, could you tell me which way i can go for this?
Grateful

**Comment by DelphiWorlds** [comment]
> when I take a picture there is a delay of at least 2 seconds

Unfortunately this is an issue I am yet to find a viable solution for. I plan to revisit it before the end of the month

**Comment by alissonrodrigo** [comment]
If you have a solution posted here on the community forum.
Thanks
