### ISSUE TITLE
Native Controls - TNativeRectangle, TNativeEllipse Opacity does not work

### ISSUE THREAD

**Issue by MarkBracey** [DelphiWorlds/Kastri#73]
Using the NativeControlsDemo I set the opacity of the TNativeRectange and TNativeEllipse to 0.1 but the control renders and full Opacity (1)

**Please indicate**
Delphi Version: 10.4.2
Platform(s) that the issue occurs on (i.e. iOS, Android etc):
Android

If mobile, device model and OS version (e.g. Pixel 3a, Android 11): 
Galaxy S20 FE 5G    Android 11

**Steps To Reproduce**
Take the NativeControlsDemo that comes with Katri and change the Opacity of the two controls mentioned above.

**Comment by DelphiWorlds** [comment]
Delphi 11, or 10.4.2?

**Comment by MarkBracey** [comment]
> Delphi 11, or 10.4.2?

10.4.2

**Comment by DelphiWorlds** [comment]
Fixed
