### ISSUE TITLE
[CrossPlatformLocation] Investigate using a Worker for location updates

### ISSUE THREAD

**Issue by DelphiWorlds** [DelphiWorlds/Kastri#76]
As per the title - a standard service needs to be run in the foreground if the app is in the background or not running, so use a Worker or alternative service, as per the docs: 

https://developer.android.com/training/location/background

**Comment by MicrotronX** [comment]
I use your CrossPlatformLocation demo for testing background-location-updates.
Everything works until i close the app on android(64) from current active apps ... this terminates the Mainactivity and starting from this second on the background-service hangs. Restarting the app again starts the App but the LocationService is hanging. I can send commands to it but it never receives these. Only stopping the app completely from "Android Applications" + Stop button and restarting the app starts the service and works.

I'm missing something or is this a known issue?

Should the background-service not be able to run also if the main-application gets "terminated"?

**Comment by DelphiWorlds** [comment]
> I'm missing something or is this a known issue?

I have someone else having this same issue - I can reproduce it using their code, but it does not happen for me in the demo. I am yet to find out why this happens, however I am working on an alternative as per this enhancement request. You can find the [work in progress here](https://github.com/DelphiWorlds/Playground/tree/main/Demos/Location).

> Should the background-service not be able to run also if the main-application gets "terminated"?

The intention in the original demo is for the service to keep running when the app is terminated. As I say, the demo works fine for me.

**Comment by MicrotronX** [comment]
Thank you very much for this info, I will try to use your "Work in progress version" for further tests ...

**Comment by DelphiWorlds** [comment]
I have been doing some testing today.. the location updates do not seem to be occurring as often as I would like. I'll be doing more testing over the next couple of days

**Comment by magnolima** [comment]
> I have someone else having this same issue - I can reproduce it using their code, but it does not happen for me in the demo. I am yet to find out why this happens, however I am working on an alternative as per this enhancement request. You can find the [work in progress here](https://github.com/DelphiWorlds/Playground/tree/main/Demos/Location).

I don't have enough knowledge to understand all of what is the code, but if I try to copy the NMEA handler from the original CrossPlatformLocation demo to this one, would it work? I ask before trying it just for the sake of time.

**Comment by DelphiWorlds** [comment]
>  if I try to copy the NMEA handler from the original CrossPlatformLocation demo to this one, would it work?

No, that would not affect it, and the NMEA handler is separate from the Fused Location API anyway

**Comment by magnolima** [comment]
So, if I move the code it won't work, right?

**Comment by DelphiWorlds** [comment]
> So, if I move the code it won't work, right?

It won't fix anything

**Comment by magnolima** [comment]
> > So, if I move the code it won't work, right?
> 
> It won't fix anything

Sorry, I guess I am not being able to make my question clear. I am not expecting that it would fix anything, the question is because looks like that this demo (using the worker)  isn't treating the NMEA, so if I "copy paste" the NMEA handle into this code, would it work?

**Comment by DelphiWorlds** [comment]
> this demo (using the worker) isn't treating the NMEA
The (new) demo being referred to is not using a worker at all. If you want to have NMEA messages, it appears you have to use a LocationListener, such as was used in the original demo. I don't think you could use the new demo to do this - you would probably be better off using the original demo, at least for now

**Comment by DelphiWorlds** [comment]
Closing this issue as it appears it may be a long wait for EMBT to implement the Worker class (it will likely be similar to the Service implementation)
