### ISSUE TITLE
AndroidStartAtBoot Demo not work

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/Kastri#82]
I Compile and Run AndroidStartAtBootD11 on my device
But nothing happens after the device is turned on

**Comment by DelphiWorlds** [comment]
Works fine here. It can take a minute or two for it to start

**Comment by kabiri** [comment]
For me it has not started yet (after 40 minutes)
To rest assured, I restarted once more
I waited 5 minutes but nothing happened again
Do I need to adjust certain Permisin?

Galaxy A32 , Android 11

**Comment by DelphiWorlds** [comment]
Are you compiling the actual demo, or your own project? There are two permissions set in the demo: Receive Boot Completed and Use Full Screen Intent. Also the demo uses a build event (in the Project Options, Building > Build Events) to merge the AndroidManifest.merge.xml with the manifest that Delphi creates

**Comment by kabiri** [comment]
I compiled and installed your demo for 64-bit Android
And I did not change anything in the project

**Comment by kabiri** [comment]
I test in x32 and work and sowitch to x64 but not work in x64

**Comment by kabiri** [comment]
In x64 progect i R-Click on Libraries and select "Revert system files to default" and compile and run , problem solved

**Comment by kabiri** [comment]
How change notification MSG 
it show "Please tap this notification for the ..."

**Comment by DelphiWorlds** [comment]
It's in the Java code. I'll look at making a change that allows you to configure it from Delphi code

**Comment by DelphiWorlds** [comment]
Fixed the library references for 64-bit

**Comment by kabiri** [comment]
> How change notification MSG it show "Please tap this notification for the ..."

Has it been added?

**Comment by DelphiWorlds** [comment]
Not as yet. As per my earlier comment, please refer to this issue: https://github.com/DelphiWorlds/Kastri/issues/83
