### ISSUE TITLE
[StartAtBoot] Allow changes to the startup notification message

### ISSUE THREAD

**Issue by DelphiWorlds** [DelphiWorlds/Kastri#83]
As per title. Needs changes to the broadcast receiver to read from shared preferences or metadata

**Comment by kabiri** [comment]
Thanks

**Comment by kabiri** [comment]
Has this problem been fixed?
How to use it?

**Comment by DelphiWorlds** [comment]
The change is yet to be included. Thanks for the reminder

**Comment by DelphiWorlds** [comment]
The change is achieved by the use of the manifestmerge tool. In the Project Options of the demo, look at the Build Events:

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/22670829/176554802-f1b63ff2-ece6-45bf-b0ee-0df84d7bff15.png">

This is the file that gets merged into the manifest:

https://github.com/DelphiWorlds/Kastri/blob/master/Demos/AndroidStartAtBoot/AndroidManifest.merge.xml

**Comment by DiamatBR** [comment]
Which of these options do I choose?
![image](https://user-images.githubusercontent.com/77128586/176779872-f14773ae-6e63-426f-9fe3-b6a667f3a5b2.png)

**Comment by DelphiWorlds** [comment]
You don't choose any of those options. The command just needs to be present, as per the image I posted. 

In the demo, the Tools folder is two levels up, which is why the path is: `..\..\Tools\manifestmerge` for the command. The `AndroidManifest.merge.xml` file is in the same folder as the demo, and the target `$(Platform)\$(Config)\AndroidManifest.xml` is what is generated by Delphi

**Comment by alextim400** [comment]
I tried to test this project (Delphi 11.2) on an android 12 device. And unfortunately it doesn't work. At the same time, the example compiled in Delphi 10.4 works on this device. What's the matter here?

**Comment by DelphiWorlds** [comment]
Although my comment above still applies, I have discovered issues that I have now pushed changes for - the `AndroidManifest.merge.xml` and `dw-kastri-base-2.0.0.jar` files have been updated

**Comment by alextim400** [comment]
Many thanks. With updated dw-kastri-base-2.0.0.jar it worked. I fixed the AndroidManifest.merge.xml file even earlier.

**Comment by DelphiWorlds** [comment]
Great!
