### ISSUE TITLE
[adMob] Add a variety of ads

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/Kastri#84]
Please add display of Google ads such as:
Interstitial
Rewarded interstitial
Rewarded
Native advanced
App open
Delphi only supports Banners

**Comment by DelphiWorlds** [comment]
Please visit the [Playground](https://github.com/DelphiWorlds/Playground/tree/main/Demos/Advertising) for an implementation of Interstitial. More coming later.. maybe :-)

**Comment by kabiri** [comment]
Thanks

**Comment by kabiri** [comment]
When Rewarded ad added?
Why https://github.com/DelphiWorlds/Playground/tree/main/Demos/Advertising removed?

**Comment by DelphiWorlds** [comment]
RewardedAd is in there. The demo was renamed to: https://github.com/DelphiWorlds/Playground/tree/main/Demos/AdMob
