### ISSUE TITLE
[Geofence] Region ids are lost after closing the app

### ISSUE THREAD

**Issue by DelphiWorlds** [DelphiWorlds/Kastri#85]
As per title.

**Comment by DelphiWorlds** [comment]
Fixed

**Comment by jornada812** [comment]
Hello.  Has this been fixed for sure?  I keep losing IDs

**Comment by DelphiWorlds** [comment]
Sorry, it was fixed for Delphi 10.4.2. Should now also be fixed for Delphi 11
