### ISSUE TITLE
Several compilation errors under Alexandria

### ISSUE THREAD

**Issue by westner** [DelphiWorlds/Kastri#86]
When compiling KastriBuild for iOS 64 I get errors and warnings:

[DCC Warning] DW.Connectivity.Mac.pas(118): W1002 Symbol 'IFF_UP' is specific to a platform
[DCC Warning] DW.Connectivity.Mac.pas(118): W1002 Symbol 'IFF_UP' is specific to a platform
[DCC Hint] DW.Camera.iOS.pas(296): H2164 Variable 'LOrientation' is declared but never used in 'TPlatformCamera.GetCorrectedImage'
[DCC Hint] DW.Camera.iOS.pas(319): H2164 Variable 'LMetadata' is declared but never used in 'TPlatformCamera.CaptureStillImageCompletionHandler'
[DCC Hint] DW.Camera.iOS.pas(320): H2164 Variable 'LMetadataMutable' is declared but never used in 'TPlatformCamera.CaptureStillImageCompletionHandler'
[DCC Hint] DW.Camera.iOS.pas(47): H2219 Private symbol 'FRequestHandler' declared but never used
[DCC Warning] DW.Connectivity.iOS.pas(110): W1002 Symbol 'IFF_UP' is specific to a platform
[DCC Warning] DW.Connectivity.iOS.pas(110): W1002 Symbol 'IFF_UP' is specific to a platform
[DCC Warning] DW.NativeButton.pas(48): W1000 Symbol 'pidAndroid32Arm' is deprecated: 'Use pidAndroidArm32'
[DCC Warning] DW.NativeButton.pas(48): W1000 Symbol 'pidAndroid64Arm' is deprecated: 'Use pidAndroidArm64'
[DCC Warning] DW.NativeShape.pas(92): W1000 Symbol 'pidAndroid32Arm' is deprecated: 'Use pidAndroidArm32'
[DCC Warning] DW.NativeShape.pas(92): W1000 Symbol 'pidAndroid64Arm' is deprecated: 'Use pidAndroidArm64'
[DCC Warning] DW.NativeShape.pas(164): W1000 Symbol 'pidAndroid32Arm' is deprecated: 'Use pidAndroidArm32'
[DCC Warning] DW.NativeShape.pas(164): W1000 Symbol 'pidAndroid64Arm' is deprecated: 'Use pidAndroidArm64'
[DCC Error] DW.NativeShape.iOS.pas(45): E2003 Undeclared identifier: 'MM_NATIVESHAPE_SET_OPACITY'
[DCC Error] DW.NativeShape.iOS.pas(45): E2139 Illegal message method index
[DCC Fatal Error] DW.Precompile.pas(248): F2063 Could not compile used unit 'DW.NativeShape.iOS.pas'

When compiling for Mac OS X Intel / ARM 64 I get

[dccosx64 Error] E2597 ld: warning: directory not found for option '-L..\..\Features\AssetsManager'
  ld: warning: directory not found for option '-L..\..\Features\GoogleSignIn'

Under Windows I get:
[dcc32 Warning] DW.SpeechRecognition.pas(182): W1020 Constructing instance of 'TPlatformSpeechRecognition' containing abstract method 'TCustomPlatformSpeechRecognition.RequestPermission'

**Comment by DelphiWorlds** [comment]
Compiler errors now resolved, as well as nearly all hints/warnings. 

**Note: on iOS/macOS, linker errors may be due to having not imported dependent frameworks into the SDK**
On iOS, please ensure that at least the following frameworks are imported:

AppTrackingTransparency
ARKit
AuthenticationServices
CallKit
CoreML
CoreNFC
Messages
Photos
PhotosUI
PushKit
QuickLook
SceneKit
Speech
SpriteKit
Vision
VisionKit

**Comment by westner** [comment]
Thanks.

But search for pidAndroid32Arm in Code there are still some places where the conditional definie is missing.

**Comment by DelphiWorlds** [comment]
> But search for pidAndroid32Arm in Code there are still some places where the conditional define is missing.

When reporting an issue like this, please indicate **where**. At present, I cannot see any missing.

> And iOS /Mac still have a warning:

The warning does not appear for me using the current source. Please ensure you update before reporting issues.

 > [dcc64 Hint] DW.Connectivity.Win.pas(55): H2219 Private symbol 'Start' declared but never used
 
 That one I am leaving for now.

**Comment by westner** [comment]
I downloaded the latest source before I report the issue.

But I downloaded it again just now and can confirm that now all is fxed.

Thanks.

**Comment by DelphiWorlds** [comment]
Closing, per last comment :-)
