### ISSUE TITLE
Calling TConnectivity.IsConnectedToInternet in a thread throws an error

### ISSUE THREAD

**Issue by westner** [DelphiWorlds/Kastri#89]
Hello,

I spawn a thread (TThread.Create) from my main-thread and do some work in this thread.

At some place in the thread.execute I do a 

TConnectivity.IsConnectedToInternet

but this throws and error:

An interface which was marshalled for another thread was call from the program.

The funny thing is that on windows 10 this works but when I run our program on a terminalserver I get this error.

BTW, there must be something wrong here.

I tried to change

constructor TNetwork.Create;
begin
  inherited;
//  CoInitialize(nil);
CoInitializeEx( nil , COINIT_MULTITHREADED);
  FNetworkListManager := CoNetworkListManager.Create;
  FIsConnectedToInternet := GetIsConnectedToInternet;
end;

but this doesn't help too.

Any idea?

This issue is a little bit critical because it's a showstopper for all users of our software on a terminalserver... :-(

Greetings

Stefan

**Comment by DelphiWorlds** [comment]
Notwithstanding the issue, I'm curious as to why you would use this code on a terminal server at all. The fact that they are remoting to the machine means it has connectivity.

**Comment by DelphiWorlds** [comment]
Can you give the *exact* error message, please?

**Comment by westner** [comment]
Sure, but the EXCAT error message is in german:
Eine Schnittstelle, die für einen anderen Thread marshalled war, wurde von der Anwendung aufgerufen.

**Comment by DelphiWorlds** [comment]
Thanks.. the exact error message provides more hits in Google :-) I'll look into it

**Comment by DelphiWorlds** [comment]
I'm not set up for Terminal Services, so can you try the following where you call `TConnectivity.IsConnectedToInternet`:

```
  TThread.Synchronize(nil,
    procedure
    begin
      if TConnectivity.IsConnectedToInternet then
        // Do whatever you are doing, here..
    end
  );
```

**Comment by westner** [comment]
This doesn't solve the problem...

**Comment by westner** [comment]
If you want I can provide you a VMWare Workstation / Player Virtualmaschine with a installed Terminalserver and a testproject to reproduce the problem. I'm willing to donate the money you want as an hourly fee. Send me a mail at westner@kic-software.de if you are willing to support us in this issue and I will send you the downloadlinks and so on. Thanks

**Comment by westner** [comment]
Any feedback already?

**Comment by DelphiWorlds** [comment]
I've sent you an email.. thanks!

**Comment by DelphiWorlds** [comment]
Fixed
