### ISSUE TITLE
[DEMO] MacOSToolBar demo

### ISSUE THREAD

**Issue by acarlomagno** [DelphiWorlds/Kastri#90]
[MACOS] MacOsToolBar demo

compile and linking works fine .. but when deploy on MacOS tha PAServer display some errors and the application start and close immediately

these are PAServer lines error:

>Exception EAccessViolation in module libobjc.A.dylib at 00007FFF201D6829.
Access violation at address 00007FFF201D6829, accessing address 00007FFF80A76FE8.
objc[740]: objc_disposeClassPair: class 'FMXWindow' still has subclasses, including 'NSKVONotifying_FMXWindow'!
objc[740]: objc_disposeClassPair: class 'FMXWindow' still has subclasses, including 'NSKVONotifying_FMXWindow'!

MacOS Big Sur 11.6 - XCode 13.0
Delphi 11

**Comment by DelphiWorlds** [comment]
Committed changes that should fix it

**Comment by acarlomagno** [comment]
works fine!
