### ISSUE TITLE
[DCC Fatal Error] DW.OSLog.pas(119): F2063 Could not compile used unit 'DW.OSDevice.pas'

### ISSUE THREAD

**Issue by alissonrodrigo** [DelphiWorlds/Kastri#91]
Hello, I'm trying to use the library to manage the push notification but it's returning this error when compiling for iOS, for Android everything is ok.

[DCC Error] DW.OSDevice.pas(321): E2003 Undeclared identifier: 'OpenWriteSettingsPermissions'
[DCC Fatal Error] DW.OSLog.pas(119): F2063 Could not compile used unit 'DW.OSDevice.pas'

**Comment by DelphiWorlds** [comment]
Please make sure you have updated Kastri files before compiling

**Comment by alissonrodrigo** [comment]
I updated to the latest version on github. but now I get the following message
[DCC Error] E2597 ld: file not found: PromisesObjC
[DCC Fatal Error] F2588 Linker error code: 1 ($00000001)

Search path project
![image](https://user-images.githubusercontent.com/8572209/150639050-9454ee9d-161e-44cc-a617-34daf644ecbe.png)

**Comment by DelphiWorlds** [comment]
This should have been reported as a separate issue. The paths you have are in `Search Path`, when they should be in `Framework search path` instead. Please refer to the Project Options in [this demo](https://github.com/DelphiWorlds/Kastri/tree/master/Demos/FirebaseCloudMessaging).

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
