### ISSUE TITLE
[CrossPlatformLocation] The Google Play services resources were not found. 

### ISSUE THREAD

**Issue by magnolima** [DelphiWorlds/Kastri#92]
**Description**
Even after completely deleted all the files from Kastri, downloading the newest zip instead of the git fetch, clean and rebuild, my app is still showing an error about a Google Play lib

Error messages:
**The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.**

The tag for the error is **GooglePlayServicesUtil**

The error seems not to crash the app though.

Delphi Version: 10.4.2
Platform(s) that the issue occurs on (i.e. iOS, Android etc): Android
If mobile, device model and OS version (e.g. Pixel 3a, Android 11): Samsung S10+ (Android 11), Redmi 7

**Comment by DelphiWorlds** [comment]
Not going to "fix" this unless it actually causes a problem
