### ISSUE TITLE
Expand DW.ServiceCommander.Android to have SendTextCommand()

### ISSUE THREAD

**Issue by magnolima** [DelphiWorlds/Kastri#93]
Can you add the SendTextCommand() version to the lib? =)

class procedure TServiceCommander.SendTextCommand(const ACommand: String);
var
  LIntent: JIntent;
begin
  LIntent := TJIntent.JavaClass.init(StringToJString(cServiceCommandAction));
  LIntent.putExtra(StringToJString(cServiceBroadcastParamCommand), StringToJString(ACommand));
  TJLocalBroadcastManager.JavaClass.getInstance(TAndroidHelper.Context).sendBroadcast(LIntent);
end;

**Comment by DelphiWorlds** [comment]
I've pushed a change to add a method called SendMessage, and updated the CrossPlatformLocation demo to handle it. Please let me know if the change works for you

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
