### ISSUE TITLE
Change colour on TQLPreview

### ISSUE THREAD

**Issue by elcharlie** [DelphiWorlds/Kastri#97]
Hello, I Have tested the QuickLook demo, and I think its fantastic, its very usefull and easy, but its possible to add a method o property to change the colours of the TQLPreview buttons?, (I think it is the toolbar, but I dont know) 
It would be fantastic.
Thank you.

**Comment by DelphiWorlds** [comment]
Apparently it is possible:

https://stackoverflow.com/questions/48821893/change-navigation-bar-color-in-qlpreviewcontroller

This is not a high priority item, so you may wish to try and figure it out yourself

**Comment by elcharlie** [comment]
Ok, Thank you.
